WebDriverUtils changes
CBIIT/CBIIT-Test-Automation pull request #131
Opened 2023-05-04 16:16 UTC by iamdez99

2023-05-04 16:40 UTC, hamidnesar approved these changes
@iamdez99 not sure if we are going to keep the deprecated browsers.

2023-05-04 16:40 UTC, hamidnesar commented on src/main/java/com/nci/automation/common/Constants.java
@iamdez99 are we going to keep IE on line 11 and Phantomjs on line 17 even though they are deprecated?

2023-05-04 16:40 UTC, hamidnesar commented on src/test/java/CustomBusiness/EIDP/Pages/LoginPage.java
@iamdez99 is it the compound class commented out?

2023-05-04 16:40 UTC, hamidnesar commented on src/test/java/ServiceNow/ITPG/Pages/LoginPage.java
@iamdez99 is it the compound class commented out?

2023-05-04 16:46 UTC, zamant2 commented on src/main/java/com/nci/automation/web/WebDriverUtils.java
> +
Empty line need to be removed

2023-05-04 16:47 UTC, zamant2 commented on src/main/java/com/nci/automation/web/WebDriverUtils.java
>  //import io.appium.java_client.MobileElement;
Empty line need to be removed

2023-05-04 16:50 UTC, zamant2 commented on src/main/java/com/nci/automation/web/WebDriverUtils.java
> +            if (Constants.BROWSER_MOBILE.equalsIgnoreCase(browser)) {
@iamdez99 , I think we need to be constant with the logic using (browser.equalsIgnoreCase(Constants.BROWSER_{browser name})) instead of (Constants.BROWSER_{browser name}.equalsIgnoreCase(browser))

2023-05-04 17:22 UTC, matakevin commented on pom.xml
Remove added space on line 240

2023-05-04 17:39 UTC, matakevin commented on src/test/java/CustomBusiness/EIDP/Pages/LoginPage.java
Commented code shouldn't be pushed to master

2023-05-04 17:40 UTC, matakevin commented on src/test/java/ServiceNow/SEER/Features/LandingPage.feature
Progression tag shouldn't be pushed to master

2023-05-04 17:41 UTC, matakevin commented on src/test/java/ServiceNow/ITPG/Pages/LoginPage.java
Commented code on lines 44, 45 shouldn't be pushed to master

2023-05-04 17:45 UTC, matakevin requested changes
Please make the changes outlined in the comments from the others and myself

2023-05-04 17:49 UTC, hamidnesar commented on src/main/java/com/nci/automation/web/WebDriverUtils.java
> +
I would remove the line 311

2023-05-04 20:16 UTC, iamdez99 commented on src/test/java/ServiceNow/ITPG/Pages/LoginPage.java
updated

2023-05-04 20:18 UTC, iamdez99 commented on src/main/java/com/nci/automation/common/Constants.java
updated

2023-05-04 20:19 UTC, iamdez99 commented on src/test/java/ServiceNow/ITPG/Pages/LoginPage.java
updated

2023-05-04 20:20 UTC, iamdez99 commented on src/main/java/com/nci/automation/web/WebDriverUtils.java
> +
updated

2023-05-04 20:21 UTC, iamdez99 commented on src/main/java/com/nci/automation/web/WebDriverUtils.java
>  //import io.appium.java_client.MobileElement;
updated

2023-05-04 20:23 UTC, iamdez99 commented on src/main/java/com/nci/automation/web/WebDriverUtils.java
> +            if (Constants.BROWSER_MOBILE.equalsIgnoreCase(browser)) {
this is ok, boolean condition is valid and there is no hardcoding

2023-05-04 20:24 UTC, iamdez99 commented on src/test/java/CustomBusiness/EIDP/Pages/LoginPage.java
updated

2023-05-04 20:24 UTC, iamdez99 commented on src/test/java/ServiceNow/SEER/Features/LandingPage.feature
updated

2023-05-04 20:28 UTC, iamdez99 commented on src/main/java/com/nci/automation/web/WebDriverUtils.java
> +
cleaned WebDriverUtils

2023-05-04 21:13 UTC, hamidnesar approved these changes

2023-05-05 13:27 UTC, zamant2 approved these changes

2023-05-05 14:57 UTC, alenaminsk commented
PR looks good, no comments

2023-05-05 15:12 UTC, alenaminsk approved these changes

2023-05-05 15:16 UTC, merged