George
CBIIT/CBIIT-Test-Automation pull request #136
Opened 2023-05-25 14:37 UTC by georgeb79

SEER test cases updated

2023-05-26 17:21 UTC, matakevin commented on src/main/java/com/nci/automation/web/CommonUtils.java
Line 430 camel casing seems to be off on "lastNAmeRandomizer"

2023-05-26 17:24 UTC, matakevin commented on src/test/java/ServiceNow/SEER/Constants/Registration_Constants.java
I could be wrong but to Addresses normally have underscores and hyphens?

2023-05-26 17:26 UTC, matakevin commented on src/test/java/ServiceNow/SEER/Features/LandingPage.feature
Double annotation "@@" on line 3 shouldn't be there

2023-05-30 18:03 UTC, georgeb79 commented on src/main/java/com/nci/automation/web/CommonUtils.java
Corrected. Thanks!

2023-05-31 17:57 UTC, matakevin commented on src/test/java/ServiceNow/SEER/Constants/Registration_Constants.java
Got it, great!  Thanks for clarifying!

2023-05-31 17:58 UTC, matakevin approved these changes
LGTM

2023-05-31 18:11 UTC, shomiruddin94 approved these changes

2023-06-02 15:22 UTC, matakevin commented on src/test/java/ServiceNow/SEER/Features/SEERDataAccessRequestPage.feature
Your regression tag on line 3 is misspelled

2023-06-02 15:25 UTC, matakevin requested changes
Hey George, I only have one change that I found that should be changed.  On the SEERDataAccessRequestPage.feature file

2023-06-02 15:35 UTC, matakevin approved these changes
LGTM

2023-06-05 16:46 UTC, iamdez99 commented on src/test/java/ServiceNow/SEER/Features/SEERDataAccessRequestPage.feature
verified

2023-06-05 17:03 UTC, merged