Zamant2
CBIIT/CBIIT-Test-Automation pull request #140
Opened 2023-06-09 19:54 UTC by zamant2

Few commented lines, which I might need to uncomment later.

2023-06-12 17:43 UTC, matakevin commented on src/main/resources/conf/env/stage.xml
What is the addition of the application tag on line 6 for?

2023-06-12 17:59 UTC, matakevin commented on src/test/java/CustomBusiness/BusinessAppRunners/RunAppDCEGProgressionTest.java
Regression runner being tagged "tz"

2023-06-12 18:00 UTC, matakevin commented on src/test/java/CustomBusiness/EIDP/Pages/CoPrimaryMentorPage.java
Commented sleep on line 186

2023-06-12 18:01 UTC, zamant2 commented on src/main/resources/conf/env/stage.xml
Updated

2023-06-12 18:02 UTC, matakevin commented on src/test/java/CustomBusiness/EIDP/Steps/CoPrimaryMentorSteps.java
Commented code on like 46

2023-06-12 18:03 UTC, matakevin commented on src/test/java/CustomBusiness/EIDP/Steps/DashboardSteps.java
Is the commented code on line 194 needed?

2023-06-12 18:13 UTC, matakevin commented on src/test/java/CustomBusiness/EIDP/Steps/IDPAwaitingResponseSteps.java
Commented line 35 doesn't seem needed

2023-06-12 18:23 UTC, zamant2 commented on src/test/java/CustomBusiness/BusinessAppRunners/RunAppDCEGProgressionTest.java
Updated

2023-06-12 18:23 UTC, zamant2 commented on src/test/java/CustomBusiness/BusinessAppRunners/RunAppEIDPRegressionTest.java
Fixed

2023-06-12 18:25 UTC, zamant2 commented on src/test/java/CustomBusiness/EIDP/Pages/CoPrimaryMentorPage.java
Updated

2023-06-12 18:46 UTC, georgeb79 requested changes
I left a few comments for items that need attention.

2023-06-12 18:46 UTC, georgeb79 commented on src/test/java/CustomBusiness/BusinessAppRunners/RunAppDCEGProgressionTest.java
Line 14 - This should have @Progression tag

2023-06-12 18:46 UTC, georgeb79 commented on src/test/java/CustomBusiness/BusinessAppRunners/RunAppEIDPRegressionTest.java
Line 13 - This should have @Regression tag

2023-06-12 18:46 UTC, georgeb79 commented on src/test/java/CustomBusiness/BusinessAppRunners/RunAppEIDPSanityTest.java
If this Runner uses a @Smoke tag I believe Smoke should be added un the file's name to be easily identifiable.

2023-06-12 18:46 UTC, georgeb79 commented on src/test/java/CustomBusiness/EIDP/Pages/CareerGoalAndActivePage.java
extra space lines 11 and 42. Please remove.

2023-06-12 18:46 UTC, georgeb79 commented on src/test/java/CustomBusiness/EIDP/Pages/CoPrimaryMentorPage.java
extra space line 173 Please remove.

2023-06-12 18:49 UTC, matakevin commented on src/test/java/CustomBusiness/EIDP/StepsImplementation/TraineeReviewStepsImpl.java
Is the try catch block needed here?

2023-06-12 18:52 UTC, matakevin reviewed
Clarification is needed for the try catch block being necessary but aside from that and the hardcoded credentials actually working or not, all the rest of the code looks good

2023-06-12 19:04 UTC, hamidnesar requested changes
Left a few comments. I noticed Thread.sleep and MiscUtils are used interchangeably across pages. I would recommend MiscUtils.sleep for consistency

2023-06-12 19:04 UTC, hamidnesar commented on src/test/java/CustomBusiness/BusinessAppRunners/RunAppDCEGProgressionTest.java
> +        ,junit = "--step-notifications"
missing monochrome and strict

2023-06-12 19:11 UTC, zamant2 commented on src/main/resources/conf/env/stage.xml
> +	<application>
updated

2023-06-12 19:16 UTC, zamant2 commented on src/test/java/CustomBusiness/EIDP/Pages/CoPrimaryMentorPage.java
>  	private WebElement primaryMentorComments;
There a lot of element using the private which need to be updated gradually

2023-06-12 19:24 UTC, zamant2 commented on src/test/java/CustomBusiness/BusinessAppRunners/RunAppEIDPSanityTest.java
Updated the runner

2023-06-12 19:28 UTC, zamant2 commented on src/test/java/CustomBusiness/EIDP/StepsImplementation/ProjectRelatedDeliverableStepImpl.java
Hardcoding issue will resolve gradually as I progress through test cases

2023-06-12 19:36 UTC, zamant2 commented on src/test/java/CustomBusiness/EIDP/StepsImplementation/TraineeReviewStepsImpl.java
removed the try catch block

2023-06-12 19:37 UTC, zamant2 commented on src/test/java/CustomBusiness/ETD/StepsImplementation/ETDFlowStepsImpl.java
yes

2023-06-12 20:19 UTC, matakevin commented on src/test/java/CustomBusiness/BusinessAppRunners/RunAppEIDPSmokeTest.java
monochrome and strict tags are missing and junit was added as a tag

2023-06-12 20:22 UTC, matakevin commented on src/test/java/CustomBusiness/BusinessAppRunners/RunAppEIDPSmokeTest.java
Tag is also "@Smoke " with a space added after

2023-06-12 20:27 UTC, hamidnesar commented on src/test/java/CustomBusiness/BusinessAppRunners/RunAppDCEGProgressionTest.java
> +        ,junit = "--step-notifications"
missing monochrome and strict tags

2023-06-12 20:34 UTC, matakevin commented on src/main/resources/conf/env/stage.xml
Line 196 "<!-- add test..." should be <!-- add stage..."

2023-06-12 20:40 UTC, matakevin approved these changes
LGTM

2023-06-12 20:59 UTC, hamidnesar approved these changes
It would be nice to remove the extra lines and have the closing brackets consistent across different runner classes.

2023-06-12 20:59 UTC, hamidnesar commented on src/test/java/CustomBusiness/BusinessAppRunners/RunAppEIDPSanityTest.java
> +		junit = "--step-notifications")
missing monochrome and strict tags

2023-06-12 20:59 UTC, hamidnesar commented on src/test/java/CustomBusiness/BusinessAppRunners/RunAppEIDPProgressionTest.java
Please remove the extra line

2023-06-12 20:59 UTC, hamidnesar commented on src/test/java/CustomBusiness/BusinessAppRunners/RunAppETDProgressionTest.java
> +
Please remove the extra line

2023-06-12 20:59 UTC, hamidnesar commented on src/test/java/CustomBusiness/BusinessAppRunners/RunAppETDRegressionTest.java
> +
Please remove the extra line. You have closing bracket on the same line as Strict in runners while on a new line a few

2023-06-13 13:04 UTC, georgeb79 approved these changes

2023-06-29 13:08 UTC, alenaminsk approved these changes

2023-07-07 13:48 UTC, alenaminsk approved these changes

2023-07-21 18:56 UTC, alenaminsk approved these changes

2023-08-03 14:02 UTC, iamdez99 approved these changes
Reviewed and approved - juarezds

2023-08-03 14:03 UTC, merged

2023-08-03 14:12 UTC, mzuhoor reviewed
Done