Upgraded Cucumber version and added screenshots to spark report
CBIIT/CBIIT-Test-Automation pull request #141
Opened 2023-06-13 17:30 UTC by shomiruddin94

2023-06-13 21:45 UTC, matakevin commented on src/main/java/com/nci/automation/web/CommonUtils.java
Is there a reason for the "//" slashes on lines 82-149?

2023-06-13 21:55 UTC, georgeb79 requested changes

2023-06-13 21:55 UTC, georgeb79 commented on src/test/java/AnalysisTools/AnalysisToolsRunners/RunComets2ProgressionTest.java
Please see commented-out imports

2023-06-13 21:55 UTC, georgeb79 commented on src/test/java/AnalysisTools/AnalysisToolsRunners/RunComets2SmokeTest.java
Please see commented-out imports

2023-06-13 21:55 UTC, georgeb79 commented on src/test/java/AnalysisTools/AnalysisToolsRunners/RunICRPSmokeTest.java
Please see commented-out imports

2023-06-13 21:55 UTC, georgeb79 commented on src/test/java/AnalysisTools/AnalysisToolsRunners/RunLDLinkRegressionTest.java
Please see commented-out imports

2023-06-13 21:55 UTC, georgeb79 commented on src/test/java/AnalysisTools/AnalysisToolsRunners/RunLDLinkSmokeTest.java
Please see commented-out imports

2023-06-13 21:55 UTC, georgeb79 commented on src/test/java/AnalysisTools/AnalysisToolsRunners/RunMSigPortalProgressionTest.java
Please see commented-out imports

2023-06-13 21:55 UTC, georgeb79 commented on src/test/java/AnalysisTools/AnalysisToolsRunners/RunMSigPortalSmokeTest.java
Please see commented-out imports

2023-06-13 21:55 UTC, georgeb79 commented on src/test/java/AnalysisTools/AnalysisToolsRunners/RunPLCOProgressionTest.java
Please see commented-out imports

2023-06-13 21:55 UTC, georgeb79 commented on src/test/java/AnalysisTools/AnalysisToolsRunners/RunPLCOSmokeTest.java
Please see commented-out imports

2023-06-13 21:55 UTC, georgeb79 commented on src/test/java/AnalysisTools/CEDCD/Steps/CEDCDAdminPageSteps.java
Please see commented-out imports

2023-06-13 21:55 UTC, georgeb79 commented on src/test/java/AnalysisTools/CEDCD/Steps/CEDCDBiospecimenCountClearAllSteps.java
Please see commented-out imports

2023-06-13 21:55 UTC, georgeb79 commented on src/test/java/AnalysisTools/CEDCD/Steps/CEDCDBiospecimenCountsAlphabeticalCancerTypeSteps.java
Please see commented-out imports

2023-06-13 21:55 UTC, georgeb79 commented on src/test/java/AnalysisTools/CEDCD/Steps/CEDCDBiospecimenCountsSelectAllCohortsSteps.java
Please see commented-out imports

2023-06-13 21:55 UTC, georgeb79 commented on src/test/java/AnalysisTools/CEDCD/Steps/HooksSteps.java
Please see commented-out imports

2023-06-13 21:55 UTC, georgeb79 commented on src/test/java/AnalysisTools/Comets2/Steps/HooksSteps.java
Please see commented-out imports

2023-06-13 21:55 UTC, georgeb79 commented on src/test/java/AnalysisTools/ICRP/Steps/HooksSteps.java
Please see commented-out imports

2023-06-13 21:55 UTC, georgeb79 commented on src/test/java/AnalysisTools/ICRP/Steps/ICRPSearchSteps.java
Please see commented-out line 37-38

2023-06-13 21:55 UTC, georgeb79 commented on src/test/java/AnalysisTools/JPSurv/Steps/JPSurvHomePageSteps.java
Please see commented-out line 34-41, 111-112, 140-141

2023-06-13 21:55 UTC, georgeb79 commented on src/test/java/AnalysisTools/cProSite/Pages/CProSiteExplorePage.java
Locators missing description

2023-06-13 21:55 UTC, georgeb79 commented on src/test/java/CustomBusiness/BusinessAppRunners/RunAppEIDPProgressionTest.java
Please see commented-out imports

2023-06-13 21:55 UTC, georgeb79 commented on src/test/java/CustomBusiness/DCEG/Steps/RegularUserFlowSteps.java
Please see commented-out imports

2023-06-13 21:55 UTC, georgeb79 commented on src/test/java/CustomBusiness/DCEG/StepsImplementation/FlowStepsImplementation.java
Please see commented-out imports

2023-06-13 21:55 UTC, georgeb79 commented on src/test/java/CustomBusiness/EIDP/Pages/IDPAwaitingResponsePage.java
Please see commented-out imports

2023-06-13 21:55 UTC, georgeb79 commented on src/test/java/ServiceNow/ATO/Pages/BasePage.java
Please see commented-out lines 199, 204 to 212, 217, 220, 222

2023-06-13 21:55 UTC, georgeb79 commented on src/test/java/ServiceNow/ATO/Pages/SecurityFormPage.java
Please see commented-out imports

2023-06-13 21:55 UTC, georgeb79 commented on src/test/java/ServiceNow/ATO/Steps/HookSteps.java
Please see commented-out imports

2023-06-13 21:55 UTC, georgeb79 commented on src/test/java/ServiceNow/ATO/Utils/ReportUtil.java
Please see commented-out imports

2023-06-13 21:55 UTC, georgeb79 commented on src/test/java/ServiceNow/CADSR/Pages/BasePage.java
Please see commented-out lines 231, 236-244, 249, 252

2023-06-13 21:55 UTC, georgeb79 commented on src/test/java/ServiceNow/CHARMS/Steps/MelanomaScreenerSubmission.java
Please see commented-out imports

2023-06-13 21:55 UTC, georgeb79 commented on src/test/java/ServiceNow/CHARMS/Steps/RASSurveySteps.java
Please see commented-out imports

2023-06-13 21:55 UTC, georgeb79 commented on src/test/java/ServiceNow/CICDBuildRunners/Run_CICD_DevOps_Application_Build_Test.java
Please see commented-out imports

2023-06-13 21:55 UTC, georgeb79 commented on src/test/java/ServiceNow/CICDBuildRunners/Run_CICD_DevOps_UpdateSet_Build_Test.java
Please see commented-out imports

2023-06-13 21:55 UTC, georgeb79 commented on src/test/java/ServiceNow/CICDBuildRunners/Run_CICD_Integration_Application_Build_Test.java
Please see commented-out imports

2023-06-13 21:55 UTC, georgeb79 commented on src/test/java/ServiceNow/CICDBuildRunners/Run_ESR_Application_Build_Test.java
Please see commented-out imports

2023-06-13 21:55 UTC, georgeb79 commented on src/test/java/ServiceNow/CICDBuildRunners/Run_MyCICDTestApp_Application_Build_Test.java
Please see commented-out imports

2023-06-13 21:55 UTC, georgeb79 commented on src/test/java/ServiceNow/CHARMS/Steps/myRASScreenerSubmissions.java
Please see commented-out lines 104, 1570-1574, 1870-1872, 2350-2356, and 2642-2652

2023-06-13 21:55 UTC, georgeb79 commented on src/test/java/ServiceNow/CcrHelpDesk/Steps/HookSteps.java
Please see commented-out imports

2023-06-13 21:55 UTC, georgeb79 commented on src/test/java/ServiceNow/ITPG/Pages/BasePage.java
Please see commented-out  lines 217-225, 230, and 233

2023-06-13 21:55 UTC, georgeb79 commented on src/test/java/ServiceNow/ITPG/Steps/HookSteps.java
Please see commented-out imports

2023-06-13 21:55 UTC, georgeb79 commented on src/test/java/ServiceNow/NERD/Steps/HooksSteps.java
Please see commented-out imports

2023-06-13 21:55 UTC, georgeb79 commented on src/test/java/ServiceNow/RCMDB/Steps/HookSteps.java
Please see commented-out imports

2023-06-13 21:55 UTC, georgeb79 commented on src/test/java/ServiceNow/SampleTest/Steps/HooksSteps.java
Please see commented-out imports

2023-06-13 21:55 UTC, georgeb79 commented on src/test/java/ServiceNow/ServiceNowRunners/RunAppTrackerProgressionTest.java
Please see commented-out imports

2023-06-13 21:55 UTC, georgeb79 commented on src/test/java/ServiceNow/ServiceNowRunners/RunAtoProgressionTest.java
Please see commented-out imports and line 21

2023-06-13 21:55 UTC, georgeb79 commented on src/test/java/ServiceNow/ServiceNowRunners/RunAtoRegressionTest.java
Please see commented-out imports

2023-06-13 21:55 UTC, georgeb79 commented on src/test/java/ServiceNow/ServiceNowRunners/RunCADSRServicePortalTest.java
Please see commented-out imports and line 21

2023-06-13 21:55 UTC, georgeb79 commented on src/test/java/ServiceNow/ServiceNowRunners/RunCCRHelpDesk.java
Please see commented-out imports and line 21

2023-06-13 21:55 UTC, georgeb79 commented on src/test/java/ServiceNow/ServiceNowRunners/RunCHARMSProgressionTest.java
Please see commented-out imports

2023-06-13 21:55 UTC, georgeb79 commented on src/test/java/ServiceNow/ServiceNowRunners/RunCHARMSRegressionTest.java
Please see commented-out imports

2023-06-13 21:55 UTC, georgeb79 commented on src/test/java/ServiceNow/ServiceNowRunners/RunCHARMSSmokeTest.java
Please see commented-out imports

2023-06-13 21:55 UTC, georgeb79 commented on src/test/java/ServiceNow/ServiceNowRunners/RunCHARMSTestAccountResetTest.java
Please see commented-out imports

2023-06-13 21:55 UTC, georgeb79 commented on src/test/java/ServiceNow/ServiceNowRunners/RunCOVIDCodeProgressionTest.java
Please see commented-out imports

2023-06-13 21:55 UTC, georgeb79 commented on src/test/java/ServiceNow/ServiceNowRunners/RunCOVIDDashProgressionTest.java
Please see commented-out imports

2023-06-13 21:55 UTC, georgeb79 commented on src/test/java/ServiceNow/ServiceNowRunners/RunCOVIDDashRegressionTest.java
Please see commented-out imports

2023-06-13 21:55 UTC, georgeb79 commented on src/test/java/ServiceNow/ServiceNowRunners/RunCOVIDDashSmokeTest.java
Please see commented-out imports

2023-06-13 21:55 UTC, georgeb79 commented on src/test/java/ServiceNow/ServiceNowRunners/RunITPGPSmokeTest.java
Please see commented-out imports and line 21

2023-06-13 21:55 UTC, georgeb79 commented on src/test/java/ServiceNow/ServiceNowRunners/RunITPGProgerssionTest.java
Please see commented-out imports and line 21

2023-06-13 21:55 UTC, georgeb79 commented on src/test/java/ServiceNow/ServiceNowRunners/RunITPGProgressionTest.java
Please see commented-out imports and line 21

2023-06-13 21:55 UTC, georgeb79 commented on src/test/java/ServiceNow/ServiceNowRunners/RunNERDProgressionTest.java
Please see commented-out imports

2023-06-13 21:55 UTC, georgeb79 commented on src/test/java/ServiceNow/ServiceNowRunners/RunNERDRegressionTest.java
Please see commented-out imports

2023-06-13 21:55 UTC, georgeb79 commented on src/test/java/ServiceNow/ServiceNowRunners/RunNERDSmokeTest.java
Please see commented-out imports

2023-06-13 21:55 UTC, georgeb79 commented on src/test/java/ServiceNow/ServiceNowRunners/RunRCMDBTestCases.java
Please see commented-out imports

2023-06-13 21:55 UTC, georgeb79 commented on src/test/java/ServiceNow/ServiceNowRunners/RunSEERProgressionTest.java
Please see commented-out imports

2023-06-13 21:55 UTC, georgeb79 commented on src/test/java/ServiceNow/ServiceNowRunners/RunSEERRegressionTest.java
Please see commented-out imports

2023-06-13 21:55 UTC, georgeb79 commented on src/test/java/ServiceNow/ServiceNowRunners/RunSEERSmokeTest.java
Please see commented-out imports

2023-06-13 21:55 UTC, georgeb79 commented on src/test/java/ServiceNow/ServiceNowRunners/RunSampleRunnerTest.java
Please see commented-out imports

2023-06-13 22:03 UTC, matakevin commented on src/main/java/com/nci/automation/web/CommonUtils.java
intelliJ adds the "//" to format correctly.  Disregard aforementioned comment

2023-06-14 18:04 UTC, georgeb79 approved these changes

2023-06-14 22:37 UTC, sarwarahmed1 approved these changes

2023-06-16 21:36 UTC, iamdez99 approved these changes
Reviewed and approved

2023-06-16 21:38 UTC, merged