Juarezds
CBIIT/CBIIT-Test-Automation pull request #144
Opened 2023-06-26 19:49 UTC by iamdez99

2023-06-26 20:18 UTC, hamidnesar requested changes

2023-06-26 20:18 UTC, hamidnesar commented on .gitignore
> +src/test/java/ServiceNow/BrownBag
Are we merging the BrownBag to master? I thought that was just for demo

2023-06-26 20:23 UTC, hamidnesar approved these changes

2023-06-27 13:22 UTC, sarwarahmed1 approved these changes

2023-06-27 17:01 UTC, merged