CCR - Submit an Application
CBIIT/CBIIT-Test-Automation pull request #156
Opened 2023-07-20 16:33 UTC by alenaminsk

2023-07-20 20:54 UTC, sarwarahmed1 approved these changes

2023-07-21 15:11 UTC, zamant2 commented on src/test/java/CustomBusiness/BusinessAppRunners/RunCCRProgressionTest.java
> +        tags = "@fillApplication",
Please change the tag to Progression

2023-07-21 15:38 UTC, alenaminsk commented on src/test/java/CustomBusiness/BusinessAppRunners/RunCCRProgressionTest.java
> +        tags = "@fillApplication",
Thank you, adjusted

2023-07-21 15:45 UTC, zamant2 approved these changes

2023-07-24 20:03 UTC, georgeb79 approved these changes

2023-07-25 15:26 UTC, iamdez99 requested changes

2023-07-25 15:26 UTC, iamdez99 commented on src/test/java/CustomBusiness/CCR/Pages/CCRApplicationPage.java
The last element is missing a comment

2023-07-25 15:26 UTC, iamdez99 commented on src/test/java/CustomBusiness/CCR/StepsImplementation/CCRLogInStepsImplementation.java
Use the sleep method from the MiscUtils class so that you dont "throw" the exception. Remove uneccessary sleeps

2023-07-25 16:02 UTC, alenaminsk commented on src/test/java/CustomBusiness/CCR/Features/LandingPage.feature
Added CAMS-9

> Please add user story IDs to scenarios

2023-07-25 16:02 UTC, alenaminsk commented on src/test/java/CustomBusiness/CCR/Pages/CCRApplicationPage.java
Added comment to the last element

2023-07-25 16:12 UTC, alenaminsk commented on src/test/java/CustomBusiness/CCR/StepsImplementation/CCRLogInStepsImplementation.java
Removed unneccessary sleeps

2023-07-26 16:05 UTC, iamdez99 requested changes

2023-07-26 16:09 UTC, iamdez99 approved these changes
Reviewed and approved - juarezds

2023-07-26 16:09 UTC, merged