Jains18
CBIIT/CBIIT-Test-Automation pull request #174
Opened 2023-08-25 13:24 UTC by sonika-nih

Please review the Fanconi screener submission and assertion code.

2023-08-25 14:54 UTC, alenaminsk commented on src/test/java/ServiceNow/CHARMS/alljava/ParticipantPersonalInformation.java
Please remove extra lines
14,15, 27,28,33,34,39,40,45,46,51,52,57,58,63,64,69,70,75,76,81,82,87,88,93,94,99,100,111

2023-08-25 15:02 UTC, alenaminsk commented on src/test/java/ServiceNow/CHARMS/alljava/ParticipantDetail.java
Please remove extra lines 4.5.6

2023-08-25 16:16 UTC, matakevin requested changes
Please look at the spaces that need to be deleted in the classes your adding to master.  Please look at the Page Initializer class and add your new imports and classes but don't remove the more dynamic imports

2023-08-25 16:16 UTC, matakevin commented on src/test/java/ServiceNow/CHARMS/Utils/FHQUtil.java
remove empty lines such as line 37, 41

2023-08-25 16:16 UTC, matakevin commented on src/test/java/ServiceNow/CHARMS/alljava/ParticipantDemographic.java
remove lines such as 50-53, and 39

2023-08-25 16:16 UTC, matakevin commented on src/test/java/ServiceNow/CHARMS/alljava/ParticipantDetail.java
Is this class necessary?  If so, please remove empty spaces and commented lines

2023-08-25 16:16 UTC, matakevin commented on src/test/java/ServiceNow/ServiceNowRunners/RunCHARMSTestAccountResetForFanconi.java
remove spaces on the imports and the commented out imports on lines 7 and 8.

2023-08-25 16:16 UTC, matakevin commented on src/test/java/appsCommon/PageInitializer.java
please incorporate the lines from 3-18 into your pageInitailizer class.  These were added to clean up code and not have 11 CEDCD pages and step implemenation imports and the same is true for the other projects that were deleted from lines 3-18 and 20-47.  We'll eventually have to clean up the other classes also.

2023-08-25 16:36 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/alljava/ParticipantPersonalInformation.java
Removed the extra spaces

2023-08-25 16:56 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/alljava/ParticipantDetail.java
Removed Extra Lines

2023-08-25 18:11 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/Constants/FanconiEligibilityQuestionnaireConstants.java
Removed the changes

2023-08-25 18:13 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/Constants/RAS_Screener_Constants.java
This is not my code

2023-08-25 18:38 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/Constants/StudiesConstants.java
EXtra spaces removed

2023-08-25 18:42 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/Features/FanconiStudy/FanconiEligibilityQuestionnaire.feature
The tags are commented out because I can run one scenario at a time. Otherwise, all will run for the @Regression tab

2023-08-25 18:42 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/Features/RasopathyStudy/RASSurvey.feature
This is not my code

2023-08-25 19:18 UTC, hamidnesar requested changes

2023-08-25 19:18 UTC, hamidnesar commented on src/test/java/ServiceNow/CHARMS/StepsImplementation/FanconiEligibilityQuestionnaireStepsImpl.java
> +
I dont believe there is a need for space between the following lines and above.

2023-08-25 19:18 UTC, hamidnesar commented on src/test/java/ServiceNow/CHARMS/StepsImplementation/FanconiEligibilityQuestionnaireStepsImpl.java
> +
Please remove these lines

2023-08-25 19:18 UTC, hamidnesar commented on src/test/java/ServiceNow/CHARMS/StepsImplementation/FanconiEligibilityQuestionnaireStepsImpl.java
> +		// JavascriptUtils.scrollIntoView(fanconiScreenerNVPage.nVFScreenerBoneMarrowFailure);
Please remove the commented line

2023-08-25 19:18 UTC, hamidnesar commented on src/test/java/ServiceNow/CHARMS/StepsImplementation/FanconiEligibilityQuestionnaireStepsImpl.java
> +
extra line

2023-08-25 19:18 UTC, hamidnesar commented on src/test/java/ServiceNow/CHARMS/Utils/CharmsExcelUtils.java
> +
Please remove extra space

2023-08-25 19:18 UTC, hamidnesar commented on src/test/java/ServiceNow/CHARMS/Utils/CharmsExcelUtils.java
> +
Please remove the extra lines between the comments and your code through the page

2023-08-25 19:18 UTC, hamidnesar commented on src/test/java/ServiceNow/CHARMS/Utils/CharmsExcelUtils.java
> +
Extra space

2023-08-25 19:18 UTC, hamidnesar commented on src/test/java/ServiceNow/CHARMS/Utils/CharmsExcelUtils.java
> +
Extra space

2023-08-25 19:18 UTC, hamidnesar commented on src/test/java/ServiceNow/CHARMS/Utils/CharmsExcelUtils.java
> +
Extra space

2023-08-25 19:18 UTC, hamidnesar commented on src/test/java/ServiceNow/CHARMS/Utils/CharmsUtil.java
> +
Please remove 7 and 16

2023-08-25 19:18 UTC, hamidnesar commented on src/test/java/ServiceNow/CHARMS/Utils/CharmsUtil.java
> +
Please remove such extra lines

2023-08-25 19:18 UTC, hamidnesar commented on src/test/java/ServiceNow/CHARMS/Utils/CharmsUtil.java
> +
please remove extra lines 301, 304, 306, 318,322, 324, 327, 336, 340 and following

2023-08-25 19:18 UTC, hamidnesar commented on src/test/java/ServiceNow/CHARMS/alljava/ParticipantDemographic.java
> +
Extra space

2023-08-25 19:18 UTC, hamidnesar commented on src/test/java/ServiceNow/CHARMS/alljava/ParticipantDemographic.java
> +
Extra space

2023-08-25 19:18 UTC, hamidnesar commented on src/test/java/ServiceNow/ServiceNowRunners/RunCHARMSTestAccountResetForFanconi.java
> +package ServiceNow.ServiceNowRunners;
Is this Runner class created for specific scenarios?

2023-08-25 19:18 UTC, hamidnesar commented on src/test/java/appsCommon/PageInitializer.java
Extra space

2023-08-25 19:18 UTC, hamidnesar commented on src/test/java/appsCommon/PageInitializer.java
> +	public static FanconiEligibilityQuestionnaireStepsImpl fanconiEligibilityQuestionnaireStepsImpl;
Indentations seems to be a bit off

2023-08-25 19:18 UTC, hamidnesar commented on src/test/java/appsCommon/PageInitializer.java
> +		fanconiEligibilityQuestionnaireStepsImpl = new FanconiEligibilityQuestionnaireStepsImpl();
Please indent these lines to the left

2023-08-25 19:18 UTC, hamidnesar commented on src/test/java/appsCommon/PageInitializer.java
> +
Extra space

2023-08-28 14:01 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/Pages/FanconiLoginPage.java
Done

2023-08-28 15:01 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/Pages/FanconiScreenerNVPage.java
Removed the extra lines

2023-08-28 15:01 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/Pages/FanconiEligibilityQuestionnairePage.java
Removed the extra lines

2023-08-28 15:01 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/NativeView/Pages/CHARMSParticipantDetailsPage.java
Removed the extra lines

2023-08-28 15:01 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/NativeView/Pages/CHARMSNativeViewPage.java
Removed the extra lines

2023-08-28 15:24 UTC, sonika-nih commented on src/test/java/ServiceNow/ServiceNowRunners/RunCHARMSTestAccountResetForFanconi.java
> +package ServiceNow.ServiceNowRunners;
This runner class is created to specifically run  all the Fanconi features

2023-08-28 15:59 UTC, sonika-nih commented on src/test/java/appsCommon/PageInitializer.java
If I understand correctly, you are asking to add the whole package as compared to the only classes we are using in the java code?

2023-08-28 18:15 UTC, alenaminsk approved these changes

2023-08-29 14:39 UTC, matakevin commented on src/test/java/ServiceNow/CHARMS/NativeView/Pages/CHARMSNativeViewPage.java
Lines 10 and 8 should also be removed but that can be saved for your next PR

2023-08-29 14:44 UTC, matakevin commented on src/test/java/ServiceNow/CHARMS/Steps/FanconiLoginSteps.java
Line 4 should still be deleted, save for next PR

2023-08-29 15:00 UTC, matakevin requested changes
I requested changes on some of the classes that have commented out code (not descriptive code but commented out sysout or javascript code), one of your runners class is missing a plugin that we added some time ago and the changes to the page initializer class for the classes we rolled into one import containing all classes in the "Pages.*", "Steps.*" or "StepImpl.*" classes.  There are still some classes that have empty spaces but I will overlook them until your next PR is created.

2023-08-29 16:45 UTC, sonika-nih commented on src/test/java/ServiceNow/ServiceNowRunners/RunCHARMSTestAccountResetForFanconi.java
> +		"pretty" }, features = "src/test/java/ServiceNow/CHARMS/Features/FanconiStudy", glue = "ServiceNow.CHARMS.Steps", tags = "@TestAccountReset", dryRun = false, monochrome = true, strict = true
Added the extentCucumberAdapter plugin after the "pretty" plugin

2023-08-29 16:47 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/Features/RasopathyStudy/RASSurvey.feature
> +        # And clicks Unsure/Unknown option for During her pregnancy with you, did your mother have any prenatal tests to identify fetal birth defects or fetal medical problems? page - myRAS Survey
This code needs to be cleaned with the help of Diego

2023-08-29 16:48 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/Features/RasopathyStudy/RASSurvey.feature
> +
This is the old code that needs to be cleaned with the help of Diego

2023-08-29 16:48 UTC, sonika-nih commented on src/test/java/appsCommon/PageInitializer.java
> +	public static FanconiEligibilityQuestionnaireStepsImpl fanconiEligibilityQuestionnaireStepsImpl;
Done

2023-08-29 16:52 UTC, sonika-nih commented on src/test/java/appsCommon/PageInitializer.java
> +
Done

2023-08-29 17:07 UTC, sonika-nih commented on src/test/java/ServiceNow/ServiceNowRunners/RunCHARMSTestAccountResetForFanconi.java
> +		"pretty" }, features = "src/test/java/ServiceNow/CHARMS/Features/FanconiStudy", glue = "ServiceNow.CHARMS.Steps", tags = "@TestAccountReset", dryRun = false, monochrome = true, strict = true
Done

2023-08-31 13:56 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/Utils/CharmsExcelUtils.java
REmoved extra lines

2023-08-31 14:01 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/NativeView/Pages/CHARMSNativeViewPage.java
I removed some extra lines but then realized that it was the page that needed to be cleaned because of old code.

2023-08-31 14:19 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/Steps/FanconiLoginSteps.java
Removed extra lines from FanconiLoginSteps file

2023-08-31 14:22 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/StepsImplementation/FanconiEligibilityQuestionnaireStepsImpl.java
Removed extra lines and Corrected the indentation FanconiEligibilityQuestionnaireStepsImpl file

2023-08-31 14:23 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/Utils/FHQUtil.java
I need to rewrite this code. will do the cleanup later

2023-08-31 14:27 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/alljava/ParticipantDemographic.java
Deleted the ParticipantDemographic Class. Not needed

2023-08-31 14:29 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/alljava/ParticipantDetail.java
Removed empty spaces and commented lines.

2023-08-31 14:33 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/Features/FanconiStudy/FanconiEligibilityQuestionnaire.feature
Done

2023-08-31 14:35 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/Constants/StudiesConstants.java
> +
Done

2023-08-31 14:37 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/NativeView/Pages/CHARMSNativeViewPage.java
> +	// ------- Native View Survey Participant mothers birth complications
This old code needs to be cleaned.

2023-08-31 14:38 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/NativeView/Pages/CHARMSParticipantDetailsPage.java
> +
This jave file is removed and not needed in the code.

2023-08-31 14:39 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/NativeView/Pages/CHARMSParticipantDetailsPage.java
> +	  //(//a[normalize-space()='Fanconi-3 tester-3'])[1]
Done. Removed commented lines

2023-08-31 14:40 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/NativeView/Pages/CHARMSParticipantDetailsPage.java
> +
removed double spaced empty lines throughout the class

2023-08-31 14:40 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/NativeView/Pages/CHARMSParticipantDetailsPage.java
> +
Removed Extra space

2023-08-31 14:41 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/Pages/FanconiEligibilityQuestionnairePage.java
> +	 */
Done. Removed commented lines

2023-08-31 14:41 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/Pages/FanconiEligibilityQuestionnairePage.java
> +
removed extra spaces

2023-08-31 14:42 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/Pages/FanconiEligibilityQuestionnairePage.java
> +
Done

2023-08-31 14:42 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/NativeView/Pages/CHARMSParticipantDetailsPage.java
> +
Done

2023-08-31 14:42 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/Constants/RAS_Screener_Constants.java
> +//    THIS IS A CONFLICT
This old code needs to be cleaned.

2023-08-31 14:43 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/Pages/FanconiLoginPage.java
> +
Done

2023-08-31 14:48 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/Pages/FanconiScreenerNVPage.java
> +
Corrected Indentation and removed extra lines

2023-08-31 14:49 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/Pages/FanconiScreenerNVPage.java
> +
Removed line 743

2023-08-31 14:50 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/Steps/FanconiEligibilityQuestionnaireSteps.java
> +
Done. Removed all the extra spaces

2023-08-31 14:53 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/Steps/FanconiLoginSteps.java
> +
Done

2023-08-31 14:53 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/StepsImplementation/FanconiEligibilityQuestionnaireStepsImpl.java
> +		// CucumberLogUtils.takeScreenShot(HooksSteps.scenario);
Done

2023-08-31 14:53 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/StepsImplementation/FanconiEligibilityQuestionnaireStepsImpl.java
> +
Done

2023-08-31 14:54 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/StepsImplementation/FanconiEligibilityQuestionnaireStepsImpl.java
> +
Done

2023-08-31 14:54 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/StepsImplementation/FanconiEligibilityQuestionnaireStepsImpl.java
> +				CharmsUtil.sendKeysToElement(fanconiEligibilityQuestionnairePage.otherStudyNameList.get(i),
Corrected Indentation and removed extra lines

2023-08-31 14:55 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/StepsImplementation/FanconiEligibilityQuestionnaireStepsImpl.java
> +			// When were you diagnosed with myelodysplastic syndrome (MDS)? Please enter the
Done

2023-08-31 14:56 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/StepsImplementation/FanconiEligibilityQuestionnaireStepsImpl.java
> +		// rowNumForAssertion);
I commented on this in case I need to run all the scenarios in one method. I don't need to fetch this for every scenario. But need this one running Individual scenrios

2023-08-31 14:57 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/StepsImplementation/FanconiEligibilityQuestionnaireStepsImpl.java
> +
Removed

2023-08-31 14:57 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/StepsImplementation/FanconiEligibilityQuestionnaireStepsImpl.java
> +
Removed

2023-08-31 14:57 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/StepsImplementation/FanconiEligibilityQuestionnaireStepsImpl.java
> +		// JavascriptUtils.scrollIntoView(fanconiScreenerNVPage.nVFScreenerBoneMarrowFailure);
Removed

2023-08-31 14:57 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/StepsImplementation/FanconiEligibilityQuestionnaireStepsImpl.java
> +
Removed

2023-08-31 14:57 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/Utils/CharmsExcelUtils.java
> +
Removed

2023-08-31 14:58 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/Utils/CharmsExcelUtils.java
> +
Removed

2023-08-31 14:58 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/Utils/CharmsExcelUtils.java
> +
Removed

2023-08-31 14:58 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/Utils/CharmsExcelUtils.java
> +
Removed

2023-08-31 14:58 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/Utils/CharmsUtil.java
> +
Removed

2023-08-31 15:04 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/Utils/CharmsUtil.java
> +
Done

2023-08-31 15:04 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/Utils/CharmsUtil.java
> +
Done

2023-08-31 15:04 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/alljava/ParticipantDemographic.java
> +
Removed the java class

2023-08-31 15:06 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/alljava/ParticipantDemographic.java
> +
I removed the Java class. Not needed

2023-08-31 15:06 UTC, sonika-nih commented on src/test/java/appsCommon/PageInitializer.java
Done

2023-08-31 15:07 UTC, sonika-nih commented on src/test/java/appsCommon/PageInitializer.java
> +		fanconiEligibilityQuestionnaireStepsImpl = new FanconiEligibilityQuestionnaireStepsImpl();
Done

2023-08-31 16:31 UTC, merged