SCSS - Create a vacancy as Stadtman Vacancy Manager
CBIIT/CBIIT-Test-Automation pull request #175
Opened 2023-08-31 17:18 UTC by alenaminsk

2023-09-01 17:35 UTC, matakevin requested changes
Just delete that one line and should be good to go.  Thank you!

2023-09-01 17:35 UTC, matakevin commented on src/test/java/ServiceNow/SCSS/Pages/OWMVacancyPage.java
line 71 should be deleted

2023-09-01 17:48 UTC, alenaminsk commented on src/test/java/ServiceNow/SCSS/Pages/OWMVacancyPage.java
Deleted

2023-09-01 17:49 UTC, matakevin approved these changes
LGTM

2023-09-05 13:29 UTC, georgeb79 approved these changes

2023-09-05 13:30 UTC, merged