Pull request to merge my FHQ code to Master
CBIIT/CBIIT-Test-Automation pull request #203
Opened 2024-02-28 03:15 UTC by sonika-nih

Pull request to merge my FHQ code to Master

2024-03-12 19:52 UTC, matakevin requested changes
Hey @sonika-nih can you look at my comments on some of these classes.  I'm not too familiar with Charms anymore and the whole Shadow Dom, etc... but please let me know if you have any questions regarding the comments

2024-03-12 19:52 UTC, matakevin commented on src/test/java/ServiceNow/CHARMS/Features/FanconiStudy/FanconiEligibilityQuestionnaire.feature
> +  #@jains @FanconiSubmission @Regression
Is there any reason your tags are commented out?  We could just remove or change the tag to run/not run these tests

2024-03-12 19:52 UTC, matakevin commented on src/test/java/ServiceNow/CHARMS/Features/FanconiStudy/FanconiEligibilityQuestionnaire.feature
> +#And logs in Fanconi page via Okta with username "stage-2@yopmail.com" and password "Blue2585#"
Are these commented out lines needed?

2024-03-12 19:52 UTC, matakevin commented on src/test/java/ServiceNow/CHARMS/Features/FanconiStudy/FanconiEligibilityQuestionnaire.feature
> +    #And logs in Fanconi page via Okta with username "charmsparticipant2@yopmail.com" and password "Charms123"
Are these commented out lines needed?

2024-03-12 19:52 UTC, matakevin commented on src/test/java/ServiceNow/CHARMS/StepsImplementation/FHQSubmissionStepsImpl.java
> +
We can remove these blank lines at a later PR

2024-03-12 19:52 UTC, matakevin commented on src/test/java/ServiceNow/ServiceNowRunners/RunCHARMSFHQRegressionTest.java
> +tags = "@TestRegression",
This should be the @Regression tag if it is the Regression Runners.  You'll need to change some tags on your feature files for full regression

2024-03-12 19:52 UTC, matakevin commented on src/test/java/ServiceNow/ServiceNowRunners/RunCHARMSFHQRegressionTest.java
>  monochrome = true,
If you have the latest code from master, you'd have to remove monochrome and strict tags.  We'd also have to remove @RunWith and change the imports to TestNG classes.

2024-03-12 19:55 UTC, hamidnesar requested changes

2024-03-12 19:55 UTC, hamidnesar commented on src/test/java/ServiceNow/CHARMS/Features/FHQ/FHQSubmission.feature
> +  #@FHQSubmissionInPortal @TestRegression
Please remove the commented Tag or remove the comment. 
Please change TestRegression to Regression tag

2024-03-12 19:55 UTC, hamidnesar commented on src/test/java/ServiceNow/CHARMS/Features/FHQ/FHQSubmission.feature
> +      | charmsras2@yahoo.com | RASTest2023$$ | FHQScenario1 | Participant |
It is not recommended to store passwords on the feature file

2024-03-12 19:55 UTC, hamidnesar commented on src/test/java/ServiceNow/CHARMS/Features/FHQ/FHQSubmission.feature
> +  #@FHQSubmissionInPortal @TestRegression
Please either remove the commented tag or remove #. 
Modify TestRegression to Regression tag

2024-03-12 19:55 UTC, hamidnesar commented on src/test/java/ServiceNow/CHARMS/Features/FHQ/FHQSubmission.feature
> +  @FHQSubmissionInPortal
Missing Regression tag

2024-03-12 19:55 UTC, hamidnesar commented on src/test/java/ServiceNow/CHARMS/Features/FHQ/FHQSubmission.feature
> +  #@FHQAssertionInNV @TestRegression
Please either remove the commented tag or remove #.
Modify TestRegression to Regression tag

2024-03-12 19:55 UTC, hamidnesar commented on src/test/java/ServiceNow/CHARMS/Features/FanconiStudy/FanconiEligibilityQuestionnaire.feature
> +    #And logs in Fanconi page via Okta with username "charmsparticipant2@yopmail.com" and password "Charms123"
Please remove the commented lines if no longer needed

2024-03-12 19:55 UTC, hamidnesar commented on src/test/java/ServiceNow/CHARMS/Steps/FanconiLoginSteps.java
> +
Please remove the empty line

2024-03-12 19:55 UTC, hamidnesar commented on src/test/java/ServiceNow/CHARMS/Steps/FanconiLoginSteps.java
> +
Please remove the empty line

2024-03-12 19:55 UTC, hamidnesar commented on src/test/java/ServiceNow/CHARMS/Utils/CharmsUtil.java
> +
Please remove the empty line

2024-03-12 19:55 UTC, hamidnesar commented on src/test/java/ServiceNow/CHARMS/Utils/CharmsUtil.java
> +
Please remove the empty line

2024-03-12 19:55 UTC, hamidnesar commented on src/test/java/ServiceNow/CHARMS/Utils/CharmsUtil.java
> +//		softAssert.assertEquals(actualValueWithSpace, expectedValue, "Assertion Failed for" + messsage + "-->");
Please remove the commented line

2024-03-12 19:55 UTC, hamidnesar commented on src/test/java/ServiceNow/ServiceNowRunners/RunCHARMSRegressionTest.java
>  		dryRun = false,
Please use TestNG for your Runner classes

2024-03-12 19:55 UTC, hamidnesar commented on src/test/java/appsCommon/Pages/NativeView_SideDoor_Dashboard_Page.java
> +
Please remove the empty line

2024-03-12 19:55 UTC, hamidnesar commented on src/test/java/appsCommon/Pages/NativeView_SideDoor_Dashboard_Page.java
> +
Please remove the empty line

2024-03-12 19:55 UTC, hamidnesar commented on src/test/java/appsCommon/Utils/ServiceNow_Common_Methods.java
> +
Please remove the empty line

2024-03-12 19:55 UTC, hamidnesar commented on src/test/java/appsCommon/Utils/ServiceNow_Common_Methods.java
> +
Please remove the empty line

2024-03-13 20:37 UTC, iamdez99 requested changes
Please review comments and review all files

2024-03-13 20:37 UTC, iamdez99 commented on src/test/java/ServiceNow/CHARMS/Constants/CHARMS_Data_File_Path_Constants.java
Please delete empty line 12

2024-03-13 20:37 UTC, iamdez99 commented on src/test/java/ServiceNow/CHARMS/Features/FHQ/FHQSubmission.feature
Do not comment out tags, please delete #

2024-03-13 20:37 UTC, iamdez99 commented on src/test/java/ServiceNow/CHARMS/Features/FanconiStudy/FanconiEligibilityQuestionnaire.feature
Please do not comment out tags. Also, if scenario is complete, please tag @Regression, if you will organize your scenarios with different tags, please set up a time to discuss

2024-03-13 20:37 UTC, iamdez99 commented on src/test/java/ServiceNow/CHARMS/Pages/FHQSubmissionPage.java
Please delete line 7

2024-03-13 20:37 UTC, iamdez99 commented on src/test/java/ServiceNow/CHARMS/Pages/OKTAloginPage.java
Please delete line 6

2024-03-13 20:37 UTC, iamdez99 commented on src/test/java/ServiceNow/CHARMS/Pages/OKTAloginPage.java
Also lines 39,44,45

2024-03-13 20:37 UTC, iamdez99 commented on src/test/java/ServiceNow/CHARMS/ScenariosData/FHQ_TestDataManager.java
Please review file and delete empty lines

2024-03-13 20:37 UTC, iamdez99 commented on src/test/java/ServiceNow/CHARMS/Steps/FHQSubmissionSteps.java
Please delete empty lines

2024-03-13 20:37 UTC, iamdez99 commented on src/test/java/ServiceNow/CHARMS/Steps/FanconiLoginSteps.java
Please delete empty lines and why are you using import com.google.gson.JsonIOException;
import com.google.gson.JsonSyntaxException;?

2024-03-13 20:37 UTC, iamdez99 commented on src/test/java/ServiceNow/CHARMS/StepsImplementation/FHQSubmissionStepsImpl.java
Please delete empty lines

2024-03-13 20:37 UTC, iamdez99 commented on src/test/java/ServiceNow/CHARMS/Utils/CharmsUtil.java
Empty lines again

2024-03-13 20:37 UTC, iamdez99 commented on src/test/java/ServiceNow/ServiceNowRunners/RunCHARMSFHQRegressionTest.java
Please set up a time to discuss tags for CHARMS

2024-03-13 20:37 UTC, iamdez99 commented on src/test/java/ServiceNow/ServiceNowRunners/RunCHARMSFHQRegressionTest.java
Please update ALL runners classes to run with TestNG - contact me for help if you do not know how

2024-03-14 03:36 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/Features/FanconiStudy/FanconiEligibilityQuestionnaire.feature
> +#And logs in Fanconi page via Okta with username "stage-2@yopmail.com" and password "Blue2585#"
Removed the Commented LInes.

2024-03-14 03:36 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/Features/FanconiStudy/FanconiEligibilityQuestionnaire.feature
> +    #And logs in Fanconi page via Okta with username "charmsparticipant2@yopmail.com" and password "Charms123"
Removed the Commented LInes.

2024-03-14 03:48 UTC, sonika-nih commented on src/test/java/appsCommon/Utils/ServiceNow_Common_Methods.java
> +
Done

2024-03-14 13:42 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/Features/FHQ/FHQSubmission.feature
Removed #

2024-03-14 13:54 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/Pages/OKTAloginPage.java
Done

2024-03-14 13:54 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/Pages/FHQSubmissionPage.java
Done

2024-03-14 13:55 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/Features/FanconiStudy/FanconiEligibilityQuestionnaire.feature
Removed commented tags

2024-03-14 16:59 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/Features/FanconiStudy/FanconiEligibilityQuestionnaire.feature
> +  #@jains @FanconiSubmission @Regression
Commented tags removed

2024-03-14 17:00 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/StepsImplementation/FHQSubmissionStepsImpl.java
> +
Removed blank lines

2024-03-14 23:28 UTC, sonika-nih commented on src/test/java/ServiceNow/ServiceNowRunners/RunCHARMSFHQRegressionTest.java
>  monochrome = true,
Done for all the Runner classes

2024-03-15 20:07 UTC, matakevin requested changes
Check the 2 classes with reviews being asked for.  Thank you!

2024-03-15 20:07 UTC, matakevin commented on src/test/java/ServiceNow/CHARMS/Steps/FanconiLoginSteps.java
Why are you throwing 4 exceptions on line 19?  This step is just to navigate to the Fanconi login page, do you need all of these?  I also think that we're handling the MiscUtils.Sleep exception in the method

2024-03-15 20:07 UTC, matakevin commented on src/test/java/ServiceNow/ServiceNowRunners/RunSampleRunnerTest.java
> +        //, strict = true
This line isn't needed seeing as we aren't using the strict tag

2024-03-15 21:36 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/Steps/FanconiLoginSteps.java
Removed com.google.gson.JsonIOException;
import com.google.gson.JsonSyntaxException
Also removed extra lines

2024-03-15 21:38 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/Steps/FanconiLoginSteps.java
Removed all four Exceptions

2024-03-20 12:43 UTC, hamidnesar requested changes
Hi Sonika, I left a few comments on some files if you could please address them. Thank you!

2024-03-20 12:43 UTC, hamidnesar commented on src/test/java/AnalysisTools/MCAExplorer/Features/MCAExplorer.feature
> +  @TC3 @satya  @Smoke @Regression @NCIATWP-6676 @NCIATWP-6797
Please remove @smoke tag from all scenarios on this file

2024-03-20 12:43 UTC, hamidnesar commented on src/test/java/ServiceNow/CHARMS/Features/FHQ/FHQChildRecordProducer.feature
>      And click the new Child added and verify the completed record producer data
All scenarios are missing @Regression tag

2024-03-20 12:43 UTC, hamidnesar commented on src/test/java/ServiceNow/CHARMS/Features/FanconiStudy/FanconiEligibilityQuestionnaire.feature
>    @jains @FanconiSubmission
Missing @Regression tag across almost all scenarios

2024-03-20 12:43 UTC, hamidnesar commented on src/test/java/ServiceNow/ServiceNowRunners/RunCHARMSTestAccountResetTest.java
>  		glue = "ServiceNow.CHARMS.Steps",
This Runner needs to be updated with TestNG

2024-03-20 12:43 UTC, hamidnesar commented on src/test/java/ServiceNow/ServiceNowRunners/RunGDCProgressionTest.java
Please remove empty line

2024-03-20 14:36 UTC, sonika-nih commented on src/test/java/AnalysisTools/MCAExplorer/Features/MCAExplorer.feature
> +  @TC3 @satya  @Smoke @Regression @NCIATWP-6676 @NCIATWP-6797
This is not my code so will not be able to change it

2024-03-20 14:36 UTC, sonika-nih commented on src/test/java/AnalysisTools/AnalysisToolsRunners/RunJPSurvProgressionTest.java
>  @CucumberOptions(plugin= {"com.aventstack.extentreports.cucumber.adapter.ExtentCucumberAdapter:"}
This is not my code so will not be able to change it

2024-03-20 14:39 UTC, sonika-nih commented on src/test/java/ServiceNow/ServiceNowRunners/RunGDCProgressionTest.java
done

2024-03-20 15:07 UTC, sonika-nih commented on src/test/java/AnalysisTools/MCAExplorer/Features/MCAExplorer.feature
> +  @TC3 @satya  @Smoke @Regression @NCIATWP-6676 @NCIATWP-6797
I removed the @smoke tags even though this is not my code.

2024-03-20 15:21 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/Features/FHQ/FHQChildRecordProducer.feature
>      And click the new Child added and verify the completed record producer data
Done

2024-03-20 15:25 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/Features/FHQ/FHQSubmission.feature
> +  #@FHQSubmissionInPortal @TestRegression
Done

2024-03-20 15:26 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/Features/FHQ/FHQSubmission.feature
> +      | charmsras2@yahoo.com | RASTest2023$$ | FHQScenario1 | Participant |
I will add this new code later. Need to merge the code for other urgent requirements

2024-03-20 15:27 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/Features/FHQ/FHQSubmission.feature
> +  #@FHQAssertionInNV @TestRegression
Done

2024-03-20 15:27 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/Constants/CHARMS_Data_File_Path_Constants.java
Done

2024-03-20 15:29 UTC, sonika-nih commented on src/test/java/ServiceNow/ServiceNowRunners/RunCHARMSFHQRegressionTest.java
Added appropriate tags.

2024-03-20 15:29 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/Utils/CharmsUtil.java
Removed

2024-03-20 15:30 UTC, sonika-nih commented on src/test/java/ServiceNow/ServiceNowRunners/RunCHARMSFHQRegressionTest.java
Done

2024-03-20 15:30 UTC, sonika-nih commented on src/test/java/ServiceNow/ServiceNowRunners/RunSampleRunnerTest.java
> +        //, strict = true
Removed

2024-03-20 15:31 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/Features/FHQ/FHQSubmission.feature
> +  #@FHQSubmissionInPortal @TestRegression
Done

2024-03-20 15:31 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/Features/FHQ/FHQSubmission.feature
> +  @FHQSubmissionInPortal
Done

2024-03-20 15:31 UTC, sonika-nih commented on src/test/java/ServiceNow/ServiceNowRunners/RunCHARMSRegressionTest.java
>  		dryRun = false,
Done

2024-03-20 15:32 UTC, sonika-nih commented on src/test/java/appsCommon/Pages/NativeView_SideDoor_Dashboard_Page.java
> +
done

2024-03-20 15:32 UTC, sonika-nih commented on src/test/java/appsCommon/Pages/NativeView_SideDoor_Dashboard_Page.java
> +
done

2024-03-20 15:32 UTC, sonika-nih commented on src/test/java/appsCommon/Utils/ServiceNow_Common_Methods.java
> +
Done

2024-03-20 15:33 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/Features/FanconiStudy/FanconiEligibilityQuestionnaire.feature
>    @jains @FanconiSubmission
done

2024-03-20 16:05 UTC, hamidnesar approved these changes

2024-03-20 16:20 UTC, iamdez99 approved these changes
Reviewed and approved - juarezds

2024-03-20 16:20 UTC, merged