SSJ authenticated Applicant and unauthenticated Applicant scenarios
CBIIT/CBIIT-Test-Automation pull request #210
Opened 2024-03-22 20:27 UTC by alenaminsk

2024-03-22 20:47 UTC, puzikovam2 requested changes

2024-03-22 20:47 UTC, puzikovam2 commented on src/test/java/ServiceNow/PlatformBusinessApps/SSJ/selenium/Constants/SSJ_Constants.java
please remove the commented line, and format the code here

2024-03-22 20:47 UTC, puzikovam2 commented on src/test/java/ServiceNow/PlatformBusinessApps/SSJ/selenium/StepsImplementation/StadtmanVacancyStepsImplementation.java
please remove the commented lines

2024-03-22 20:47 UTC, puzikovam2 commented on src/test/java/ServiceNow/PlatformBusinessApps/SSJ/selenium/StepsImplementation/UnauthenticatedApplicantFlowStepsImplementation.java
remove extra line after package

2024-03-22 20:50 UTC, matakevin requested changes
Please review the requested changes, thank you

2024-03-22 20:50 UTC, matakevin commented on src/main/resources/conf/env/stage.xml
> +=======
is this line needed here?

2024-03-22 20:50 UTC, matakevin commented on src/main/resources/conf/env/test.xml
> +=======
solve conflicts

2024-03-22 20:50 UTC, matakevin commented on src/main/resources/conf/env/test.xml
> +>>>>>>> afc3adfc7c66c1a85a8020c85a96ee9a649b1c46
solve conflicts

2024-03-22 20:50 UTC, matakevin commented on src/test/java/GrantsApps/EM/selenium/Steps/HooksSteps.java
> +
package should be the first line of class, remove spaces in the imports

2024-03-22 20:50 UTC, matakevin commented on src/test/java/ServiceNow/PlatformBusinessApps/SSJ/selenium/Constants/OWMVacanciesConstants.java
Package name should be first line in code, line 9 shouldn't be commented

2024-03-22 20:50 UTC, matakevin commented on src/test/java/ServiceNow/PlatformBusinessApps/SSJ/selenium/Constants/StadtmanVacanciesConstants.java
First line should be package name

2024-03-22 20:50 UTC, matakevin commented on src/test/java/ServiceNow/PlatformBusinessApps/SSJ/selenium/Pages/ApplicantFlowPage.java
remove lines 580 and 581

2024-03-22 20:50 UTC, matakevin commented on src/test/java/ServiceNow/PlatformBusinessApps/SSJ/selenium/Pages/NativeViewSSJReportsPage.java
You can add a line to separate the Package and imports.  Not 100% necessary but to ensure consistency throughout the framework, please add.  Thank you!

2024-03-22 20:50 UTC, matakevin commented on src/test/java/ServiceNow/PlatformBusinessApps/SSJ/selenium/Pages/OWMVacancyPage.java
add line between package and import please

2024-03-22 20:50 UTC, matakevin commented on src/test/java/ServiceNow/PlatformBusinessApps/SSJ/selenium/Pages/StadtmanVacancyPage.java
Add space between package and imports

2024-03-22 20:50 UTC, matakevin commented on src/test/java/ServiceNow/PlatformBusinessApps/SSJ/selenium/Steps/ApplicantFlowSteps.java
remove empty lines at 34, 165, and 225

2024-03-22 20:50 UTC, matakevin commented on src/test/java/ServiceNow/PlatformBusinessApps/SSJ/selenium/Steps/OWMVacancySteps.java
Add a line to separate package and imports, thank you

2024-03-22 20:50 UTC, matakevin commented on src/test/java/ServiceNow/PlatformBusinessApps/SSJ/selenium/Steps/StadtmanVacancySteps.java
add space between package and imports

2024-03-22 20:50 UTC, matakevin commented on src/test/java/ServiceNow/PlatformBusinessApps/SSJ/selenium/Steps/UnauthenticatedApplicantSteps.java
remove empty lines 39, 49

2024-03-22 20:50 UTC, matakevin commented on src/test/java/ServiceNow/PlatformBusinessApps/SSJ/selenium/StepsImplementation/ApplicantFlowStepsImplementation.java
Package should be line 1.  Remove empty lines on line 9, 167

2024-03-22 20:50 UTC, matakevin commented on src/test/java/ServiceNow/PlatformBusinessApps/SSJ/selenium/StepsImplementation/OWMVacancyStepsImplementation.java
remove commented out code on lines 82, 83, 106, 220.
StepImpl classes should have a javadoc or comment before method name stating what the method is doing

2024-03-22 20:50 UTC, matakevin commented on src/test/java/ServiceNow/PlatformBusinessApps/SSJ/selenium/StepsImplementation/StadtmanVacancyStepsImplementation.java
remove commented out lines 25-29 and lines 51, 128, 129

2024-03-22 20:50 UTC, matakevin commented on src/test/java/ServiceNow/PlatformBusinessApps/SSJ/selenium/StepsImplementation/UnauthenticatedApplicantFlowStepsImplementation.java
remove line 3

2024-03-22 20:53 UTC, matakevin requested changes
reviewed some changes, added more requested changes

2024-03-22 20:53 UTC, matakevin commented on src/main/resources/conf/env/stage.xml
is line 215 needed?

2024-03-22 20:53 UTC, matakevin commented on src/main/resources/conf/env/test.xml
are 2 password tags needed on lines 773, 772?

2024-03-22 20:56 UTC, hamidnesar requested changes
Hi Alena, please see my comments and kindly address the requested changes. Thank you!

2024-03-22 20:56 UTC, hamidnesar commented on src/main/resources/conf/env/stage.xml
> +=======
Please remove this line

2024-03-22 20:56 UTC, hamidnesar commented on src/main/resources/conf/env/stage.xml
> +>>>>>>> afc3adfc7c66c1a85a8020c85a96ee9a649b1c46
Please remove this merge conflict text

2024-03-22 20:56 UTC, hamidnesar commented on src/main/resources/conf/env/stage.xml
> +		</login_url> <!-
Please add the missing (-) like <!-- to properly comment within an xml file. 
otherwise we will have an error

2024-03-22 20:56 UTC, hamidnesar commented on src/main/resources/conf/env/test.xml
> +                <password></password> <!-- add encrypted test pass -->
Please remove line 773 as it is duplicate of line 772

2024-03-22 20:56 UTC, hamidnesar commented on src/test/java/GrantsApps/EM/selenium/Steps/HooksSteps.java
> +package ServiceNow.SSJ.Steps;
Please revert the package name. This should be Package GrantsApps.EM.selenium.Steps;

2024-03-22 20:56 UTC, hamidnesar commented on src/test/java/GrantsApps/EM/selenium/Steps/HooksSteps.java
> +
Please remove line 1

2024-03-22 20:56 UTC, hamidnesar commented on src/test/java/ServiceNow/PlatformBusinessApps/SSJ/selenium/Constants/NativeViewSSJConstants.java
> +
Please remove line 1

2024-03-22 20:56 UTC, hamidnesar commented on src/test/java/ServiceNow/PlatformBusinessApps/SSJ/selenium/Constants/OWMVacanciesConstants.java
> +
Please remove line 1

2024-03-22 20:56 UTC, hamidnesar commented on src/test/java/ServiceNow/PlatformBusinessApps/SSJ/selenium/Constants/OWMVacanciesConstants.java
> +  //  public static final String TODAYS_DATE = CommonUtils.getDateAsString();
Please remove the commented line 9

2024-03-22 20:56 UTC, hamidnesar commented on src/test/java/ServiceNow/PlatformBusinessApps/SSJ/selenium/Constants/SSJ_Constants.java
> +
Please remove line 1

2024-03-22 20:56 UTC, hamidnesar commented on src/test/java/ServiceNow/PlatformBusinessApps/SSJ/selenium/Constants/StadtmanVacanciesConstants.java
> +
Please remove line 1

2024-03-22 20:56 UTC, hamidnesar commented on src/test/java/ServiceNow/PlatformBusinessApps/SSJ/selenium/Features/StadtmanVacanciesFlow.feature
> +
Please remove empty lines 27-44

2024-03-22 20:56 UTC, hamidnesar commented on src/test/java/ServiceNow/PlatformBusinessApps/SSJ/selenium/Pages/ApplicantFlowPage.java
> +
Please remove this empty line

2024-03-22 20:56 UTC, hamidnesar commented on src/test/java/ServiceNow/PlatformBusinessApps/SSJ/selenium/Pages/ApplicantFlowPage.java
> +
Please remove this empty line

2024-03-22 20:56 UTC, hamidnesar commented on src/test/java/ServiceNow/PlatformBusinessApps/SSJ/selenium/Pages/NativeViewSSJReportsPage.java
Please remove this empty line

2024-03-22 20:56 UTC, hamidnesar commented on src/test/java/ServiceNow/PlatformBusinessApps/SSJ/selenium/Steps/ApplicantFlowSteps.java
> +
Please remove this empty line

2024-03-22 20:56 UTC, hamidnesar commented on src/test/java/ServiceNow/PlatformBusinessApps/SSJ/selenium/Steps/ApplicantFlowSteps.java
> +
Please remove this empty line

2024-03-22 20:56 UTC, hamidnesar commented on src/test/java/ServiceNow/PlatformBusinessApps/SSJ/selenium/Steps/UnauthenticatedApplicantSteps.java
> +
Please remove this empty line

2024-03-22 20:56 UTC, hamidnesar commented on src/test/java/ServiceNow/PlatformBusinessApps/SSJ/selenium/Steps/UnauthenticatedApplicantSteps.java
> +
Please remove this empty line

2024-03-22 20:56 UTC, hamidnesar commented on src/test/java/ServiceNow/PlatformBusinessApps/SSJ/selenium/StepsImplementation/ApplicantFlowStepsImplementation.java
> +
Please remove this empty line

2024-03-22 20:56 UTC, hamidnesar commented on src/test/java/ServiceNow/PlatformBusinessApps/SSJ/selenium/StepsImplementation/ApplicantFlowStepsImplementation.java
> +
Please remove this empty line

2024-03-22 20:56 UTC, hamidnesar commented on src/test/java/ServiceNow/PlatformBusinessApps/SSJ/selenium/StepsImplementation/ApplicantFlowStepsImplementation.java
> +
Please remove empty lines 222-228

2024-03-22 20:56 UTC, hamidnesar commented on src/test/java/ServiceNow/PlatformBusinessApps/SSJ/selenium/StepsImplementation/OWMVacancyStepsImplementation.java
> +//        CommonUtils.sendKeys(owmVacancyPage.vacancyOpenDateTextBox, OWMVacanciesConstants.TODAYS_DATE);
Please remove commented lines 82, 83

2024-03-22 20:56 UTC, hamidnesar commented on src/test/java/ServiceNow/PlatformBusinessApps/SSJ/selenium/StepsImplementation/OWMVacancyStepsImplementation.java
> +
Please remove this empty line

2024-03-22 20:56 UTC, hamidnesar commented on src/test/java/ServiceNow/PlatformBusinessApps/SSJ/selenium/StepsImplementation/OWMVacancyStepsImplementation.java
> +       // CommonUtils.waitForClickability(owmVacancyPage.positionClassificationDropdownOptions(2));
Please remove this commented line

2024-03-22 20:56 UTC, hamidnesar commented on src/test/java/ServiceNow/PlatformBusinessApps/SSJ/selenium/StepsImplementation/OWMVacancyStepsImplementation.java
> +       // CommonUtils.assertEqualsWithMessage(yourVacancies, owmVacancyPage.tabOption(yourVacancies).getText(), "-- VERIFYING YOUR VACANCIES TAB --");
Please remove this commented line

2024-03-22 20:56 UTC, hamidnesar commented on src/test/java/ServiceNow/PlatformBusinessApps/SSJ/selenium/StepsImplementation/StadtmanVacancyStepsImplementation.java
> +//        JavascriptUtils.clickByJS(owmVacancyPage.calendarDatePicker.get(Integer.parseInt(openDate.substring(6,8))-1));
Please remove these commented lines 25-29

2024-03-22 20:56 UTC, hamidnesar commented on src/test/java/ServiceNow/PlatformBusinessApps/SSJ/selenium/StepsImplementation/StadtmanVacancyStepsImplementation.java
> +       // CommonUtils.waitForClickability(owmVacancyPage.positionClassificationDropdownOptions(1));
Please remove this commented line

2024-03-22 20:56 UTC, hamidnesar commented on src/test/java/ServiceNow/PlatformBusinessApps/SSJ/selenium/StepsImplementation/StadtmanVacancyStepsImplementation.java
> +     //   CommonUtils.assertEqualsWithMessage(owmVacancyPage.owmVacancyDynamicLocatorHomePage(StadtmanVacanciesConstants.VACANCY_TITLE).getText(),StadtmanVacanciesConstants.VACANCY_INSTITUTE, "-- VER
Please remove commented lines 128-129

2024-03-22 20:56 UTC, hamidnesar commented on src/test/java/ServiceNow/PlatformBusinessApps/SSJ/selenium/StepsImplementation/UnauthenticatedApplicantFlowStepsImplementation.java
> +
Please remove this empty line

2024-03-23 12:33 UTC, alenaminsk commented on src/main/resources/conf/env/stage.xml
> +		</login_url> <!-
Fixed

2024-03-23 12:33 UTC, alenaminsk commented on src/main/resources/conf/env/stage.xml
removed

2024-03-23 23:30 UTC, alenaminsk commented on src/test/java/ServiceNow/PlatformBusinessApps/SSJ/selenium/Constants/SSJ_Constants.java
> +
removed

2024-03-23 23:30 UTC, alenaminsk commented on src/test/java/ServiceNow/PlatformBusinessApps/SSJ/selenium/Pages/ApplicantFlowPage.java
removed

2024-03-23 23:30 UTC, alenaminsk commented on src/test/java/ServiceNow/PlatformBusinessApps/SSJ/selenium/Pages/OWMVacancyPage.java
added

2024-03-23 23:30 UTC, alenaminsk commented on src/test/java/ServiceNow/PlatformBusinessApps/SSJ/selenium/Pages/StadtmanVacancyPage.java
added

2024-03-23 23:30 UTC, alenaminsk commented on src/test/java/ServiceNow/PlatformBusinessApps/SSJ/selenium/Steps/ApplicantFlowSteps.java
> +
removed

2024-03-23 23:30 UTC, alenaminsk commented on src/test/java/ServiceNow/PlatformBusinessApps/SSJ/selenium/Steps/ApplicantFlowSteps.java
> +
removed

2024-03-23 23:30 UTC, alenaminsk commented on src/test/java/ServiceNow/PlatformBusinessApps/SSJ/selenium/Steps/OWMVacancySteps.java
added

2024-03-23 23:30 UTC, alenaminsk commented on src/test/java/ServiceNow/PlatformBusinessApps/SSJ/selenium/Steps/StadtmanVacancySteps.java
added

2024-03-23 23:30 UTC, alenaminsk commented on src/test/java/ServiceNow/PlatformBusinessApps/SSJ/selenium/Steps/UnauthenticatedApplicantSteps.java
removed

2024-03-23 23:30 UTC, alenaminsk commented on src/test/java/ServiceNow/PlatformBusinessApps/SSJ/selenium/StepsImplementation/ApplicantFlowStepsImplementation.java
> +
removed

2024-03-23 23:30 UTC, alenaminsk commented on src/test/java/ServiceNow/PlatformBusinessApps/SSJ/selenium/StepsImplementation/ApplicantFlowStepsImplementation.java
> +
removed

2024-03-23 23:30 UTC, alenaminsk commented on src/test/java/ServiceNow/PlatformBusinessApps/SSJ/selenium/StepsImplementation/ApplicantFlowStepsImplementation.java
> +
removed

2024-03-23 23:30 UTC, alenaminsk commented on src/test/java/ServiceNow/PlatformBusinessApps/SSJ/selenium/StepsImplementation/OWMVacancyStepsImplementation.java
fixed

2024-03-23 23:30 UTC, alenaminsk commented on src/test/java/ServiceNow/PlatformBusinessApps/SSJ/selenium/StepsImplementation/OWMVacancyStepsImplementation.java
> +//        CommonUtils.sendKeys(owmVacancyPage.vacancyOpenDateTextBox, OWMVacanciesConstants.TODAYS_DATE);
removed

2024-03-23 23:30 UTC, alenaminsk commented on src/test/java/ServiceNow/PlatformBusinessApps/SSJ/selenium/StepsImplementation/OWMVacancyStepsImplementation.java
> +
removed

2024-03-23 23:30 UTC, alenaminsk commented on src/test/java/ServiceNow/PlatformBusinessApps/SSJ/selenium/StepsImplementation/OWMVacancyStepsImplementation.java
> +       // CommonUtils.waitForClickability(owmVacancyPage.positionClassificationDropdownOptions(2));
removed

2024-03-23 23:30 UTC, alenaminsk commented on src/test/java/ServiceNow/PlatformBusinessApps/SSJ/selenium/StepsImplementation/OWMVacancyStepsImplementation.java
> +       // CommonUtils.assertEqualsWithMessage(yourVacancies, owmVacancyPage.tabOption(yourVacancies).getText(), "-- VERIFYING YOUR VACANCIES TAB --");
removed

2024-03-23 23:30 UTC, alenaminsk commented on src/test/java/ServiceNow/PlatformBusinessApps/SSJ/selenium/StepsImplementation/StadtmanVacancyStepsImplementation.java
fixed

2024-03-23 23:30 UTC, alenaminsk commented on src/test/java/ServiceNow/PlatformBusinessApps/SSJ/selenium/StepsImplementation/StadtmanVacancyStepsImplementation.java
fixed

2024-03-23 23:30 UTC, alenaminsk commented on src/test/java/ServiceNow/PlatformBusinessApps/SSJ/selenium/StepsImplementation/StadtmanVacancyStepsImplementation.java
> +//        JavascriptUtils.clickByJS(owmVacancyPage.calendarDatePicker.get(Integer.parseInt(openDate.substring(6,8))-1));
fixed

2024-03-23 23:30 UTC, alenaminsk commented on src/test/java/ServiceNow/PlatformBusinessApps/SSJ/selenium/StepsImplementation/StadtmanVacancyStepsImplementation.java
> +       // CommonUtils.waitForClickability(owmVacancyPage.positionClassificationDropdownOptions(1));
fixed

2024-03-23 23:30 UTC, alenaminsk commented on src/test/java/ServiceNow/PlatformBusinessApps/SSJ/selenium/StepsImplementation/StadtmanVacancyStepsImplementation.java
> +     //   CommonUtils.assertEqualsWithMessage(owmVacancyPage.owmVacancyDynamicLocatorHomePage(StadtmanVacanciesConstants.VACANCY_TITLE).getText(),StadtmanVacanciesConstants.VACANCY_INSTITUTE, "-- VER
fixed

2024-03-23 23:30 UTC, alenaminsk commented on src/test/java/ServiceNow/PlatformBusinessApps/SSJ/selenium/StepsImplementation/UnauthenticatedApplicantFlowStepsImplementation.java
fixed

2024-03-23 23:30 UTC, alenaminsk commented on src/test/java/ServiceNow/PlatformBusinessApps/SSJ/selenium/StepsImplementation/UnauthenticatedApplicantFlowStepsImplementation.java
fixed

2024-03-23 23:30 UTC, alenaminsk commented on src/test/java/ServiceNow/PlatformBusinessApps/SSJ/selenium/StepsImplementation/UnauthenticatedApplicantFlowStepsImplementation.java
> +
fixed

2024-03-25 15:50 UTC, matakevin requested changes
I think there's only one class that has an extra empty line in it.  Aside from that, the PR looks great!

2024-03-25 15:50 UTC, matakevin commented on src/test/java/ServiceNow/PlatformBusinessApps/SSJ/selenium/Steps/ApplicantFlowSteps.java
Remove line 223

2024-03-25 15:53 UTC, matakevin reviewed
A few extra empty spaces

2024-03-25 15:53 UTC, matakevin commented on src/test/java/GrantsApps/EM/selenium/Steps/HooksSteps.java
Please remove lines 1, 3 and 36

2024-03-25 16:39 UTC, iamdez99 approved these changes
Reviewed and approved - juarezds

2024-03-25 16:40 UTC, merged