Satya
CBIIT/CBIIT-Test-Automation pull request #213
Opened 2024-03-26 18:07 UTC by sgugulothu

2024-03-26 18:33 UTC, matakevin requested changes
Please look through the requested changes, thank you!

2024-03-26 18:33 UTC, matakevin commented on src/main/resources/conf/env/test.xml
The URL provided on line 1058 for 3DVizSNP is for the dev site.  Please change to QA and make sure all the test cases that were running on dev still work on QA.

2024-03-26 18:33 UTC, matakevin commented on src/test/java/AnalysisTools/AnalysisToolsRunners/RunThreeDVizSNPProgressionTest.java
Please update the runners to include testNG imports and remove empty lines on 17, 19, 21, 22

2024-03-26 18:33 UTC, matakevin commented on src/test/java/AnalysisTools/AnalysisToolsRunners/RunThreeDVizSNPProgressionTest.java
This is also the Progression Runner, please keep the tag as "@Progression" when pushing to master

2024-03-26 18:33 UTC, matakevin commented on src/test/java/AnalysisTools/AnalysisToolsRunners/RunThreeDVizSNPRegressionTest.java
We no longer use JUnit runners or imports.  Please change them to testNG Imports and remove the RunsWith Commands on all new runners

2024-03-26 18:33 UTC, matakevin commented on src/test/java/AnalysisTools/AnalysisToolsRunners/RunThreeDVizSNPRegressionTest.java
remove monochrome and strict tags

2024-03-26 18:33 UTC, matakevin commented on src/test/java/AnalysisTools/AnalysisToolsRunners/RunThreeDVizSNPRegressionTest.java
remove empty lines on 16, 19

2024-03-26 18:33 UTC, matakevin commented on src/test/java/AnalysisTools/AnalysisToolsRunners/RunThreeDVizSNPSmokeTest.java
Remove empty lines on 13, 14, 18.
This is the Smoke Runner, please change the tag for it to be "@Smoke"

2024-03-26 18:33 UTC, matakevin commented on src/test/java/AnalysisTools/MCAExplorer/Features/MCAExplorer.feature
Please format this feature file to be consistent throughout the class

2024-03-26 18:33 UTC, matakevin commented on src/test/java/AnalysisTools/MCAExplorer/Pages/MCAExplorerPage.java
Add comments for all elements, lines 56-62 have no comments describing what they are.  If they're a different Age value, tag what age value they are

2024-03-26 18:33 UTC, matakevin commented on src/test/java/AnalysisTools/MCAExplorer/Steps/HooksSteps.java
Is there any reason we're taking a screenshot before closing the browser?  
Analysis tools doesn't require screenshots to be taken.

2024-03-26 18:33 UTC, matakevin commented on src/test/java/AnalysisTools/MCAExplorer/Steps/MCAExplorer_pairwiseplots_steps.java
Please remove empty lines on 58, 60.

2024-03-26 18:33 UTC, matakevin commented on src/test/java/AnalysisTools/MCAExplorer/Steps/MCAExplorer_steps.java
Please remove line 231

2024-03-26 18:33 UTC, matakevin commented on src/test/java/AnalysisTools/MCAExplorer/StepsImplementations/MCAExplorerStepImp.java
Remove lines 5, 91, 127.
For stepImplementations classes, use a javadoc or comment to state what the created methods are doing/used for.

2024-03-26 18:33 UTC, matakevin commented on src/test/java/AnalysisTools/ThreeDVizSNP/Features/ThreeDVizSNP.feature
Please check all Smoke tags, lowercased "smoke" will not run when running SmokeRunners with a "Smoke" tag

2024-03-26 18:33 UTC, matakevin commented on src/test/java/AnalysisTools/ThreeDVizSNP/Pages/ThreeDVizSNPPage.java
Remove lines 116-119

2024-03-26 18:33 UTC, matakevin commented on src/test/java/AnalysisTools/ThreeDVizSNP/StepsImplementations/ThreeDVizSNPStepImp.java
Remove empty lines in the imports

2024-03-26 18:33 UTC, matakevin commented on src/test/java/appsCommon/PageInitializers/PageInitializer.java
Delete line 657.
On line 356, make sure to label the separator "ThreeDVizSNP INSTANCES"

2024-03-26 18:33 UTC, matakevin commented on src/test/resources/example.vcf
This file should go in a folder labeled what the application is for.

2024-03-26 18:33 UTC, matakevin commented on src/test/resources/invalid.vcf
This file should go in a folder labeled what the application is for.

2024-03-26 18:36 UTC, sgugulothu commented on src/test/java/AnalysisTools/MCAExplorer/Steps/HooksSteps.java
I wanted it for better reporting and help in debugging in jenkins. I can remove it if required . Let me know

2024-03-26 19:23 UTC, hamidnesar requested changes

2024-03-26 19:23 UTC, hamidnesar commented on src/test/java/AnalysisTools/MCAExplorer/Pages/MCAExplorerPage.java
>  	/**study button**/
I was instructed by @iamdez99 to keep all the comments in uppercase across the page like: /** STUDY BUTTON **/ vs /**study button**/

2024-03-26 19:23 UTC, hamidnesar commented on src/test/java/AnalysisTools/MCAExplorer/Steps/MCAExplorer_pairwiseplots_steps.java
> +
Please remove lines 58 and 60

2024-03-26 19:23 UTC, hamidnesar commented on src/test/java/AnalysisTools/MCAExplorer/Steps/MCAExplorer_steps.java
> +
please remove line 104

2024-03-26 19:23 UTC, hamidnesar commented on src/test/java/AnalysisTools/MCAExplorer/Steps/MCAExplorer_steps.java
please remove line 231

2024-03-26 19:23 UTC, hamidnesar commented on src/test/java/AnalysisTools/MCAExplorer/StepsImplementations/MCAExplorerStepImp.java
> +
Please remove line 5

2024-03-26 19:23 UTC, hamidnesar commented on src/test/java/AnalysisTools/MCAExplorer/StepsImplementations/MCAExplorerStepImp.java
> +			// TODO: handle exception
Please remove line 69

2024-03-26 19:23 UTC, hamidnesar commented on src/test/java/AnalysisTools/MCAExplorer/StepsImplementations/MCAExplorerStepImp.java
> +			// TODO Auto-generated catch block
Please remove line 77

2024-03-26 19:23 UTC, hamidnesar commented on src/test/java/AnalysisTools/MCAExplorer/StepsImplementations/MCAExplorerStepImp.java
> +
Please remove this method since it is empty

2024-03-26 19:23 UTC, hamidnesar commented on src/test/java/AnalysisTools/ThreeDVizSNP/Features/ThreeDVizSNP.feature
> +  @TC1 @satya @Smoke @Regression
I do not believe you need to tag your scenarios as @TC

2024-03-26 19:23 UTC, hamidnesar commented on src/test/java/AnalysisTools/ThreeDVizSNP/Pages/ThreeDVizSNPPage.java
> +
Please remove lines 116-119

2024-03-26 19:23 UTC, hamidnesar commented on src/test/java/AnalysisTools/ThreeDVizSNP/Steps/ThreeDVizSNP_steps.java
> +	}
These should be implemented in the StepsImplementation class and call those methods in these steps.

2024-03-26 19:23 UTC, hamidnesar commented on src/test/java/AnalysisTools/ThreeDVizSNP/StepsImplementations/ThreeDVizSNPStepImp.java
> +
Please remove lines 4, 7 and 9

2024-03-26 19:23 UTC, hamidnesar commented on src/test/java/AnalysisTools/ThreeDVizSNP/StepsImplementations/ThreeDVizSNPStepImp.java
> +}
Please add comments for each method to explain what they are doing

2024-03-26 19:23 UTC, hamidnesar commented on src/test/java/appsCommon/PageInitializers/PageInitializer.java
> +
Please remove lines 653 and 657

2024-03-26 19:23 UTC, hamidnesar commented on src/test/resources/invalid.vcf
> +extent.reporter.spark.vieworder=dashboard,test,category,exception,author,device,log
Please explain the purpose of this file and if it is necessary this should be stored in your application directory not the resources folder

2024-03-26 19:23 UTC, hamidnesar commented on src/test/resources/example.vcf
> +##fileformat=VCFv4.2
Please explain the purpose of this file and if it is necessary this should be stored in your application directory not the resources folder

2024-03-26 19:24 UTC, iamdez99 requested changes

2024-03-26 19:24 UTC, iamdez99 commented on src/test/resources/invalid.vcf
can you please change screenshot.dir=/Screenshots/ to screenshot.dir=target/Screenshots/

2024-03-26 19:24 UTC, iamdez99 commented on src/test/resources/example.vcf
What is this file for? Is it specific for an application? It should be within the application package

2024-03-26 19:24 UTC, iamdez99 commented on src/test/java/AnalysisTools/AnalysisToolsRunners/RunThreeDVizSNPRegressionTest.java
Remove the junit plugins junit:target/cucumber.xml

2024-03-26 19:24 UTC, iamdez99 commented on src/test/java/AnalysisTools/MCAExplorer/Features/MCAExplorer.feature
2341 should be a dynamic value - lets get on a call to discuss this

2024-03-26 19:24 UTC, iamdez99 commented on src/test/java/AnalysisTools/MCAExplorer/Pages/MCAExplorerPage.java
Please uppercase commented element descriptions study dropdown - /*** STUDY DROPDOWN */

2024-03-26 19:24 UTC, iamdez99 commented on src/test/java/AnalysisTools/MCAExplorer/Steps/HooksSteps.java
Go ahead and leave this here Satya, but please add it to all your hooks class.

2024-03-27 03:59 UTC, sgugulothu commented on src/test/resources/example.vcf
Moved into application util package as per the discussion on teams

2024-03-27 04:08 UTC, sgugulothu commented on src/test/resources/invalid.vcf
> +extent.reporter.spark.vieworder=dashboard,test,category,exception,author,device,log
Moved it into application util folder as per the discussion on teams

2024-03-27 04:20 UTC, sgugulothu commented on src/test/java/AnalysisTools/MCAExplorer/Pages/MCAExplorerPage.java
>  	/**study button**/
I can follow this going forward if its not very impotant to do it in this file, It will be lot of rework. But let me know

2024-03-27 04:22 UTC, sgugulothu commented on src/test/java/AnalysisTools/ThreeDVizSNP/Steps/ThreeDVizSNP_steps.java
> +	}
I have moved the code into impl class where ever there was more than 1 line of code in step defination

2024-03-27 04:29 UTC, sgugulothu commented on src/test/resources/invalid.vcf
This file am just using for a negative test case, its not going to effeect the screenshots etc.

2024-03-27 14:45 UTC, hamidnesar requested changes
Please review the comments across the files.

2024-03-27 14:45 UTC, hamidnesar commented on src/test/java/AnalysisTools/AnalysisToolsRunners/RunMCAExplorerRegressionTest.java
> +	    "junit:target/cucumber.xml",
Please remove line 9

2024-03-27 14:45 UTC, hamidnesar commented on src/test/java/AnalysisTools/AnalysisToolsRunners/RunMCAExplorerRegressionTest.java
> +		"html:target/html-reports/cucumber-default-report",
Add .html after the report such as: 
"html:target/html-reports/cucumber-default-report.html"

2024-03-27 14:45 UTC, hamidnesar commented on src/test/java/AnalysisTools/AnalysisToolsRunners/RunMCAExplorerProgressionTest.java
> +		"html:target/html-reports/cucumber-default-report",
Add .html after the report such as:
"html:target/html-reports/cucumber-default-report.html"

2024-03-27 14:45 UTC, hamidnesar commented on src/test/java/AnalysisTools/AnalysisToolsRunners/RunMCAExplorerSmokeTest.java
> +		"html:target/html-reports/cucumber-default-report",
1. Add .html after the report such as: "html:target/html-reports/cucumber-default-report.html"
2. Please format lines 7 - 11

2024-03-27 14:45 UTC, hamidnesar commented on src/test/java/AnalysisTools/AnalysisToolsRunners/RunMCAExplorerSmokeTest.java
> +		"junit:target/cucumber.xml",
Please remove line 9. We are not using Junit anymore

2024-03-27 14:45 UTC, hamidnesar commented on src/test/java/AnalysisTools/AnalysisToolsRunners/RunThreeDVizSNPProgressionTest.java
> +		"html:target/html-reports/cucumber-default-report",
Add .html after the report such as: "html:target/html-reports/cucumber-default-report.html"

2024-03-27 14:45 UTC, hamidnesar commented on src/test/java/AnalysisTools/AnalysisToolsRunners/RunThreeDVizSNPProgressionTest.java
> +		"junit:target/cucumber.xml",
Please remove line 9. We are no longer using Junit

2024-03-27 14:45 UTC, hamidnesar commented on src/test/java/AnalysisTools/AnalysisToolsRunners/RunThreeDVizSNPRegressionTest.java
> +		"html:target/html-reports/cucumber-default-report",
1. Add .html after the report such as: "html:target/html-reports/cucumber-default-report.html"
2. Please format lines 7 - 11

2024-03-27 14:45 UTC, hamidnesar commented on src/test/java/AnalysisTools/AnalysisToolsRunners/RunThreeDVizSNPRegressionTest.java
> +	    "junit:target/cucumber.xml",
Please remove line 9

2024-03-27 14:45 UTC, hamidnesar commented on src/test/java/AnalysisTools/AnalysisToolsRunners/RunThreeDVizSNPSmokeTest.java
> +		"rerun:target/failed.txt", "pretty" }
1. Add .html after the report such as: "html:target/html-reports/cucumber-default-report.html"
2. Please format lines 7 - 10
3. Please remove line 9.

2024-03-27 14:45 UTC, hamidnesar commented on src/test/java/AnalysisTools/MCAExplorer/Pages/MCAExplorerPage.java
>  	/**study button**/
Please consult with Diego @iamdez99. Thank you!

2024-03-27 14:45 UTC, hamidnesar commented on src/test/java/AnalysisTools/MCAExplorer/Steps/MCAExplorer_pairwiseplots_steps.java
> +				"Study: PLCO,UK Biobank; Types: CN-LOH");
Assertion must be implemented in the StepsImplementation class and called here

2024-03-27 14:45 UTC, hamidnesar commented on src/test/java/AnalysisTools/MCAExplorer/Steps/MCAExplorer_steps.java
>  		JavascriptUtils.clickByJS(mcaExplorerPage.export_data_btn);
These must be implemented in the StepsImplementation class and called here

2024-03-27 14:45 UTC, hamidnesar commented on src/test/java/AnalysisTools/MCAExplorer/StepsImplementations/MCAExplorerStepImp.java
> +	/** test healper class object **/
Please correct the spelling error in the comment. **healper vs helper**

2024-03-27 14:45 UTC, hamidnesar commented on src/test/java/AnalysisTools/ThreeDVizSNP/Steps/HooksSteps.java
> +		CucumberLogUtils.logScreenshot();
Is there a need to take a screenshot every time a page is closed? Screenshots could be implemented across all your steps implementation.

2024-03-27 14:45 UTC, hamidnesar commented on src/test/java/AnalysisTools/ThreeDVizSNP/Steps/ThreeDVizSNP_steps.java
> +		WebDriverUtils.webDriver.get(EnvUtils.getApplicationUrl("ThreeDVizSNP"));
This must be implemented in the StepsImplementation class and called here

2024-03-27 14:45 UTC, hamidnesar commented on src/test/java/AnalysisTools/ThreeDVizSNP/Steps/ThreeDVizSNP_steps.java
> +		ThreeDVizSNPPage.visulizeButton.click();
This must be implemented in the StepsImplementation class and called here

2024-03-27 14:45 UTC, hamidnesar commented on src/test/java/AnalysisTools/ThreeDVizSNP/Steps/ThreeDVizSNP_steps.java
> +		ThreeDVizSNPPage.submitButton.click();
This must be implemented in the StepsImplementation class and called here

2024-03-27 14:45 UTC, hamidnesar commented on src/test/java/AnalysisTools/ThreeDVizSNP/Steps/ThreeDVizSNP_steps.java
> +		ThreeDVizSNPStepImp.dismissPopUpAlert();
This must be implemented in the StepsImplementation class and called here

2024-03-27 14:45 UTC, hamidnesar commented on src/test/java/AnalysisTools/ThreeDVizSNP/Steps/ThreeDVizSNP_steps.java
> +	}
These must be implemented in the StepsImplementation class and called here

2024-03-27 14:45 UTC, hamidnesar commented on src/test/java/AnalysisTools/ThreeDVizSNP/Steps/ThreeDVizSNP_steps.java
> +	}
These must be implemented in the StepsImplementation class and called here

2024-03-27 16:48 UTC, sgugulothu commented on src/test/java/AnalysisTools/ThreeDVizSNP/Steps/HooksSteps.java
> +		CucumberLogUtils.logScreenshot();
I want to make sure even if test case fails at any point it takes a screenshot. this can be implemented in hooks only

2024-03-27 17:30 UTC, iamdez99 requested changes
Please view and address comments.

2024-03-27 17:30 UTC, iamdez99 commented on src/test/java/AnalysisTools/MCAExplorer/StepsImplementations/MCAExplorerStepImp.java
Please remove space on line 8.

2024-03-27 17:30 UTC, iamdez99 commented on src/test/java/AnalysisTools/ThreeDVizSNP/Features/ThreeDVizSNP.feature
Please add US and TC ID's.

2024-03-27 17:30 UTC, iamdez99 commented on src/test/java/AnalysisTools/ThreeDVizSNP/Pages/ThreeDVizSNPPage.java
There should be a space after line 1 to separate package and import statements.

2024-03-27 17:30 UTC, iamdez99 commented on src/test/java/AnalysisTools/ThreeDVizSNP/StepsImplementations/ThreeDVizSNPStepImp.java
Moving forward, I recommend you make these methods static, that way you won't have to keep creating objects of steps implementation classes.

2024-03-27 17:30 UTC, iamdez99 commented on src/test/java/AnalysisTools/ThreeDVizSNP/Utils/invalid.vcf
Can you please explain this file? It looks like an extent.properties

2024-03-27 17:36 UTC, sgugulothu commented on src/test/java/AnalysisTools/ThreeDVizSNP/Utils/invalid.vcf
in my test case i had to uload any invalid file to validate a negative scenario. I picked the extent.properties and renamed it invalid.vcf. I can take any other file to it doesnt matter.

2024-03-27 17:37 UTC, hamidnesar requested changes

2024-03-27 17:37 UTC, hamidnesar commented on src/test/java/AnalysisTools/AnalysisToolsRunners/RunMCAExplorerProgressionTest.java
> +		, "json:target/cucumber.json"
Please add "rerun:target/failed.txt". You were supposed to only remove Junit

2024-03-27 17:37 UTC, hamidnesar commented on src/test/java/AnalysisTools/AnalysisToolsRunners/RunMCAExplorerRegressionTest.java
> +		,"pretty" }
Please format lines 7, 8, 9

2024-03-27 17:37 UTC, hamidnesar commented on src/test/java/AnalysisTools/AnalysisToolsRunners/RunMCAExplorerSmokeTest.java
> +		,"pretty" }
Please format lines 7, 8, 9

2024-03-27 17:37 UTC, hamidnesar commented on src/test/java/AnalysisTools/AnalysisToolsRunners/RunThreeDVizSNPRegressionTest.java
> +		, "pretty" }
Please format lines 7, 8, 9

2024-03-27 17:37 UTC, hamidnesar commented on src/test/java/AnalysisTools/MCAExplorer/Steps/MCAExplorer_pairwiseplots_steps.java
> +		JavascriptUtils.clickByJS(mcaExplorerPage.age_checkbox);
It is recommended to implement this in StepsImplementation class and then call it here. Your code would be more consistent.

2024-03-27 17:37 UTC, hamidnesar commented on src/test/java/AnalysisTools/MCAExplorer/Steps/MCAExplorer_pairwiseplots_steps.java
> +				"Study: PLCO,UK Biobank; Types: CN-LOH");
It is recommended to implement this in StepsImplementation class and then call it here. Your code would be more consistent.

2024-03-27 17:37 UTC, hamidnesar commented on src/test/java/AnalysisTools/MCAExplorer/Steps/MCAExplorer_pairwiseplots_steps.java
> +
Please remove line 84

2024-03-27 17:37 UTC, hamidnesar commented on src/test/java/AnalysisTools/MCAExplorer/Steps/MCAExplorer_steps.java
> +		mcaExplorerStepImp.clickOnSubmitButton();
It is recommended to implement these in StepsImplementation class and then call them here. Your code would be more consistent.

2024-03-27 17:37 UTC, hamidnesar commented on src/test/java/AnalysisTools/MCAExplorer/Steps/MCAExplorer_steps.java
> +				+ "}");
can these parameters be passed to the method in StepsImplementation class? that way your steps would be much cleaner.

2024-03-27 17:37 UTC, hamidnesar commented on src/test/java/AnalysisTools/ThreeDVizSNP/Pages/ThreeDVizSNPPage.java
> +	/** FEEDBACK IFRME **/
Please change IFRME to IFRAME

2024-03-27 17:37 UTC, hamidnesar commented on src/test/java/AnalysisTools/MCAExplorer/Steps/MCAExplorer_steps.java
> +				+ "}");
can these parameters be passed to the method in StepsImplementation class? that way your steps would be much cleaner.

2024-03-27 17:37 UTC, hamidnesar commented on src/test/java/AnalysisTools/ThreeDVizSNP/StepsImplementations/ThreeDVizSNPStepImp.java
> +	/** Upload exmple VCF File**/
Please change exmple to example

2024-03-27 17:37 UTC, hamidnesar commented on src/test/java/AnalysisTools/ThreeDVizSNP/StepsImplementations/ThreeDVizSNPStepImp.java
> +	/** Upload exmple VCF File after clicking vizulize button and then submit**/
Please change exmple to example.

2024-03-27 17:40 UTC, sgugulothu commented on src/test/java/AnalysisTools/MCAExplorer/Steps/MCAExplorer_pairwiseplots_steps.java
> +				"Study: PLCO,UK Biobank; Types: CN-LOH");
its already in steps Implementation class only. if you check the object used its for imp class

2024-03-27 17:41 UTC, sgugulothu commented on src/test/java/AnalysisTools/MCAExplorer/Steps/MCAExplorer_steps.java
> +		mcaExplorerStepImp.clickOnSubmitButton();
The object here is for impl class only. The code is there in IMPL class

2024-03-27 17:43 UTC, sgugulothu commented on src/test/java/AnalysisTools/MCAExplorer/Steps/MCAExplorer_steps.java
> +				+ "}");
We can have one line code in step definitions as per my understanding. We will be just adding more lines to implement 1 line of code by moving that into imp class which doesnt increase code readability also. I dont see any valid reasons to move one line simple codes into impl classes

2024-03-27 17:44 UTC, sgugulothu commented on src/test/java/AnalysisTools/MCAExplorer/Steps/MCAExplorer_pairwiseplots_steps.java
> +		JavascriptUtils.clickByJS(mcaExplorerPage.age_checkbox);
We can have one line code in step definitions as per my understanding. We will be just adding more lines to implement 1 line of code by moving that into imp class which doesnt increase code readability also. I dont see any valid reasons to move one line simple codes into impl classes

2024-03-27 18:25 UTC, hamidnesar requested changes
Please review the updated comments

2024-03-27 18:25 UTC, hamidnesar commented on src/test/java/AnalysisTools/AnalysisToolsRunners/RunMCAExplorerRegressionTest.java
> +		, "pretty" }
Please format lines 7, 8, 9

2024-03-27 18:25 UTC, hamidnesar commented on src/test/java/AnalysisTools/AnalysisToolsRunners/RunMCAExplorerSmokeTest.java
> +		, "pretty" }
Please format lines 7, 8, 9

2024-03-27 18:25 UTC, hamidnesar commented on src/test/java/AnalysisTools/AnalysisToolsRunners/RunThreeDVizSNPSmokeTest.java
> +		, "pretty" }
Please format lines 7, 8, 9. Shift to the left so they are aligned with lines 10 - 13

![2024-03-27_14h02_51](https://github.com/CBIIT/CBIIT-Test-Automation/assets/83662518/1e3726a7-6981-45bd-9127-d83b54a7d9b8)

2024-03-27 18:31 UTC, hamidnesar commented on src/test/java/AnalysisTools/ThreeDVizSNP/Pages/ThreeDVizSNPPage.java
> +	/** SVG BUTTON **/
Please add a space

2024-03-27 20:54 UTC, hamidnesar commented on src/test/java/appsCommon/PageInitializers/PageInitializer.java
> +	public static AnalysisTools.ThreeDVizSNP.StepsImplementations.ThreeDVizSNPStepImp ThreeDVizSNPStepImp;
It is a good practice to create instance variables with lower characters such as: threeDVizSNPPage or threeSVizSNPStepImp

2024-03-27 20:56 UTC, hamidnesar commented on src/test/java/appsCommon/PageInitializers/PageInitializer.java
> +		/** 3DVIZSNP INSTANCE VERIABLES */
For consistency, it is better to write the application ID the same throughout the page, such as /** --------------- THREEDVIZSNP INSTANCE VARIABLES --------*/

2024-03-27 21:22 UTC, hamidnesar commented on src/test/java/appsCommon/PageInitializers/PageInitializer.java
> +	public static AnalysisTools.ThreeDVizSNP.StepsImplementations.ThreeDVizSNPStepImp threeDVizSNPStepImp;
These should be declared as below: 
	public static ThreeDVizSNPPage threeDVizSNPPage;
	public static ThreeDVizSNPStepImp threeDVizSNPStepImp;

2024-03-27 21:22 UTC, hamidnesar commented on src/test/java/appsCommon/PageInitializers/PageInitializer.java
> +		threeDVizSNPStepImp = new AnalysisTools.ThreeDVizSNP.StepsImplementations.ThreeDVizSNPStepImp();
These should be declared as below: 
	threeDVizSNPPage = new ThreeDVizSNPPage ();
	threeDVizSNPStepImp = new ThreeDVizSNPStepImp ();

2024-03-27 21:41 UTC, hamidnesar commented on src/test/java/AnalysisTools/ThreeDVizSNP/Pages/ThreeDVizSNPPage.java
> +	/** JOBNAME **/
JOB NAME

2024-03-27 22:07 UTC, hamidnesar approved these changes

2024-03-28 12:27 UTC, alenaminsk approved these changes

2024-03-28 15:01 UTC, iamdez99 requested changes
Please make requested changes

2024-03-28 15:48 UTC, iamdez99 approved these changes
Reviewed and approved - juarezds

2024-03-28 15:48 UTC, merged