ACT24 automation + some code clean up
CBIIT/CBIIT-Test-Automation pull request #217
Opened 2024-04-03 18:57 UTC by matakevin

This PR contains some progress on the ACT24 application automation and some clean up for pageInitializer and cedcd classes

2024-04-03 19:22 UTC, Mariachaudhry commented on src/test/java/AnalysisTools/ACT24/Steps/ACT24ResearcherPortalSteps.java
Please add line between 19, 20 and 40,41

2024-04-03 19:32 UTC, Mariachaudhry approved these changes

2024-04-03 20:50 UTC, hamidnesar requested changes
Please review the comments. Thank you!

2024-04-03 20:50 UTC, hamidnesar commented on src/test/java/AnalysisTools/ACT24/Features/ParticipantPortal.feature
> +   @matakevin
Please add @Regression or @Smoke tags plus the Jira story#

2024-04-03 20:50 UTC, hamidnesar commented on src/test/java/AnalysisTools/ACT24/Features/ParticipantPortal.feature
> +  @Smoke @matakevin
Please add @regression

2024-04-03 20:50 UTC, hamidnesar commented on src/test/java/AnalysisTools/ACT24/Features/ResearcherPortal.feature
> +  Scenario: The Researcher can log in
Please add @regression and the Jira story#

2024-04-03 20:50 UTC, hamidnesar commented on src/test/java/AnalysisTools/ACT24/Features/ResearcherPortal.feature
> +  @Smoke @matakevin
Please add @regression and the Jira story#

2024-04-03 20:50 UTC, hamidnesar commented on src/test/java/AnalysisTools/ACT24/Steps/ACT24ParticipantPortalSteps.java
> +        Assert.assertTrue(act24ParticipantPortalPage.act24WelcomeText.isDisplayed());
Shouldn't these be implemented in Steps Implementation class? Per Diego, it is fine as long as it is one line of code.

2024-04-03 20:50 UTC, hamidnesar commented on src/test/java/AnalysisTools/ACT24/Steps/ACT24ParticipantPortalSteps.java
> +    }
Please add a space after line 31

2024-04-03 20:50 UTC, hamidnesar commented on src/test/java/AnalysisTools/ACT24/Steps/ACT24ParticipantPortalSteps.java
> +    }
Please add a space after line 35

2024-04-03 20:50 UTC, hamidnesar commented on src/test/java/AnalysisTools/AnalysisToolsRunners/RunACT24ProgressionTest.java
> +        "junit:target/cucumber.xml", "rerun:target/failed.txt",
Please remove "junit:target/cucumber.xml" from you runner class as we no longer use jUnit.

2024-04-03 20:50 UTC, hamidnesar commented on src/test/java/AnalysisTools/AnalysisToolsRunners/RunACT24ProgressionTest.java
> +        dryRun = true
Please set dryRun to false

2024-04-03 20:50 UTC, hamidnesar commented on src/test/java/AnalysisTools/AnalysisToolsRunners/RunACT24RegressionTest.java
> +        "junit:target/cucumber.xml", "rerun:target/failed.txt",
Please remove "junit:target/cucumber.xml" from you runner class as we no longer use jUnit.

2024-04-03 20:50 UTC, hamidnesar commented on src/test/java/AnalysisTools/AnalysisToolsRunners/RunACT24SmokeTest.java
> +        "junit:target/cucumber.xml", "rerun:target/failed.txt",
Please remove "junit:target/cucumber.xml" from you runner class as we no longer use jUnit.

2024-04-03 20:50 UTC, hamidnesar commented on src/test/java/AnalysisTools/AnalysisToolsRunners/RunACT24RegressionTest.java
> +
Please remove the empty line 22

2024-04-03 20:50 UTC, hamidnesar commented on src/test/java/AnalysisTools/AnalysisToolsRunners/RunACT24SmokeTest.java
> +
Please remove the empty line 22

2024-04-03 20:50 UTC, hamidnesar commented on src/test/java/AnalysisTools/AnalysisToolsRunners/RunJPSurvSmokeTest.java
> +		, dryRun=false
Please remove line 12, "junit:target/cucumber.xml" from you runner class as we no longer use jUnit.

2024-04-03 21:13 UTC, matakevin commented on src/test/java/AnalysisTools/ACT24/Features/ParticipantPortal.feature
> +  @Smoke @matakevin
I'll add the regression tags on the runners

2024-04-03 21:14 UTC, matakevin commented on src/test/java/AnalysisTools/ACT24/Features/ResearcherPortal.feature
> +  Scenario: The Researcher can log in
Analysis Tools doesn't use user stories to automate scenarios.  The dev team asks us to automate certain scenarios (regardless if there's a requirement for it or not.). We hope to change this process soon

2024-04-03 21:17 UTC, matakevin commented on src/test/java/AnalysisTools/ACT24/Steps/ACT24ParticipantPortalSteps.java
> +        Assert.assertTrue(act24ParticipantPortalPage.act24WelcomeText.isDisplayed());
Lines 19 and 20 aren't necessary but I wanted to make sure the welcome page was displayed.  I'll remove these lines

2024-04-03 21:46 UTC, hamidnesar requested changes
Please review the comments.

2024-04-03 21:46 UTC, hamidnesar commented on src/test/java/AnalysisTools/ACT24/Steps/ACT24ResearcherPortalSteps.java
> +        Assert.assertTrue(act24ResearcherPortalPage.researcherText.isDisplayed());
Are lines 17 and 18 necessary?

2024-04-03 21:46 UTC, hamidnesar commented on src/test/java/AnalysisTools/AnalysisToolsRunners/RunACT24ProgressionTest.java
> +        dryRun = true
Please set dryRun to false

2024-04-03 21:46 UTC, hamidnesar commented on src/test/java/AnalysisTools/ACT24/Steps/ACT24ParticipantPortalSteps.java
> +    }
Please add a space after line 33

2024-04-03 21:46 UTC, hamidnesar commented on src/test/java/AnalysisTools/ACT24/Steps/ACT24ParticipantPortalSteps.java
> +    }
Please add a space after line 29

2024-04-03 22:16 UTC, hamidnesar approved these changes
Looks good!
Is the comment on line 38 necessary in ACT24ResearcherPortalSteps.java?

2024-04-03 22:16 UTC, hamidnesar commented on src/test/java/AnalysisTools/ACT24/Steps/ACT24ResearcherPortalSteps.java
> +        //NEED TO CHANGE STUDY ABBREVIATION (THERE CAN'T BE DUPLICATE NAMES)
Is the comment on line 38 necessary?

2024-04-04 16:45 UTC, alenaminsk approved these changes

2024-04-04 16:46 UTC, merged