tag added for SSJ Playwright scenario
CBIIT/CBIIT-Test-Automation pull request #222
Opened 2024-04-10 17:20 UTC by alenaminsk

2024-04-10 17:25 UTC, matakevin approved these changes
Very quick and small PR, LGTM - thank you!

2024-04-10 17:30 UTC, puzikovam2 approved these changes
approved by puzikovam2

2024-04-10 18:41 UTC, iamdez99 requested changes

2024-04-10 18:41 UTC, iamdez99 commented on src/test/java/ServiceNow/PlatformBusinessApps/SSJ/playwright/Features/Applicant Profile.feature
Please run this scenario again and make sure it passes, add screenshots wherever screenshots need to be added, if all is good please add the @Regression tag

2024-04-11 17:48 UTC, alenaminsk commented on src/test/java/ServiceNow/PlatformBusinessApps/SSJ/playwright/Features/Applicant Profile.feature
done

2024-04-11 18:15 UTC, iamdez99 requested changes

2024-04-11 18:15 UTC, iamdez99 commented on src/test/java/ServiceNow/PlatformBusinessApps/SSJ/playwright/Steps/ApplicantProfileSteps.java
Cucumber steps should only have one line of code, you will have to add screenshots in the steps implementation classes.

2024-04-11 18:15 UTC, iamdez99 commented on src/test/java/ServiceNow/PlatformBusinessApps/SSJ/playwright/Features/Applicant Profile.feature
Sorry - I meant @Regression not @regression

2024-04-11 18:36 UTC, iamdez99 approved these changes
Reviewed and approved - juarezds

2024-04-11 18:37 UTC, merged