"CTRPSNOW-88 Atomated - Task - CTRPSNOW-92" ~Chaudhryma
CBIIT/CBIIT-Test-Automation pull request #223
Opened 2024-04-12 17:13 UTC by Mariachaudhry

2024-04-12 23:34 UTC, iamdez99 requested changes
Please make requested changes.

2024-04-12 23:34 UTC, iamdez99 commented on src/test/java/ServiceNow/PlatformBusinessApps/CTRP_CTRO/Selenium/Constants/CTRPCTRO_NV_Constants.java
Please add a space after line 5.

2024-04-12 23:34 UTC, iamdez99 commented on src/test/java/ServiceNow/PlatformBusinessApps/CTRP_CTRO/Selenium/StepImplementation/CTRPCTRO_NV_StepImpl.java
Please use selenium waits instead of sleep() from Java. Also, highlighting elements in blue/red does not perform an Assertion. The highlighted elements will display in report screenshots. Your code is missing a lot of assertions. Please fix this ASAP for all test cases.

2024-04-12 23:34 UTC, iamdez99 commented on src/test/java/ServiceNow/PlatformBusinessApps/SNOWOBF/playwright/Features/OBF_NCI_Portal_Form.feature
Progression tag cannot be merged to master.

2024-04-12 23:34 UTC, iamdez99 commented on src/test/java/ServiceNow/PlatformBusinessApps/SNOWOBF/playwright/Steps/OBF_NCI_Portal_Form_Steps.java
Remove space on line 11.

2024-04-14 04:01 UTC, Mariachaudhry commented on src/test/java/ServiceNow/PlatformBusinessApps/CTRP_CTRO/Selenium/StepImplementation/CTRPCTRO_NV_StepImpl.java
added more assertions. Assertions are added where needed as per test case. let me know if you want me to add more or we can discuss about it on Monday.

2024-04-14 04:05 UTC, Mariachaudhry commented
updates are commited. Please review again @iamdez99

2024-04-15 19:05 UTC, alenaminsk approved these changes

2024-04-17 15:40 UTC, iamdez99 approved these changes
Reviewed and approved - juarezds

2024-04-17 15:41 UTC, merged