Satya
CBIIT/CBIIT-Test-Automation pull request #224
Opened 2024-04-17 18:10 UTC by sgugulothu

New Test cases for Comets Analytics application

2024-04-18 17:22 UTC, hamidnesar commented on src/test/java/AnalysisTools/CometsAnalytics/Features/CometsAnalytics.feature
> +  Scenario: Verify user is able to About Page
there seems to be a word missing between _able to_ and _About page_. You may meant to say is _able to_ open/access/view _About page_

2024-04-18 17:41 UTC, hamidnesar commented on src/test/java/AnalysisTools/CometsAnalytics/StepsImplemantation/CometsAnalyticsStepImp.java
> +		String path = System.getProperty("user.dir") + "/src/test/java/AnalysisTools/CometsAnalytics/Utils/invalid.vcf";
It would be better to declare this string in your constant class and call it here. It would keep your code clean and more readable.

2024-04-18 17:43 UTC, hamidnesar commented on src/test/java/AnalysisTools/CometsAnalytics/StepsImplemantation/CometsAnalyticsStepImp.java
> +		MiscUtils.sleep(20000);
This is holding the execution for 20 seconds. Is it intended?

2024-04-18 17:50 UTC, hamidnesar commented on src/test/java/appsCommon/PageInitializers/PageInitializer.java
> +	/** ----------------- COMETSANALYTICS INSTANCES -----*/
Please add a space between the words _COMET_ and _ANALYTICS_

2024-04-18 17:51 UTC, hamidnesar commented on src/test/java/AnalysisTools/AnalysisToolsRunners/RunThreeDVizSNPProgressionTest.java
> +		, dryRun = true
Please set the dryRun to False

2024-04-18 18:13 UTC, iamdez99 requested changes

2024-04-18 18:13 UTC, iamdez99 commented on src/test/java/appsCommon/PageInitializers/PageInitializer.java
Remove 321 and 323

2024-04-18 18:13 UTC, iamdez99 commented on src/test/java/AnalysisTools/CometsAnalytics/StepsImplemantation/CometsAnalyticsStepImp.java
Replace JUnit assertions with TestNG assertions

2024-04-18 18:13 UTC, iamdez99 commented on src/test/java/AnalysisTools/CometsAnalytics/StepsImplemantation/CometsAnalyticsStepImp.java
Remove WebDriverUtils.webDriver.switchTo().defaultContent();

2024-04-22 18:53 UTC, hamidnesar requested changes
Please see the comments. Thanks!

2024-04-22 18:53 UTC, hamidnesar commented on src/test/java/AnalysisTools/AnalysisToolsRunners/RunThreeDVizSNPProgressionTest.java
> +		, glue = "AnalysisTools.CometsAnalytics.Steps"
The class name indicates _ThreeDVizSNP_, however, the features and steps defined in this runner are referring to _CometsAnalytics_ projects. Looking the at the repo, there are separate projects for Comets2, _CometsAnalytics_ and _ThreeDVizSNP_. Plus, there are three runner classes names as _CometsAnalytics_. 

![image](https://github.com/CBIIT/CBIIT-Test-Automation/assets/83662518/af366cd1-e73f-4903-bf28-a2d6b62676b0)

2024-04-22 18:53 UTC, hamidnesar commented on src/test/java/AnalysisTools/CometsAnalytics/Pagaes/CometsAnalyticsPage.java
> +	/** ACCESIBILITY TEXT **/
ACCESIBILITY vs Accessibility

2024-04-22 18:53 UTC, hamidnesar commented on src/test/java/AnalysisTools/CometsAnalytics/Pagaes/CometsAnalyticsPage.java
> +	/** ACCESIBILITY TEXT **/
ACCESIBILITY vs Accessibility. Additionally, you might consider a different description for this element as it's the same as line 39

2024-04-22 18:53 UTC, hamidnesar commented on src/test/java/AnalysisTools/CometsAnalytics/Pagaes/CometsAnalyticsPage.java
> +	/** ACCESIBILITY TEXT **/
ACCESIBILITY vs Accessibility. Additionally, you might consider a different description for this element as it's the same as line 39

2024-04-22 18:53 UTC, hamidnesar commented on src/test/java/ServiceNow/PlatformBusinessApps/SNOWOBF/playwright/StepImpl/OBF_NCI_NV_Form_StepImpl.java
> +        //PlaywrightUtils.page.getByRole(AriaRole.LINK, new Page.GetByRoleOptions().setName(NCISP_Portal_Page.nativeViewLink)).click();
Please uncomment this line or remove it if no longer in used

2024-04-22 19:12 UTC, sgugulothu commented on src/test/java/ServiceNow/PlatformBusinessApps/SNOWOBF/playwright/StepImpl/OBF_NCI_NV_Form_StepImpl.java
> +        //PlaywrightUtils.page.getByRole(AriaRole.LINK, new Page.GetByRoleOptions().setName(NCISP_Portal_Page.nativeViewLink)).click();
This is not my code

2024-04-22 19:56 UTC, hamidnesar requested changes
Please review the comments

2024-04-22 19:56 UTC, hamidnesar commented on src/test/java/AnalysisTools/AnalysisToolsRunners/RunThreeDVizSNPProgressionTest.java
> +		, glue = "AnalysisTools.CometsAnalytics.Steps"
Please replace CometsAnalytics with ThreeDVizSNP. There is already another progression runner for CometsAnalytics

2024-04-22 19:56 UTC, hamidnesar commented on src/test/java/AnalysisTools/AnalysisToolsRunners/RunMCAExplorerSmokeTest.java
> +        , tags = "@Help"
Please replace @Help with @Smoke tag

2024-04-22 19:56 UTC, hamidnesar commented on src/test/java/AnalysisTools/AnalysisToolsRunners/RunThreeDVizSNPProgressionTest.java
> +		, glue = "AnalysisTools.CometsAnalytics.Steps"
Please replace CometsAnalytics with ThreeDVizSNP on line 11.

2024-04-22 19:56 UTC, hamidnesar commented on src/test/java/AnalysisTools/AnalysisToolsRunners/RunThreeDVizSNPSmokeTest.java
> +        , tags = "@Trest"
Please replace @Trest with @Smoke tag

2024-04-22 19:56 UTC, hamidnesar commented on src/test/java/AnalysisTools/CometsAnalytics/Pagaes/CometsAnalyticsPage.java
> +	/** ACCESIBILITY TEXT **/
Please correct the Accessibility spelling

2024-04-22 19:56 UTC, hamidnesar commented on src/test/java/AnalysisTools/MCAExplorer/StepsImplementations/MCAExplorerStepImp.java
> +		System.out.println(expectedValue.toLowerCase());
Where are you capturing the current and expected values for Chart Header? are they defined in another class?

Here you are just printing them in the console

2024-04-22 19:56 UTC, hamidnesar commented on src/test/java/AnalysisTools/ThreeDVizSNP/Features/ThreeDVizSNP.feature
> +  @Satya @Smoke @Regression @NCIATWP-5955 @Trest
Please correct the spelling for @Test tag

2024-04-23 02:18 UTC, sgugulothu commented on src/test/java/AnalysisTools/MCAExplorer/StepsImplementations/MCAExplorerStepImp.java
> +		System.out.println(expectedValue.toLowerCase());
The expected value is coming from feature file, actual value is fetched from application in step class

2024-04-23 14:27 UTC, hamidnesar requested changes

2024-04-23 15:15 UTC, hamidnesar approved these changes

2024-04-23 15:19 UTC, georgeb79 commented on src/test/java/AnalysisTools/MCAExplorer/Features/MCAExplorer.feature
Is the @Help tag needed? Are you using it for anything?

2024-04-23 15:21 UTC, georgeb79 commented on src/test/java/AnalysisTools/MCAExplorer/StepsImplementations/MCAExplorerStepImp.java
Please remove extra spaces between imports

2024-04-23 15:21 UTC, sgugulothu commented on src/test/java/AnalysisTools/MCAExplorer/Features/MCAExplorer.feature
I add the help tag to run the one test cases 
I removed it

2024-04-23 15:22 UTC, georgeb79 commented on src/test/java/AnalysisTools/ThreeDVizSNP/StepsImplementations/ThreeDVizSNPStepImp.java
The paths could be stored in constants so we don't have to hardcode them and they can be changed in one place.

2024-04-23 15:30 UTC, alenaminsk approved these changes

2024-04-24 13:49 UTC, georgeb79 approved these changes

2024-04-24 17:30 UTC, puzikovam2 requested changes

2024-04-24 17:30 UTC, puzikovam2 commented on src/main/resources/conf/env/test.xml
is the /analysis required for CometsAnalytics URL?

2024-04-24 17:30 UTC, puzikovam2 commented on src/test/java/AnalysisTools/CometsAnalytics/Features/CometsAnalytics.feature
Line 53 Regression tag is missing 'n' at the end

2024-04-24 17:30 UTC, puzikovam2 commented on src/test/java/AnalysisTools/CometsAnalytics/Pagaes/CometsAnalyticsPage.java
File paths should be in a constants class, I understood from Diego and our code review checklist page classes are only for page elements

2024-04-24 17:30 UTC, puzikovam2 commented on src/test/java/ServiceNow/PlatformBusinessApps/SNOWOBF/playwright/Pages/NCISP_Portal_Page.java
File needs to be formatted

2024-04-24 17:30 UTC, puzikovam2 commented on src/test/java/appsCommon/PageInitializers/PageInitializer.java
Line 7, Pages is spelled incorrectly. Same with line 8, StepsImplementation is spelled incorrectly

2024-04-24 17:41 UTC, sgugulothu commented on src/main/resources/conf/env/test.xml
yes we need the url

2024-04-24 18:41 UTC, sgugulothu commented on src/test/java/AnalysisTools/CometsAnalytics/Pagaes/CometsAnalyticsPage.java
do we have the constant class being used in the framework or shall i create a new constant class?

2024-04-25 17:29 UTC, puzikovam2 approved these changes
approved by puzikovam2

2024-05-06 18:46 UTC, iamdez99 requested changes

2024-05-06 18:46 UTC, iamdez99 commented on src/test/java/AnalysisTools/MCAExplorer/StepsImplementations/MCAExplorerStepImp.java
Can you pleas replace comments with javaDoc statements. Remember, for methods, we give descriptions with /** and then press enter on your keyboard

2024-05-06 18:46 UTC, iamdez99 commented on src/test/java/AnalysisTools/ThreeDVizSNP/Pages/ThreeDVizSNPPage.java
Line 125, you do not need @FindAll if you already have @FindBy

2024-05-06 18:46 UTC, iamdez99 commented on src/test/java/AnalysisTools/ThreeDVizSNP/StepsImplementations/ThreeDVizSNPStepImp.java
So, for methods in steps implementation classes, you can make them static so that you do not need to create an object of them in the page initializer class. You can just call these in a static way. Please do this since we have too many objects being initialized already.

2024-05-06 18:46 UTC, iamdez99 commented on src/test/java/ServiceNow/PlatformBusinessApps/SSJ/playwright/Features/Applicant Profile.feature
Please remove progression tag

2024-05-08 16:34 UTC, iamdez99 approved these changes
Reviewed and approved - juarezds

2024-05-08 17:00 UTC, merged