OWM Vacancy Manager scenarios: SSJ application
CBIIT/CBIIT-Test-Automation pull request #226
Opened 2024-04-26 15:54 UTC by alenaminsk

OWM Vacancy Manager scenarios: SSJ application

2024-04-26 16:18 UTC, iamdez99 requested changes

2024-04-26 16:18 UTC, iamdez99 commented on pom.xml
Remove runners name from pom

2024-04-26 16:18 UTC, iamdez99 commented on src/main/java/com/nci/automation/web/PlaywrightUtils.java
Can you please change setHeadless() from true to false? It currently is false on master. I will work on making this dynamic in my next PR.

2024-04-26 16:18 UTC, iamdez99 commented on src/main/resources/conf/env/test.xml
is the '#/' needed at the end of the URL?

2024-04-26 16:18 UTC, iamdez99 commented on src/test/java/ServiceNow/PlatformBusinessApps/SSJ/playwright/Steps/ApplicantProfileSteps.java
There is a commented line of code on this file.

2024-04-26 16:18 UTC, iamdez99 commented on src/test/java/ServiceNow/PlatformBusinessApps/SSJ/playwright/StepsImplementation/ApplicantProfileStepsImpl.java
Empty line with imports.. please check

2024-04-26 16:18 UTC, iamdez99 commented on src/test/java/ServiceNow/PlatformBusinessApps/SSJ/playwright/StepsImplementation/Reset_Account_StepsImpl.java
Where is the EncryptionUtils import being used?

2024-04-26 16:18 UTC, iamdez99 commented on src/test/java/appsCommon/PlaywrightUtils/Playwright_ServiceNow_Common_Methods.java
Please review your PRs with more attention to detail. This is the whole point of QA's reviewing PRs before asking the team to review so we dont point out simple errors.

2024-04-26 16:38 UTC, alenaminsk commented on pom.xml
removed

2024-04-26 16:40 UTC, alenaminsk commented on src/main/java/com/nci/automation/web/PlaywrightUtils.java
changed

2024-04-26 16:41 UTC, alenaminsk commented on src/main/resources/conf/env/test.xml
removed

2024-04-26 16:43 UTC, alenaminsk commented on src/test/java/ServiceNow/PlatformBusinessApps/SSJ/playwright/StepsImplementation/ApplicantProfileStepsImpl.java
removed

2024-04-26 16:44 UTC, alenaminsk commented on src/test/java/ServiceNow/PlatformBusinessApps/SSJ/playwright/StepsImplementation/Reset_Account_StepsImpl.java
removed

2024-04-26 16:46 UTC, alenaminsk commented on src/test/java/appsCommon/PlaywrightUtils/Playwright_ServiceNow_Common_Methods.java
Thank you Diego

2024-04-26 17:37 UTC, hamidnesar requested changes
Please review the comments. Thanks!

2024-04-26 17:37 UTC, hamidnesar commented on src/test/java/ServiceNow/PlatformBusinessApps/SSJ/playwright/Features/Applicant Profile.feature
> +  @Regression @Smoke @alenan @APPTRACK-712
Is SSJ and APPTRACK the same application? If not, the story tag should be adjusted accordingly

2024-04-26 17:37 UTC, hamidnesar commented on src/test/java/ServiceNow/PlatformBusinessApps/SSJ/playwright/Features/OWM_Vacancy_Manager.feature
> +  @SSJ-7  @SSJ-8
Missing @regression or @smoke tags

2024-04-26 17:37 UTC, hamidnesar commented on src/test/java/ServiceNow/PlatformBusinessApps/SSJ/playwright/Features/OWM_Vacancy_Manager.feature
> +  @SSJ-69
Missing @regression or @smoke tags

2024-04-26 17:37 UTC, hamidnesar commented on src/test/java/ServiceNow/PlatformBusinessApps/SSJ/playwright/Features/OWM_Vacancy_Manager.feature
> +  @SSJ-185 @SSJ-306
Missing @regression or @smoke tags

2024-04-26 17:37 UTC, hamidnesar commented on src/test/java/ServiceNow/PlatformBusinessApps/SSJ/playwright/Features/OWM_Vacancy_Manager.feature
> +  @SSJ-11
Missing @regression or @smoke tags

2024-04-26 17:37 UTC, hamidnesar commented on src/test/java/ServiceNow/PlatformBusinessApps/SSJ/playwright/Features/OWM_Vacancy_Manager.feature
> +  @SSJ-310 @SSJ-158 @SSJ-71
Missing @regression or @smoke tags

2024-04-26 17:37 UTC, hamidnesar commented on src/test/java/ServiceNow/PlatformBusinessApps/SSJ/playwright/Features/OWM_Vacancy_Manager.feature
> +  @SSJ-64  @SSJ-305
Missing @regression or @smoke tags

2024-04-26 17:37 UTC, hamidnesar commented on src/test/java/ServiceNow/PlatformBusinessApps/SSJ/playwright/Features/OWM_Vacancy_Manager.feature
> +  @SSJ-221 @SSJ-100
Missing @regression or @smoke tags

2024-04-26 17:37 UTC, hamidnesar commented on src/test/java/ServiceNow/PlatformBusinessApps/SSJ/playwright/Features/OWM_Vacancy_Manager.feature
> +  @SSJ-1  @SSJ-29 @SSJ-66 @SSJ-62
Missing @regression or @smoke tags

2024-04-26 17:37 UTC, hamidnesar commented on src/test/java/ServiceNow/PlatformBusinessApps/SSJ/playwright/Features/OWM_Vacancy_Manager.feature
> +  @SSJ-160 @SSJ-284
Missing @regression or @smoke tags

2024-04-26 17:37 UTC, hamidnesar commented on src/test/java/ServiceNow/PlatformBusinessApps/SSJ/playwright/Features/OWM_Vacancy_Manager.feature
> +  @SSJ-93 @SSJ-146
Missing @regression or @smoke tags

2024-04-26 17:37 UTC, hamidnesar commented on src/test/java/ServiceNow/PlatformBusinessApps/SSJ/playwright/Pages/Profile_Tab_Page.java
> +    public static String demographicsEditButton = "//span[.='Edit']";
On lines 88 and 103, is the period (.) necessary in //span[**.**=

2024-04-26 18:07 UTC, alenaminsk commented on src/test/java/ServiceNow/PlatformBusinessApps/SSJ/playwright/Features/Applicant Profile.feature
> +  @Regression @Smoke @alenan @APPTRACK-712
Adjusted

2024-04-26 18:07 UTC, alenaminsk commented on src/test/java/ServiceNow/PlatformBusinessApps/SSJ/playwright/Features/OWM_Vacancy_Manager.feature
> +  @SSJ-7  @SSJ-8
These are only feature files, once glue code is developed, @regression tag will be added

2024-04-26 18:08 UTC, alenaminsk commented on src/test/java/ServiceNow/PlatformBusinessApps/SSJ/playwright/Features/OWM_Vacancy_Manager.feature
> +  @SSJ-69
@regression tag will be added after glue code is developed

2024-04-26 18:08 UTC, alenaminsk commented on src/test/java/ServiceNow/PlatformBusinessApps/SSJ/playwright/Features/OWM_Vacancy_Manager.feature
> +  @SSJ-11
@regression tag will be added after glue code is developed

2024-04-26 18:08 UTC, alenaminsk commented on src/test/java/ServiceNow/PlatformBusinessApps/SSJ/playwright/Features/OWM_Vacancy_Manager.feature
> +  @SSJ-310 @SSJ-158 @SSJ-71
@regression tag will be added after glue code is developed

2024-04-26 18:08 UTC, alenaminsk commented on src/test/java/ServiceNow/PlatformBusinessApps/SSJ/playwright/Features/OWM_Vacancy_Manager.feature
> +  @SSJ-160 @SSJ-284
@regression tag will be added after glue code is developed

2024-04-26 18:09 UTC, alenaminsk commented on src/test/java/ServiceNow/PlatformBusinessApps/SSJ/playwright/Features/OWM_Vacancy_Manager.feature
> +  @SSJ-1  @SSJ-29 @SSJ-66 @SSJ-62
@regression tag will be added after glue code is developed

2024-04-26 18:09 UTC, alenaminsk commented on src/test/java/ServiceNow/PlatformBusinessApps/SSJ/playwright/Features/OWM_Vacancy_Manager.feature
> +  @SSJ-93 @SSJ-146
@regression tag will be added after glue code is developed

2024-04-26 18:12 UTC, alenaminsk commented on src/test/java/ServiceNow/PlatformBusinessApps/SSJ/playwright/Pages/Profile_Tab_Page.java
> +    public static String demographicsEditButton = "//span[.='Edit']";
Yes, (.) is a part of a locator

2024-04-29 17:41 UTC, iamdez99 requested changes
Please review changes

2024-04-29 17:50 UTC, matakevin requested changes
Left some comments, please review

2024-04-29 17:50 UTC, matakevin commented on src/test/java/ServiceNow/PlatformBusinessApps/SSJ/playwright/Features/Applicant Profile.feature
Remove the extra space after Diego's tag on line 4

2024-04-29 17:50 UTC, matakevin commented on src/test/java/ServiceNow/PlatformBusinessApps/SSJ/playwright/Features/OWM_Vacancy_Manager.feature
Are these scenarios in progress, a part of smoke or regression?  Please add tags symbolizing state of the scenarios

2024-04-29 17:50 UTC, matakevin commented on src/test/java/ServiceNow/PlatformBusinessApps/SSJ/playwright/Steps/ApplicantProfileSteps.java
There's a couple of steps here that have more than 1 line of code, can you ask Diego if that's okay or if you can add the double clicks in one method or the screenshot line of code also

2024-04-29 17:50 UTC, matakevin commented on src/test/java/ServiceNow/PlatformBusinessApps/SSJ/playwright/StepsImplementation/ApplicantProfileStepsImpl.java
Are there any actions being take for code on lines 21 and 23?

2024-04-29 17:53 UTC, alenaminsk commented on src/test/java/ServiceNow/PlatformBusinessApps/SSJ/playwright/Features/Applicant Profile.feature
removed

2024-04-29 17:56 UTC, alenaminsk commented on src/test/java/ServiceNow/PlatformBusinessApps/SSJ/playwright/Features/OWM_Vacancy_Manager.feature
updated

2024-04-29 18:00 UTC, alenaminsk commented on src/test/java/ServiceNow/PlatformBusinessApps/SSJ/playwright/Steps/ApplicantProfileSteps.java
updated

2024-04-29 18:10 UTC, alenaminsk commented on src/test/java/ServiceNow/PlatformBusinessApps/SSJ/playwright/StepsImplementation/ApplicantProfileStepsImpl.java
removed

2024-04-29 18:10 UTC, alenaminsk commented on src/test/java/ServiceNow/PlatformBusinessApps/SSJ/playwright/StepsImplementation/ApplicantProfileStepsImpl.java
to be developed later

2024-04-29 18:50 UTC, iamdez99 approved these changes
Reviewed and approved

2024-04-29 18:50 UTC, merged