SNOWOBF Test Cases Automation ~Maria
CBIIT/CBIIT-Test-Automation pull request #227
Opened 2024-05-06 17:19 UTC by Mariachaudhry

2024-05-06 19:22 UTC, Mariachaudhry reviewed
reviewed

2024-05-06 19:58 UTC, georgeb79 approved these changes

2024-05-07 14:26 UTC, sarwarahmed1 approved these changes

2024-05-07 14:34 UTC, andreyeve approved these changes

2024-05-07 14:50 UTC, matakevin approved these changes
LGTM

2024-05-08 19:45 UTC, Mariachaudhry reviewed
Reviewed

2024-05-08 21:50 UTC, hamidnesar requested changes
Please review the comments

2024-05-08 21:50 UTC, hamidnesar commented on src/test/java/ServiceNow/PlatformBusinessApps/SNOWOBF/playwright/Pages/NCISP_Portal_Page.java
> +
This is going to create a conflict. This missing element was added to this page class in the latest PR. 
![image](https://github.com/CBIIT/CBIIT-Test-Automation/assets/83662518/74732f49-0202-4f34-9358-dfba5c3acee5)

2024-05-08 21:50 UTC, hamidnesar commented on src/test/java/ServiceNow/PlatformBusinessApps/SNOWOBF/playwright/StepImpl/OBF_NCI_NV_Form_StepImpl.java
> +     * THIS METHOD LOGS INTO TO SIDE DOOR AND IMPERSONATE TO OBF SYSTEMS SUPPORT FULFILLER
You could remove TO

2024-05-08 21:50 UTC, hamidnesar commented on src/test/java/ServiceNow/PlatformBusinessApps/CCT_CHAT_BOT/Playwright/Steps/Example.java
> +}
I see this class added to gitignore file. Do you still need to push this to master?

2024-05-08 21:55 UTC, Mariachaudhry commented on src/test/java/ServiceNow/PlatformBusinessApps/CCT_CHAT_BOT/Playwright/StepImpl/CCT_CHAT_BOT_StepImpl.java
> +     * This Method NAVIGATES TO NATIVE VIEW AND
Resolved

2024-05-08 22:35 UTC, hamidnesar approved these changes

2024-05-09 16:41 UTC, iamdez99 requested changes

2024-05-09 16:41 UTC, iamdez99 commented on src/test/java/ServiceNow/PlatformBusinessApps/CCT_CHAT_BOT/Playwright/Steps/Example.java
You need to uncache this. I see you added this file to the gitignore but you had already committed. Please reach out to me to fix this.

2024-05-09 16:41 UTC, iamdez99 commented on src/test/java/ServiceNow/PlatformBusinessApps/SNOWOBF/playwright/Pages/OBF_Notifications_Page.java
Please add dynamic methods either on the top or bottom, separately so they are not scattered with other locators.

2024-05-09 16:41 UTC, iamdez99 commented on src/test/java/ServiceNow/PlatformBusinessApps/SNOWOBF/playwright/StepImpl/OBF_NCI_NV_Form_StepImpl.java
This class does not have proper javaDoc statements.

2024-05-09 16:41 UTC, iamdez99 commented on src/test/java/ServiceNow/PlatformBusinessApps/SNOWOBF/playwright/StepImpl/OBF_NCI_Portal_Form_StepImpl.java
Some of these methods dont have proper javaDoc statements.

2024-05-09 16:45 UTC, Mariachaudhry commented on src/test/java/ServiceNow/PlatformBusinessApps/SNOWOBF/playwright/Pages/OBF_Notifications_Page.java
updated

2024-05-09 16:51 UTC, Mariachaudhry commented on src/test/java/ServiceNow/PlatformBusinessApps/SNOWOBF/playwright/StepImpl/OBF_Notifications_StepImpl.java
yes since I am calling the previously created method for submitting a ticket which is why it is not used in same method. if it has to be used as a mandatory then I can change the whole method. please let me know and I can implement it.

2024-05-09 17:25 UTC, iamdez99 commented on src/test/java/ServiceNow/PlatformBusinessApps/SNOWOBF/playwright/StepImpl/OBF_Notifications_StepImpl.java
Yes you need to change it, it is not good practice to declare methods with parameters that wont be used

2024-05-09 17:27 UTC, Mariachaudhry commented on src/test/java/ServiceNow/PlatformBusinessApps/SNOWOBF/playwright/StepImpl/OBF_Notifications_StepImpl.java
yes I updated it

2024-05-09 21:44 UTC, iamdez99 requested changes
Reviewed and approved

2024-05-09 21:45 UTC, merged