Automated NERD test case 686 ~Maria
CBIIT/CBIIT-Test-Automation pull request #228
Opened 2024-05-13 18:46 UTC by Mariachaudhry

2024-05-13 18:47 UTC, Mariachaudhry reviewed
Reviewed by me

2024-05-14 15:24 UTC, iamdez99 requested changes

2024-05-14 15:24 UTC, iamdez99 commented on src/test/java/ServiceNow/PlatformBusinessApps/NERD/selenium/Steps/NERD_NCI_StaffMembers_Steps.java
Please add a space between lines 9 and 10
<img width="660" alt="image" src="https://github.com/CBIIT/CBIIT-Test-Automation/assets/45674986/fad37022-8223-4e84-94cc-8e4d5464b436">

2024-05-14 15:28 UTC, iamdez99 approved these changes
Reviewed and approved - juarezds

2024-05-14 15:28 UTC, merged