SSJ - Verification of Vacancy Committee section while creating an NCI Vacancy Positive Flow
CBIIT/CBIIT-Test-Automation pull request #234
Opened 2024-05-21 20:31 UTC by iamdez99

2024-05-21 20:37 UTC, iamdez99 reviewed
reviewed

2024-05-21 21:08 UTC, lfcabrera14 approved these changes
reviewed and approved - cabreralf

2024-05-22 15:30 UTC, alenaminsk commented on src/test/java/ServiceNow/PlatformBusinessApps/SSJ/playwright/Features/OWM_Vacancy_Manager.feature
@iamdez99  Do you possibly need  @playwirght tag for Scenario: Verification of Vacancy Committee section while creating an NCI Vacancy Positive Flow

2024-05-22 15:57 UTC, iamdez99 commented on src/test/java/ServiceNow/PlatformBusinessApps/SSJ/playwright/Features/OWM_Vacancy_Manager.feature
Yes but Luis will actually add all @playwright and @selenium tags to all test cases

2024-05-22 16:20 UTC, alenaminsk commented on src/test/java/ServiceNow/PlatformBusinessApps/SSJ/playwright/Features/OWM_Vacancy_Manager.feature
Thank you Diego

2024-05-22 16:20 UTC, alenaminsk approved these changes

2024-05-22 17:14 UTC, hamidnesar requested changes
Hi, please review the comments. Thanks!

2024-05-22 17:14 UTC, hamidnesar commented on src/test/java/ServiceNow/PlatformBusinessApps/SSJ/SSJ_Runners/SSJ_Regression_Runners.java
> +        "junit:target/cucumber.xml", "rerun:target/failed.txt",
You could remove the "junit: junit:target/cucumber.xml" since it is no longer used

2024-05-22 17:14 UTC, hamidnesar commented on src/test/java/ServiceNow/PlatformBusinessApps/SSJ/SSJ_Runners/SSJ_Progression_Runners.java
>          "junit:target/cucumber.xml", "rerun:target/failed.txt",
You could remove the "junit: junit:target/cucumber.xml" since it is no longer used

2024-05-22 17:14 UTC, hamidnesar commented on src/test/java/ServiceNow/PlatformBusinessApps/SSJ/SSJ_Runners/SSJ_Smoke_Runners.java
> +        "junit:target/cucumber.xml", "rerun:target/failed.txt",
Please remove the "junit: junit:target/cucumber.xml" since it is no longer used

2024-05-22 17:40 UTC, iamdez99 commented on src/test/java/ServiceNow/PlatformBusinessApps/SSJ/SSJ_Runners/SSJ_Smoke_Runners.java
> +        "junit:target/cucumber.xml", "rerun:target/failed.txt",
Got it, great observation, pushed changes, please review.

2024-05-22 17:42 UTC, hamidnesar approved these changes

2024-05-22 19:01 UTC, merged