Added four new test cases for Soccer application.
CBIIT/CBIIT-Test-Automation pull request #240
Opened 2024-06-12 16:16 UTC by sgugulothu

Added four new test cases for Soccer application.

2024-06-12 17:22 UTC, Mariachaudhry requested changes
please review my comments

2024-06-12 17:22 UTC, Mariachaudhry commented on src/test/java/AnalysisTools/Soccer/playwright/StepsImplementation/SoccerStepsImpl.java
Please remove empty lines. 57, 62, 67
format. closing bracket on line 72 should be on next line
same for line 177, brackets should be on next lines

2024-06-12 17:22 UTC, Mariachaudhry commented on src/test/java/AnalysisTools/Soccer/playwright/Utils/Soccer_Constants.java
please remove empty line 66

2024-06-12 17:22 UTC, Mariachaudhry commented on src/test/java/AnalysisTools/ThreeDVizSNP/StepsImplementations/ThreeDVizSNPStepImp.java
please add a line between 20 and 21

2024-06-12 17:22 UTC, Mariachaudhry commented on src/test/java/appsCommon/PlaywrightUtils/Playwright_Common_Utils.java
please remove line 8

2024-06-12 17:33 UTC, Mariachaudhry commented on src/test/java/AnalysisTools/Soccer/playwright/Features/Soccer.feature
please remove empty line # 4

2024-06-12 17:34 UTC, Mariachaudhry commented on src/test/java/AnalysisTools/CometsAnalytics/StepsImplementation/CometsAnalyticsStepImp.java
please remove empty line # 4

2024-06-12 17:46 UTC, iamdez99 approved these changes
Reviewed and approved - juarezds

2024-06-12 18:04 UTC, hamidnesar commented on src/test/java/AnalysisTools/Soccer/playwright/Features/Soccer.feature
> +
Please remove lines 82 - 86

2024-06-12 18:07 UTC, hamidnesar commented on src/test/java/AnalysisTools/Soccer/playwright/Steps/Soccer_Steps.java
> +    }
The step does not match with what is implemented here. The step is meant to verify navigation to FAQ page. However, you are only doing assertion here.

2024-06-12 18:09 UTC, hamidnesar commented on src/test/java/AnalysisTools/Soccer/playwright/Utils/Soccer_Constants.java
> +            * HHS URL
Please format this line by aligning * HHS URL to left

2024-06-12 18:09 UTC, hamidnesar commented on src/test/java/AnalysisTools/Soccer/playwright/Utils/Soccer_Constants.java
> +
Please remove these two lines 67-68

2024-06-12 18:12 UTC, puzikovam2 approved these changes
Reviewed and approved by @puzikovam2

2024-06-12 18:13 UTC, hamidnesar commented on src/test/java/ServiceNow/PlatformBusinessApps/ETracking/Steps/HooksSteps.java
> +
Please remove line 34

2024-06-12 18:13 UTC, sarwarahmed1 requested changes

2024-06-12 18:13 UTC, sarwarahmed1 commented on src/test/java/AnalysisTools/Soccer/playwright/Utils/Soccer_Constants.java
> +
Please remove extra line on 68

2024-06-12 18:13 UTC, sarwarahmed1 commented on src/test/java/ServiceNow/PlatformBusinessApps/NERD/playwright/Features/NCI_Staff_Member_CRS_Knowledge_Base.feature
> +Feature: NCI Staff Member CRS knowledge base portal submission Test Scenarios
Is this an in progress file?

2024-06-12 18:13 UTC, sarwarahmed1 commented on src/test/java/ServiceNow/PlatformBusinessApps/NERD/playwright/Steps/Example.java
> +}
Are we merging example files in the codebase? Also this is incomplete

2024-06-12 18:14 UTC, hamidnesar commented on src/test/java/ServiceNow/PlatformBusinessApps/NERD/selenium/Steps/HooksSteps.java
> +
Please remove the empty line 34

2024-06-12 18:16 UTC, hamidnesar commented on src/test/java/ServiceNow/PlatformBusinessApps/SEER/Steps/HooksSteps.java
> +
Please remove line 34

2024-06-12 18:17 UTC, hamidnesar commented on src/test/java/ServiceNow/ServiceNowRunners/RunNERDRegression1Test.java
> +        , tags="@Regression1"
Remove the number one. _Regression_ vs _Regression1_

2024-06-12 18:18 UTC, hamidnesar commented on src/test/java/ServiceNow/ServiceNowRunners/RunNERDRegression1Test.java
> +        , tags="@Regression1"
Why is the class named as RegressionTest1?

2024-06-12 18:19 UTC, hamidnesar commented on src/test/java/ServiceNow/ServiceNowRunners/RunSSJSmokeTest.java
> +        , "junit:target/cucumber.xml"
Please remove line 8. We no longer use Junit

2024-06-12 18:19 UTC, hamidnesar commented on src/test/java/ServiceNow/ServiceNowRunners/RunSSJRegressionTest.java
> +        , "junit:target/cucumber.xml"
Please remove line 8. We no longer use Junit

2024-06-12 18:20 UTC, sgugulothu commented on src/test/java/ServiceNow/PlatformBusinessApps/NERD/playwright/Features/NCI_Staff_Member_CRS_Knowledge_Base.feature
> +Feature: NCI Staff Member CRS knowledge base portal submission Test Scenarios
This is not my application

2024-06-12 18:20 UTC, hamidnesar commented on src/test/java/ServiceNow/ServiceNowRunners/RunNERDRegression1Test.java
> +@CucumberOptions(plugin= {"html:target/html-reports/cucumber-default-report", "json:target/cucumber.json",
Make sure the HTML has a .html at the end. i.e html:target/html-reports/cucumber-default-report.html

2024-06-12 18:21 UTC, sgugulothu commented on src/test/java/ServiceNow/PlatformBusinessApps/NERD/playwright/Steps/Example.java
> +}
This is also not my application

2024-06-12 18:21 UTC, hamidnesar commented on src/test/java/ServiceNow/ServiceNowRunners/RunNERDRegression1Test.java
> +        "junit:target/cucumber.xml", "rerun:target/failed.txt",
Remove Junit, it is not longer used

2024-06-12 18:21 UTC, hamidnesar commented on src/test/java/ServiceNow/ServiceNowRunners/RunSSJRegressionTest.java
> +@CucumberOptions(plugin= {"html:target/html-reports/cucumber-default-report"
Make sure the HTML has a .html at the end. i.e _html:target/html-reports/cucumber-default-report.html_

2024-06-12 18:21 UTC, hamidnesar commented on src/test/java/ServiceNow/ServiceNowRunners/RunSampleRunnerTest.java
> +@CucumberOptions(plugin = { "html:target/html-reports/cucumber-default-report", "json:target/cucumber.json",
Make sure the HTML has a .html at the end. i.e _html:target/html-reports/cucumber-default-report.html_

2024-06-12 18:22 UTC, hamidnesar commented on src/test/java/ServiceNow/ServiceNowRunners/RunSampleRunnerTest.java
> +        "junit:target/cucumber.xml", "rerun:target/failed.txt",
Please remove Junit, it is no longer used

2024-06-12 18:22 UTC, hamidnesar commented on src/test/java/ServiceNow/ServiceNowRunners/RunSSJProgressionTest.java
> +@CucumberOptions(plugin= {"html:target/html-reports/cucumber-default-report"
Make sure the HTML has a .html at the end. i.e _html:target/html-reports/cucumber-default-report.html_

2024-06-12 18:23 UTC, hamidnesar commented on src/test/java/ServiceNow/ServiceNowRunners/RunSSJProgressionTest.java
> +        , "junit:target/cucumber.xml"
Please remove Junit, it is no longer used

2024-06-12 18:23 UTC, hamidnesar commented on src/test/java/ServiceNow/ServiceNowRunners/RunSSJSmokeTest.java
> +@CucumberOptions(plugin= {"html:target/html-reports/cucumber-default-report"
Make sure the HTML has a .html at the end. i.e _html:target/html-reports/cucumber-default-report.html_

2024-06-12 18:23 UTC, sarwarahmed1 approved these changes
Approved!

2024-06-12 18:24 UTC, hamidnesar commented on src/test/java/ServiceNow/ServiceNowRunners/SEERRunners/Run_SEER_Smoke_Test.java
> +@CucumberOptions(plugin= {"html:target/html-reports/cucumber-default-report", "json:target/cucumber.json",
Make sure the HTML has a .html at the end. i.e _html:target/html-reports/cucumber-default-report.html_

2024-06-12 18:24 UTC, hamidnesar commented on src/test/java/ServiceNow/ServiceNowRunners/SEERRunners/Run_SEER_Smoke_Test.java
> +		"junit:target/cucumber.xml", "rerun:target/failed.txt",
Please remove Junit

2024-06-12 18:27 UTC, hamidnesar commented on src/test/java/AnalysisTools/Soccer/playwright/Steps/Soccer_Steps.java
> +    }
There is no Click action performed here but only Assertion. Please either implement the Click action or rewrite the step to match the implementation. You could say: _User verifies the policies link_

2024-06-12 18:28 UTC, hamidnesar commented on src/test/java/AnalysisTools/Soccer/playwright/Steps/Soccer_Steps.java
> +    }
There is no Click action performed here but only Assertion. Please either implement the Click action or rewrite the step to match the implementation

2024-06-12 18:29 UTC, hamidnesar commented on src/test/java/AnalysisTools/Soccer/playwright/Steps/Soccer_Steps.java
> +    }
There is no Click action performed here but only Assertion. Please either implement the Click action or rewrite the step to match the implementation

2024-06-12 18:29 UTC, hamidnesar commented on src/test/java/AnalysisTools/Soccer/playwright/Steps/Soccer_Steps.java
> +    }
There is no Click action performed here but only Assertion. Please either implement the Click action or rewrite the step to match the implementation

2024-06-12 18:30 UTC, hamidnesar commented on src/test/java/AnalysisTools/Soccer/playwright/Steps/Soccer_Steps.java
> +    }
There is no Click action performed here but only Assertion. Please either implement the Click action or rewrite the step to match the implementation

2024-06-12 18:30 UTC, hamidnesar commented on src/test/java/AnalysisTools/Soccer/playwright/Steps/Soccer_Steps.java
> +    }
There is no Click action performed here but only Assertion. Please either implement the Click action or rewrite the step to match the implementation

2024-06-12 18:30 UTC, hamidnesar commented on src/test/java/AnalysisTools/Soccer/playwright/Steps/Soccer_Steps.java
> +    }
There is no Click action performed here but only Assertion. Please either implement the Click action or rewrite the step to match the implementation

2024-06-12 18:59 UTC, sgugulothu commented on src/test/java/AnalysisTools/Soccer/playwright/Utils/Soccer_Constants.java
> +
I dont see these lines

2024-06-12 19:02 UTC, sgugulothu commented on src/test/java/ServiceNow/PlatformBusinessApps/ETracking/Steps/HooksSteps.java
> +
This is not my application

2024-06-12 19:03 UTC, sgugulothu commented on src/test/java/ServiceNow/PlatformBusinessApps/ETracking/Steps/HooksSteps.java
> +
This is not my application

2024-06-12 19:03 UTC, sgugulothu commented on src/test/java/ServiceNow/PlatformBusinessApps/NERD/selenium/Steps/HooksSteps.java
> +
This is not my application

2024-06-12 19:03 UTC, sgugulothu commented on src/test/java/ServiceNow/PlatformBusinessApps/SEER/Steps/HooksSteps.java
> +
This is not my application

2024-06-12 19:04 UTC, sgugulothu commented on src/test/java/ServiceNow/ServiceNowRunners/RunNERDRegression1Test.java
> +        , tags="@Regression1"
This is not my application

2024-06-12 19:04 UTC, sgugulothu commented on src/test/java/ServiceNow/ServiceNowRunners/RunSSJSmokeTest.java
> +        , "junit:target/cucumber.xml"
This is not my application

2024-06-12 19:04 UTC, sgugulothu commented on src/test/java/ServiceNow/ServiceNowRunners/RunNERDRegression1Test.java
> +@CucumberOptions(plugin= {"html:target/html-reports/cucumber-default-report", "json:target/cucumber.json",
This is not my application

2024-06-12 19:04 UTC, sgugulothu commented on src/test/java/ServiceNow/ServiceNowRunners/RunNERDRegression1Test.java
> +        "junit:target/cucumber.xml", "rerun:target/failed.txt",
This is not my application

2024-06-12 19:04 UTC, sgugulothu commented on src/test/java/ServiceNow/ServiceNowRunners/RunSSJRegressionTest.java
> +@CucumberOptions(plugin= {"html:target/html-reports/cucumber-default-report"
This is not my application

2024-06-12 19:04 UTC, sgugulothu commented on src/test/java/ServiceNow/ServiceNowRunners/RunSampleRunnerTest.java
> +@CucumberOptions(plugin = { "html:target/html-reports/cucumber-default-report", "json:target/cucumber.json",
This is not my application

2024-06-12 19:05 UTC, sgugulothu commented on src/test/java/ServiceNow/ServiceNowRunners/RunSampleRunnerTest.java
> +        "junit:target/cucumber.xml", "rerun:target/failed.txt",
This is not my application

2024-06-12 19:05 UTC, sgugulothu commented on src/test/java/ServiceNow/ServiceNowRunners/RunSSJProgressionTest.java
> +@CucumberOptions(plugin= {"html:target/html-reports/cucumber-default-report"
This is not my application

2024-06-12 19:05 UTC, sgugulothu commented on src/test/java/ServiceNow/ServiceNowRunners/RunSSJProgressionTest.java
> +        , "junit:target/cucumber.xml"
This is not my application

2024-06-12 19:05 UTC, sgugulothu commented on src/test/java/ServiceNow/ServiceNowRunners/RunSSJSmokeTest.java
> +@CucumberOptions(plugin= {"html:target/html-reports/cucumber-default-report"
This is not my application

2024-06-12 19:05 UTC, sgugulothu commented on src/test/java/ServiceNow/ServiceNowRunners/SEERRunners/Run_SEER_Smoke_Test.java
> +@CucumberOptions(plugin= {"html:target/html-reports/cucumber-default-report", "json:target/cucumber.json",
This is not my application

2024-06-12 19:05 UTC, sgugulothu commented on src/test/java/ServiceNow/ServiceNowRunners/SEERRunners/Run_SEER_Smoke_Test.java
> +		"junit:target/cucumber.xml", "rerun:target/failed.txt",
This is not my application

2024-06-12 19:05 UTC, sgugulothu commented on src/test/java/AnalysisTools/Soccer/playwright/Steps/Soccer_Steps.java
> +    }
This is not my application

2024-06-12 19:20 UTC, sgugulothu commented on src/test/java/AnalysisTools/Soccer/playwright/Steps/Soccer_Steps.java
> +    }
Actually I am clicking on the link and then verifying the opened url used in the playwright common utils. And so implementation is matching with the step.

2024-06-12 19:29 UTC, sgugulothu commented on src/test/java/AnalysisTools/Soccer/playwright/Steps/Soccer_Steps.java
> +    }
Actually i am clicking on the url and and then validating it after it is opening in the new tab using the common method used in the playwright common utils. And so implementation is as per the defined step.

2024-06-12 19:29 UTC, sgugulothu commented on src/test/java/AnalysisTools/Soccer/playwright/Steps/Soccer_Steps.java
> +    }
Actually i am clicking on the url and and then validating it after it is opening in the new tab using the common method used in the playwright common utils. And so implementation is as per the defined step.

2024-06-12 19:29 UTC, sgugulothu commented on src/test/java/AnalysisTools/Soccer/playwright/Steps/Soccer_Steps.java
> +    }
Actually i am clicking on the url and and then validating it after it is opening in the new tab using the common method used in the playwright common utils. And so implementation is as per the defined step.

2024-06-12 19:29 UTC, sgugulothu commented on src/test/java/AnalysisTools/Soccer/playwright/Steps/Soccer_Steps.java
> +    }
Actually i am clicking on the url and and then validating it after it is opening in the new tab using the common method used in the playwright common utils. And so implementation is as per the defined step.

2024-06-12 19:29 UTC, sgugulothu commented on src/test/java/AnalysisTools/Soccer/playwright/Steps/Soccer_Steps.java
> +    }
Actually i am clicking on the url and and then validating it after it is opening in the new tab using the common method used in the playwright common utils. And so implementation is as per the defined step.

2024-06-12 20:53 UTC, Mariachaudhry approved these changes

2024-06-13 15:14 UTC, sgugulothu commented on src/test/java/AnalysisTools/Soccer/playwright/Steps/Soccer_Steps.java
> +    }
I changed the name

2024-06-13 16:22 UTC, hamidnesar requested changes
Please review the comments

2024-06-13 16:22 UTC, hamidnesar commented on src/test/java/AnalysisTools/NIFESubmit/playwright/Features/NIFESubmit.feature
> +
Please remove line 36-37

2024-06-13 16:22 UTC, hamidnesar commented on src/test/java/AnalysisTools/NIFESubmit/playwright/Features/NIFESubmit.feature
> +
Please remove line 27

2024-06-13 16:22 UTC, hamidnesar commented on src/test/java/AnalysisTools/NIFESubmit/playwright/Features/NIFESubmit.feature
> +
Please remove line 17

2024-06-13 16:22 UTC, hamidnesar commented on src/test/java/AnalysisTools/NIFESubmit/playwright/Features/NIFESubmit.feature
> +
Please remove line 9

2024-06-13 16:22 UTC, hamidnesar commented on src/test/java/AnalysisTools/NIFESubmit/playwright/Steps/NIFESubmit_Steps.java
> +
Please remove line 13

2024-06-13 16:22 UTC, hamidnesar commented on src/test/java/AnalysisTools/NIFESubmit/playwright/Steps/NIFESubmit_Steps.java
> +
Please remove line 20

2024-06-13 16:22 UTC, hamidnesar commented on src/test/java/AnalysisTools/NIFESubmit/playwright/Steps/NIFESubmit_Steps.java
> +
Please remove line 23

2024-06-13 16:22 UTC, hamidnesar commented on src/test/java/AnalysisTools/NIFESubmit/playwright/Steps/NIFESubmit_Steps.java
> +    }
Add an empty line between the closing bracket and the following step

2024-06-13 16:22 UTC, hamidnesar commented on src/test/java/AnalysisTools/NIFESubmit/playwright/Steps/NIFESubmit_Steps.java
> +
Please remove lines 99-100

2024-06-13 16:22 UTC, hamidnesar commented on src/test/java/AnalysisTools/NIFESubmit/playwright/StepsImplementation/NIFESubmitStepsImpl.java
> +
Please remove line 13

2024-06-13 16:22 UTC, hamidnesar commented on src/test/java/AnalysisTools/NIFESubmit/playwright/StepsImplementation/NIFESubmitStepsImpl.java
> +
Please remove line 15

2024-06-13 16:22 UTC, hamidnesar commented on src/test/java/AnalysisTools/NIFESubmit/playwright/StepsImplementation/NIFESubmitStepsImpl.java
> +
Please remove line 26

2024-06-13 16:22 UTC, hamidnesar commented on src/test/java/AnalysisTools/NIFESubmit/playwright/StepsImplementation/NIFESubmitStepsImpl.java
> +
Please remove line 34

2024-06-13 16:22 UTC, hamidnesar commented on src/test/java/AnalysisTools/NIFESubmit/playwright/StepsImplementation/NIFESubmitStepsImpl.java
> +
Please remove line 48

2024-06-13 16:22 UTC, hamidnesar commented on src/test/java/AnalysisTools/NIFESubmit/playwright/StepsImplementation/NIFESubmitStepsImpl.java
> +
Please remove line 56

2024-06-13 16:22 UTC, hamidnesar commented on src/test/java/AnalysisTools/NIFESubmit/playwright/StepsImplementation/NIFESubmitStepsImpl.java
> +
Please remove line 66

2024-06-13 16:22 UTC, hamidnesar commented on src/test/java/AnalysisTools/NIFESubmit/playwright/StepsImplementation/NIFESubmitStepsImpl.java
> +
Please remove line 76

2024-06-13 16:22 UTC, hamidnesar commented on src/test/java/AnalysisTools/NIFESubmit/playwright/StepsImplementation/NIFESubmitStepsImpl.java
> +
Please remove line 87

2024-06-13 16:22 UTC, hamidnesar commented on src/test/java/AnalysisTools/NIFESubmit/playwright/StepsImplementation/NIFESubmitStepsImpl.java
> +
Please remove line 89, 90, 91

2024-06-13 16:22 UTC, hamidnesar commented on src/test/java/AnalysisTools/NIFESubmit/playwright/Utils/NIFESubmit_Constants.java
> +
Please remove line 42

2024-06-13 16:22 UTC, hamidnesar commented on src/test/java/AnalysisTools/NIFESubmit/playwright/Utils/NIFESubmit_Constants.java
> +
Please remove line 48

2024-06-13 17:44 UTC, hamidnesar requested changes
Please address the comments. Thank you!

2024-06-13 17:44 UTC, hamidnesar commented on src/test/java/AnalysisTools/NIFESubmit/playwright/StepsImplementation/NIFESubmitStepsImpl.java
> +    public static void verifyNCSLink() {
Change NCS to NCI. 
Rename the method to _verifyNCILink_

2024-06-13 17:44 UTC, hamidnesar commented on src/test/java/AnalysisTools/Soccer/playwright/Utils/Soccer_Constants.java
> +            * HHS URL
Please shift * HHS to the left

2024-06-13 17:54 UTC, hamidnesar commented on src/test/java/AnalysisTools/NIFESubmit/playwright/Features/NIFESubmit.feature
> +    Then User clicks on NCS link and verify it in NIFE
Please change NCS to NCI

2024-06-13 18:13 UTC, hamidnesar approved these changes
Reviewed and approved!

2024-06-13 18:41 UTC, merged