Created FanconiSurvey test cases using playwright
CBIIT/CBIIT-Test-Automation pull request #241
Opened 2024-06-13 15:11 UTC by sonika-nih

2024-06-14 19:48 UTC, iamdez99 requested changes

2024-06-14 19:48 UTC, iamdez99 commented on src/test/java/ServiceNow/CHARMS/FanconiSurvey/playwright/Features/FanconiSurvey.feature
Scenario on line 6 is missing User Story ID, Regression tag, playwright or selenium tag. If its in progress please tag it @IN_PROGRESS

2024-06-14 19:48 UTC, iamdez99 commented on pom.xml
What is the purpose of the annotations dependency from jetbrains? You would have to let the team know of any changes in important files like in pom.xml

2024-06-14 19:48 UTC, iamdez99 commented on src/test/java/ServiceNow/CHARMS/FanconiSurvey/playwright/Pages/FanconiSurveyLoginPage.java
Import on line 3 is never used. Please remove.

2024-06-14 19:48 UTC, iamdez99 commented on src/test/java/ServiceNow/CHARMS/FanconiSurvey/playwright/Runners/Run_CHARMS_FanconiSurvey_Regression_Test.java
Please make a side not that we would have to come back and update this runners class at a later time.

2024-06-14 19:48 UTC, iamdez99 commented on src/test/java/ServiceNow/CHARMS/FanconiSurvey/playwright/Steps/PlaywrightHooks.java
Please delete this hooks class. We need to configure runners classes to use the global hooks class.

2024-06-14 19:48 UTC, iamdez99 commented on src/test/java/ServiceNow/CHARMS/FanconiSurvey/playwright/StepsImplementation/FanconiSurveyStepsImpl.java
Please format this class and great job on writing clean code.

2024-06-14 19:48 UTC, iamdez99 commented on src/test/java/ServiceNow/CHARMS/Features/FHQ/FHQSubmission.feature
Scenarios are missing selenium or playwright tags as well as user story IDs.

2024-06-14 19:48 UTC, iamdez99 commented on src/test/java/ServiceNow/CHARMS/Features/FanconiStudy/FanconiEligibilityQuestionnaire.feature
Please add user story IDs

2024-06-14 19:48 UTC, iamdez99 commented on src/test/java/ServiceNow/CHARMS/Features/RasopathyStudy/RAS Screener Submissions.feature
Please add selenium or playwright tag and user story ID.

2024-06-17 13:40 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/FanconiSurvey/playwright/Features/FanconiSurvey.feature
Done

2024-06-17 13:45 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/FanconiSurvey/playwright/Pages/FanconiSurveyLoginPage.java
Done

2024-06-17 13:48 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/FanconiSurvey/playwright/Steps/PlaywrightHooks.java
Done

2024-06-17 13:49 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/FanconiSurvey/playwright/StepsImplementation/FanconiSurveyStepsImpl.java
Done

2024-06-17 14:32 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/Features/FanconiStudy/FanconiEligibilityQuestionnaire.feature
Done

2024-06-17 14:55 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/Features/RasopathyStudy/RAS Screener Submissions.feature
Added  user story ID and @selenium tags in FHQ , Fanconi screener and RAS

2024-06-18 14:39 UTC, hamidnesar requested changes
Hi, please review the comments. Thanks!

2024-06-18 14:39 UTC, hamidnesar commented on src/test/java/ServiceNow/CHARMS/FanconiSurvey/playwright/Pages/FanconiSurveyLoginPage.java
> +}
All the page elements are missing comments. Please see the below example:
![image](https://github.com/CBIIT/CBIIT-Test-Automation/assets/83662518/2f7a1e09-a4eb-4587-a761-89efe30e1681)

2024-06-18 14:39 UTC, hamidnesar commented on src/test/java/ServiceNow/CHARMS/FanconiSurvey/playwright/Pages/FanconiSurveyLoginPage.java
> +}
- It would have been great to follow the Camel case for naming the page elements. 
- Is there to need to declare them all as Final?

2024-06-18 14:39 UTC, hamidnesar commented on src/test/java/ServiceNow/CHARMS/FanconiSurvey/playwright/Runners/Run_CHARMS_FanconiSurvey_Regression_Test.java
> +		"junit:target/cucumber.xml", "rerun:target/failed.txt",
Please remove "junit:target/cucumber.xml" as it is no longer used

2024-06-18 14:39 UTC, hamidnesar commented on src/test/java/ServiceNow/CHARMS/FanconiSurvey/playwright/StepsImplementation/FanconiSurveyStepsImpl.java
> +    public static void backgroundInformationSection() {
There is missing a comment at the beginning of this method, which describes the method's functionality, parameters, parameter types, and return types if applicable.

2024-06-18 14:39 UTC, hamidnesar commented on src/test/java/ServiceNow/CHARMS/FanconiSurvey/playwright/StepsImplementation/FanconiSurveyStepsImpl.java
> +
There is missing a comment at the beginning of this method, which describes the method's functionality, parameters, parameter types, and return types if applicable.

2024-06-18 14:39 UTC, hamidnesar commented on src/test/java/ServiceNow/CHARMS/Features/FHQ/FHQSubmission.feature
> +   @jains @FHQSubmissionInPortal  @CP2-562  @CP2-930  @CP2-559 @Regression @selenium
There are double spaces between some of the tags

2024-06-18 14:39 UTC, hamidnesar commented on src/test/java/ServiceNow/CHARMS/Features/FHQ/FHQSubmission.feature
There are double spaces between most of the tags

2024-06-18 14:39 UTC, hamidnesar commented on src/test/java/ServiceNow/CHARMS/Runners/RunCHARMSSmokeTest.java
>  @CucumberOptions(plugin = { "html:target/html-reports/cucumber-default-report", "json:target/cucumber.json",
Please add .html at the end of "html:target/html-reports/cucumber-default-report"

2024-06-18 14:39 UTC, hamidnesar commented on src/test/java/ServiceNow/CHARMS/Runners/RunCHARMSSmokeTest.java
>  		"junit:target/cucumber.xml", "rerun:target/failed.txt",
Please remove "junit:target/cucumber.xml"

2024-06-18 14:39 UTC, hamidnesar commented on src/test/java/ServiceNow/CHARMS/Runners/RunCHARMSRegressionTest.java
> +package ServiceNow.CHARMS.Runners;
- Please add .html at the end of "html:target/html-reports/cucumber-default-report"
- Please remove "junit:target/cucumber.xml"

2024-06-18 14:39 UTC, hamidnesar commented on src/test/java/ServiceNow/CHARMS/Runners/RunCHARMSTestAccountResetForFanconi.java
> +package ServiceNow.CHARMS.Runners;
- Please add .html at the end of "html:target/html-reports/cucumber-default-report"
- Please remove "junit:target/cucumber.xml"

2024-06-18 14:39 UTC, hamidnesar commented on src/test/java/ServiceNow/CHARMS/Runners/RunCHARMSTestAccountResetTest.java
> +package ServiceNow.CHARMS.Runners;
- Please add .html at the end of "html:target/html-reports/cucumber-default-report"
- Please remove "junit:target/cucumber.xml"

2024-06-18 14:39 UTC, hamidnesar commented on src/test/java/ServiceNow/CHARMS/Runners/Run_CHARMS_Fanconi_Regression_Test.java
> +package ServiceNow.CHARMS.Runners;
- Please add .html at the end of "html:target/html-reports/cucumber-default-report"
- Please remove "junit:target/cucumber.xml"

2024-06-18 14:39 UTC, hamidnesar commented on src/test/java/ServiceNow/CHARMS/Runners/Run_CHARMS_Fanconi_Smoke_Test.java
> +		"junit:target/cucumber.xml", "rerun:target/failed.txt",
Please remove "junit:target/cucumber.xml"

2024-06-18 14:39 UTC, hamidnesar commented on src/test/java/ServiceNow/CHARMS/Runners/RunCHARMSTestAccountResetTest.java
>  import io.cucumber.junit.CucumberOptions;
Please replace Junit import with TestNG. i.e: import io.cucumber.testng.CucumberOptions;

2024-06-18 14:39 UTC, hamidnesar commented on src/test/java/ServiceNow/CHARMS/Runners/RunCHARMSFHQRegressionTest.java
> +package ServiceNow.CHARMS.Runners;
Please add .html at the end of "html:target/html-reports/cucumber-default-report"
Please remove "junit:target/cucumber.xml"

2024-06-18 14:39 UTC, hamidnesar commented on src/test/java/ServiceNow/CHARMS/Runners/RunCHARMSRasRegressionTest.java
> +package ServiceNow.CHARMS.Runners;
- Please add .html at the end of "html:target/html-reports/cucumber-default-report"
- Please remove "junit:target/cucumber.xml"

2024-06-18 14:39 UTC, hamidnesar commented on src/test/java/ServiceNow/CHARMS/Runners/Run_CHARMS_Progression_Test.java
- Please add .html at the end of "html:target/html-reports/cucumber-default-report"
- Please remove "junit:target/cucumber.xml"

2024-06-18 14:39 UTC, hamidnesar commented on src/test/java/ServiceNow/CHARMS/Runners/Run_CHARMS_RAS_Study_RegressionTest.java
- Please add .html at the end of "html:target/html-reports/cucumber-default-report"
- Please remove "junit:target/cucumber.xml"

2024-06-18 14:44 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/Features/FHQ/FHQSubmission.feature
DONE

2024-06-18 14:48 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/FanconiSurvey/playwright/Features/FanconiSurvey.feature
> +  @jains @BackgroundInformation  @CP2-3178 @CP2-3133 @playwright @Regression
DONE

2024-06-18 14:57 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/FanconiSurvey/playwright/Runners/Run_CHARMS_FanconiSurvey_Regression_Test.java
> +		"junit:target/cucumber.xml", "rerun:target/failed.txt",
Removed.

2024-06-18 15:01 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/FanconiSurvey/playwright/StepsImplementation/FanconiSurveyStepsImpl.java
> +    public static void backgroundInformationSection() {
Done

2024-06-18 15:20 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/FanconiSurvey/playwright/StepsImplementation/FanconiSurveyStepsImpl.java
> +
Added the comments for the method

2024-06-18 15:34 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/Features/FHQ/FHQSubmission.feature
> +   @jains @FHQSubmissionInPortal  @CP2-562  @CP2-930  @CP2-559 @Regression @selenium
Removed double spaces between the tags

2024-06-18 15:41 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/Features/FHQ/FHQSubmission.feature
Removed double spaces between the tags

2024-06-18 15:43 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/Runners/RunCHARMSSmokeTest.java
>  @CucumberOptions(plugin = { "html:target/html-reports/cucumber-default-report", "json:target/cucumber.json",
Added .html at the end of "html:target/html-reports/cucumber-default-report

2024-06-18 15:44 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/Runners/RunCHARMSSmokeTest.java
>  		"junit:target/cucumber.xml", "rerun:target/failed.txt",
Removed "junit:target/cucumber.xml

2024-06-18 15:45 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/Runners/RunCHARMSTestAccountResetForFanconi.java
> +package ServiceNow.CHARMS.Runners;
Done

2024-06-18 15:46 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/Runners/Run_CHARMS_Fanconi_Smoke_Test.java
> +		"junit:target/cucumber.xml", "rerun:target/failed.txt",
Done

2024-06-18 15:47 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/Runners/RunCHARMSTestAccountResetTest.java
>  import io.cucumber.junit.CucumberOptions;
Done

2024-06-18 15:50 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/Runners/RunCHARMSFHQRegressionTest.java
> +package ServiceNow.CHARMS.Runners;
Done

2024-06-18 15:52 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/Runners/RunCHARMSRasRegressionTest.java
> +package ServiceNow.CHARMS.Runners;
Done

2024-06-18 15:53 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/Runners/Run_CHARMS_Progression_Test.java
Done

2024-06-18 15:55 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/Runners/Run_CHARMS_RAS_Study_RegressionTest.java
Done

2024-06-18 16:29 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/FanconiSurvey/playwright/Pages/FanconiSurveyLoginPage.java
> +}
Hey, I talked to Diego and as per his instructions I will be adding the comments going forward but for this time it can be one slide with no comments.

2024-06-18 17:03 UTC, alenaminsk approved these changes

2024-06-18 17:19 UTC, Mariachaudhry approved these changes
LGTM!

2024-06-18 17:27 UTC, hamidnesar requested changes
Hi, please review the comments in the below classes:

- src/test/java/ServiceNow/CHARMS/FanconiSurvey/playwright/Features/FanconiSurvey.feature
- src/test/java/ServiceNow/CHARMS/Runners/Run_CHARMS_RAS_Study_RegressionTest.java

2024-06-18 17:27 UTC, hamidnesar commented on src/test/java/ServiceNow/CHARMS/Runners/Run_CHARMS_Fanconi_Smoke_Test.java
> +dryRun = false
Please format lines 9 - 12.
![image](https://github.com/CBIIT/CBIIT-Test-Automation/assets/83662518/dcb6fcb5-e35a-4797-b4fc-989dd952e93a)

2024-06-18 17:27 UTC, hamidnesar commented on src/test/java/ServiceNow/CHARMS/Runners/Run_CHARMS_RAS_Study_RegressionTest.java
> +		tags = "@RAS_Study_Regression",
This needs to be tagged as @Regression

2024-06-18 17:27 UTC, hamidnesar commented on src/test/java/ServiceNow/CHARMS/FanconiSurvey/playwright/Features/FanconiSurvey.feature
> +
lines 9-12

2024-06-18 17:41 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/Runners/Run_CHARMS_RAS_Study_RegressionTest.java
> +		tags = "@RAS_Study_Regression",
Done

2024-06-18 17:50 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/Runners/Run_CHARMS_Fanconi_Smoke_Test.java
> +dryRun = false
Done

2024-06-18 17:52 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/FanconiSurvey/playwright/Features/FanconiSurvey.feature
> +
Done

2024-06-18 18:09 UTC, sarwarahmed1 approved these changes

2024-06-18 18:31 UTC, hamidnesar approved these changes
Looks Good! 
Reviewed and approved.

2024-06-18 19:32 UTC, matakevin approved these changes
LGTM

2024-06-18 21:41 UTC, iamdez99 approved these changes
Reviewed and approved - juarezds

2024-06-18 21:41 UTC, merged