[PLATFORM BUSINESS APPS] -  SEER ODS Regression updates
CBIIT/CBIIT-Test-Automation pull request #242
Opened 2024-06-13 19:25 UTC by Mariachaudhry

2024-06-13 19:35 UTC, Mariachaudhry reviewed
Reviewed by Maria

2024-06-14 16:09 UTC, andreyeve approved these changes

2024-06-14 16:33 UTC, matakevin requested changes
Left some comments on a feature file for extra spaces but aside from that it looks good.

2024-06-14 16:33 UTC, matakevin commented on src/test/java/ServiceNow/PlatformBusinessApps/NERD/Features/NCI Staff Members.feature
> +  @NERDSNOW-690 @chaudhryma  @selenium @In-Progress
delete extra space between your name tag and the selenium tag

2024-06-14 16:33 UTC, matakevin commented on src/test/java/ServiceNow/PlatformBusinessApps/NERD/Features/NCI Staff Members.feature
> +  @NERDSNOW-689 @chaudhryma  @Regression @selenium
delete extra space between your name tag and the Regression tag

2024-06-14 17:10 UTC, matakevin approved these changes
LGTM

2024-06-14 17:23 UTC, hamidnesar requested changes
Hi, please review the comments.

2024-06-14 17:23 UTC, hamidnesar commented on src/test/java/ServiceNow/PlatformBusinessApps/SEER/SEER_Runners/Run_SEER_Progression_Test.java
> +@CucumberOptions(plugin = {"html:target/html-reports/cucumber-default-report",
Please add .html for the html report. i.e: _"html:target/html-reports/cucumber-default-report.html"_

2024-06-14 17:23 UTC, hamidnesar commented on src/test/java/ServiceNow/PlatformBusinessApps/SEER/SEER_Runners/Run_SEER_Regression_Test.java
> +@CucumberOptions(plugin = {"html:target/html-reports/cucumber-default-report",
Please add .html for the html report. i.e: "html:target/html-reports/cucumber-default-report.html"

2024-06-14 18:01 UTC, hamidnesar approved these changes
Reviewed and approved.

2024-06-14 18:20 UTC, merged