Jains18
CBIIT/CBIIT-Test-Automation pull request #247
Opened 2024-06-26 19:35 UTC by sonika-nih

Updated the Fanconi test cases for Smoke run and reset test accounts script to reset Charms Accounts. 
Added a new Demographic section Test case for the Fanconi Survey using Playwright.

2024-06-26 21:31 UTC, hamidnesar requested changes
Hi, please review the comments, specifically in src/test/java/ServiceNow/CHARMS/StepsImplementation/FanconiEligibilityQuestionnaireStepsImpl.java

2024-06-26 21:31 UTC, hamidnesar commented on src/test/java/ServiceNow/CHARMS/StepsImplementation/FanconiEligibilityQuestionnaireStepsImpl.java
> +    /*****************************************************************/
Please add a space between lines 259 and 260

2024-06-26 21:31 UTC, hamidnesar commented on src/test/java/ServiceNow/CHARMS/StepsImplementation/FanconiEligibilityQuestionnaireStepsImpl.java
> +    /*****************************************************************/
Please add a space between lines 270 and 271

2024-06-26 21:31 UTC, hamidnesar commented on src/test/java/ServiceNow/CHARMS/StepsImplementation/FanconiEligibilityQuestionnaireStepsImpl.java
> +    /* Method to submit the phone details */
Please add a space between lines 280 and 281

2024-06-26 21:31 UTC, hamidnesar commented on src/test/java/ServiceNow/CHARMS/StepsImplementation/FanconiEligibilityQuestionnaireStepsImpl.java
> +    /* Method to submit the Ethnicity details */
Please add a space between lines 301 and 302

2024-06-26 21:31 UTC, hamidnesar commented on src/test/java/ServiceNow/CHARMS/StepsImplementation/FanconiEligibilityQuestionnaireStepsImpl.java
> +    /*****************************************************************/
Please add a space between the methods

2024-06-26 21:31 UTC, hamidnesar commented on src/test/java/ServiceNow/CHARMS/StepsImplementation/FanconiEligibilityQuestionnaireStepsImpl.java
> +    /*****************************************************************/
Please add a space between the methods

2024-06-26 21:31 UTC, hamidnesar commented on src/test/java/ServiceNow/CHARMS/StepsImplementation/FanconiEligibilityQuestionnaireStepsImpl.java
> +    /*****************************************************************/
Please add a space between the methods

2024-06-26 21:31 UTC, hamidnesar commented on src/test/java/ServiceNow/CHARMS/StepsImplementation/FanconiEligibilityQuestionnaireStepsImpl.java
> +    /*****************************************************************/
Please add a space between the methods

2024-06-26 21:31 UTC, hamidnesar commented on src/test/java/ServiceNow/CHARMS/StepsImplementation/FanconiEligibilityQuestionnaireStepsImpl.java
> +    /*****************************************************************/
Please add a space between the methods

2024-06-26 21:31 UTC, hamidnesar commented on src/test/java/ServiceNow/CHARMS/StepsImplementation/FanconiEligibilityQuestionnaireStepsImpl.java
> +    /*****************************************************************/
Please add a space between the methods

2024-06-26 21:31 UTC, hamidnesar commented on src/test/java/ServiceNow/CHARMS/StepsImplementation/FanconiEligibilityQuestionnaireStepsImpl.java
> +    /*****************************************************************/
Please add a space between the methods

2024-06-26 21:31 UTC, hamidnesar commented on src/test/java/ServiceNow/CHARMS/StepsImplementation/FanconiEligibilityQuestionnaireStepsImpl.java
> +    /*****************************************************************/
Please add a space between the methods

2024-06-26 21:31 UTC, hamidnesar commented on src/test/java/ServiceNow/CHARMS/StepsImplementation/FanconiEligibilityQuestionnaireStepsImpl.java
> +    /*****************************************************************/
Please add a space between the methods

2024-06-26 21:31 UTC, hamidnesar commented on src/test/java/ServiceNow/CHARMS/StepsImplementation/FanconiEligibilityQuestionnaireStepsImpl.java
> +    /*****************************************************************/
Please add a space between the methods

2024-06-26 21:31 UTC, hamidnesar commented on src/test/java/ServiceNow/CHARMS/StepsImplementation/FanconiEligibilityQuestionnaireStepsImpl.java
> +    /*****************************************************************/
Please add a space between the methods

2024-06-26 21:31 UTC, hamidnesar commented on src/test/java/ServiceNow/CHARMS/StepsImplementation/FanconiEligibilityQuestionnaireStepsImpl.java
> +    /*****************************************************************/
Please add a space between the methods

2024-06-26 21:31 UTC, hamidnesar commented on src/test/java/ServiceNow/CHARMS/StepsImplementation/FanconiEligibilityQuestionnaireStepsImpl.java
> +    /*****************************************************************/
Please add a space between the methods

2024-06-26 21:31 UTC, hamidnesar commented on src/test/java/ServiceNow/CHARMS/StepsImplementation/FanconiEligibilityQuestionnaireStepsImpl.java
> +    /*****************************************************************/
Please add a space between the methods

2024-06-26 21:31 UTC, hamidnesar commented on src/test/java/ServiceNow/CHARMS/StepsImplementation/FanconiEligibilityQuestionnaireStepsImpl.java
> +    /*****************************************************************/
Please add a space between the methods

2024-06-26 21:31 UTC, hamidnesar commented on src/test/java/ServiceNow/CHARMS/StepsImplementation/FanconiEligibilityQuestionnaireStepsImpl.java
> +    /*****************************************************************/
Please add a space between the methods

2024-06-26 21:31 UTC, hamidnesar commented on src/test/java/ServiceNow/CHARMS/StepsImplementation/FanconiEligibilityQuestionnaireStepsImpl.java
> +    /*****************************************************************/
Please add a space between the methods

2024-06-26 21:31 UTC, hamidnesar commented on src/test/java/ServiceNow/CHARMS/StepsImplementation/FanconiEligibilityQuestionnaireStepsImpl.java
> +    /*****************************************************************/
Please add a space between the methods

2024-06-26 21:31 UTC, hamidnesar commented on src/test/java/ServiceNow/CHARMS/StepsImplementation/FanconiEligibilityQuestionnaireStepsImpl.java
> +    /*****************************************************************/
Please add a space between the methods

2024-06-26 21:31 UTC, hamidnesar commented on src/test/java/ServiceNow/CHARMS/StepsImplementation/FanconiEligibilityQuestionnaireStepsImpl.java
> +    /*****************************************************************/
Please add a space between the methods

2024-06-26 21:31 UTC, hamidnesar commented on src/test/java/ServiceNow/CHARMS/StepsImplementation/FanconiEligibilityQuestionnaireStepsImpl.java
> +    /*****************************************************************/
Please add a space between the methods

2024-06-26 21:31 UTC, hamidnesar commented on src/test/java/ServiceNow/CHARMS/StepsImplementation/FanconiEligibilityQuestionnaireStepsImpl.java
> +    /*****************************************************************/
Please add a space between the methods

2024-06-26 21:31 UTC, hamidnesar commented on src/test/java/ServiceNow/CHARMS/StepsImplementation/FanconiEligibilityQuestionnaireStepsImpl.java
> +    /*****************************************************************/
Please add a space between the methods

2024-06-26 21:31 UTC, hamidnesar commented on src/test/java/ServiceNow/CHARMS/StepsImplementation/FanconiEligibilityQuestionnaireStepsImpl.java
> +    /*****************************************************************/
Please add a space between the methods

2024-06-26 21:31 UTC, hamidnesar commented on src/test/java/ServiceNow/CHARMS/StepsImplementation/FanconiEligibilityQuestionnaireStepsImpl.java
> +    /*****************************************************************/
Please add a space between the methods

2024-06-26 21:31 UTC, hamidnesar commented on src/test/java/ServiceNow/CHARMS/StepsImplementation/FanconiEligibilityQuestionnaireStepsImpl.java
> +    /*****************************************************************/
Please add a space between the methods

2024-06-26 21:31 UTC, hamidnesar commented on src/test/java/ServiceNow/CHARMS/StepsImplementation/FanconiEligibilityQuestionnaireStepsImpl.java
> +    /*****************************************************************/
Please add a space between the methods

2024-06-26 21:31 UTC, hamidnesar commented on src/test/java/ServiceNow/CHARMS/StepsImplementation/FanconiEligibilityQuestionnaireStepsImpl.java
> +import java.util.Iterator;
There is literally a comment for each single line of the code across this class. We only need to add java doc statements which a descriptive comment for each method. Please do the followings across this class: 
**_1. Remove all the comments from each line of the code except java doc statements. 
2. Add a space between the methods._**

2024-06-26 21:31 UTC, hamidnesar commented on src/test/java/ServiceNow/CHARMS/Steps/FanconiEligibilityQuestionnaireSteps.java
> +import ServiceNow.CHARMS.NativeView.Pages.CHARMSParticipantDetailsPage;
Please keep your steps limited to one or two lines. If there are going to be longer, they need to be implemented in the steps implementation class and called here. 

_**1. Please remove all the comments from this class. 
2. Please remove java doc statements from the Steps class, step definition does not require them.**_

2024-06-26 23:15 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/StepsImplementation/FanconiEligibilityQuestionnaireStepsImpl.java
> +import java.util.Iterator;
I have given the comments for each line to make it clear as to what each step is doing. The surveys are very complicated and many questions are similar. To avoid confustion during debugging, i have given the comments. It has been approved by Diego

2024-06-26 23:32 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/StepsImplementation/FanconiEligibilityQuestionnaireStepsImpl.java
> +import java.util.Iterator;
Added a space between the methods.

2024-06-26 23:34 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/StepsImplementation/FanconiEligibilityQuestionnaireStepsImpl.java
> +    /*****************************************************************/
Added a space between the methods

2024-06-26 23:40 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/Steps/FanconiEligibilityQuestionnaireSteps.java
> +import ServiceNow.CHARMS.NativeView.Pages.CHARMSParticipantDetailsPage;
This is the code for the old test cases that needs to be revisited later on for cleaning.

2024-06-26 23:48 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/StepsImplementation/FanconiEligibilityQuestionnaireStepsImpl.java
> +    /*****************************************************************/
Added a space between the methods.

2024-06-26 23:48 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/StepsImplementation/FanconiEligibilityQuestionnaireStepsImpl.java
> +    /*****************************************************************/
done

2024-06-26 23:54 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/FanconiSurvey/playwright/Features/FanconiSurveyBackgroundInformation.feature
> +  @jains @BackgroundInformation @CP2-3178 @CP2-3133 @playwright
Reason not to add the  @regression or @smoke tag is because when running a specific feature file, the runner will look for all the features with these tags and will run all.

2024-06-26 23:57 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/FanconiSurvey/playwright/Pages/FanconiSurveyLoginPage.java
> +	public static final String PLEASE_RESPOND_FROM_THE_PERSPECTIVE_OF_THE_PARTICIPANT = "If you are filling this out for someone else, please respond from the perspective of the participant";
This is the file that have been excluded from the descriptive comments. Diego has approved it.

2024-06-27 00:03 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/FanconiSurvey/playwright/Features/FanconiSurveyDemographic.feature
> +    Given a Participant is on the Fanconi Study login page and logs with user credentials via Okta
yes, it is implemented in FanconiSurveyBackgroundInformationSteps

2024-06-27 00:05 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/Features/FanconiStudy/FanconiEligibilityQuestionnaire.feature
> +
Done

2024-06-27 00:06 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/Pages/FanconiLoginPage.java
> +
Done

2024-06-27 00:08 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/Pages/TestAccountResetPage.java
> +	@FindElementBy(css = "iframe[title='Main Content']")
Changed to @Findby

2024-06-27 00:19 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/Steps/FanconiEligibilityQuestionnaireSteps.java
> +        // Click the submit button
Done

2024-06-27 00:20 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/Steps/FanconiEligibilityQuestionnaireSteps.java
> +        //LogOut
Done

2024-06-27 00:20 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/Steps/FanconiEligibilityQuestionnaireSteps.java
> +        MiscUtils.sleep(500);
Done

2024-06-27 00:41 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/StepsImplementation/FanconiEligibilityQuestionnaireStepsImpl.java
> +    public void resetTestAccountSignIn() throws TestingException {
Done

2024-06-27 00:45 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/StepsImplementation/FanconiEligibilityQuestionnaireStepsImpl.java
> +            // Click Next Button
Added comments for the sake of readable code and easy to debug. Its a complex project

2024-06-27 00:45 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/StepsImplementation/FanconiEligibilityQuestionnaireStepsImpl.java
> +	/*****************************************************************/
Done

2024-06-27 00:45 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/StepsImplementation/FanconiEligibilityQuestionnaireStepsImpl.java
> +        // Click Next Button
explanation already given above

2024-06-27 00:46 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/StepsImplementation/FanconiEligibilityQuestionnaireStepsImpl.java
> +    /*****************************************************************/
Done

2024-06-27 00:47 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/StepsImplementation/FanconiEligibilityQuestionnaireStepsImpl.java
> +                // Add Other textBox option for your relationship to the participant
Explanation given above.

2024-06-27 00:47 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/StepsImplementation/FanconiEligibilityQuestionnaireStepsImpl.java
> +    /*****************************************************************/
Done

2024-06-27 00:47 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/StepsImplementation/FanconiEligibilityQuestionnaireStepsImpl.java
> +    /*****************************************************************/
Done

2024-06-27 00:47 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/StepsImplementation/FanconiEligibilityQuestionnaireStepsImpl.java
> +    /*****************************************************************/
Done

2024-06-27 00:48 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/StepsImplementation/FanconiEligibilityQuestionnaireStepsImpl.java
> +    /*****************************************************************/
Done

2024-06-27 00:48 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/StepsImplementation/FanconiEligibilityQuestionnaireStepsImpl.java
> +    /*****************************************************************/
Done

2024-06-27 00:48 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/StepsImplementation/FanconiEligibilityQuestionnaireStepsImpl.java
> +    /* Method to submit the phone details */
Done

2024-06-27 00:48 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/StepsImplementation/FanconiEligibilityQuestionnaireStepsImpl.java
> +    /* Method to submit the Ethnicity details */
Done

2024-06-27 00:48 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/StepsImplementation/FanconiEligibilityQuestionnaireStepsImpl.java
> +    /*****************************************************************/
Done

2024-06-27 00:48 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/StepsImplementation/FanconiEligibilityQuestionnaireStepsImpl.java
> +    /*****************************************************************/
Done

2024-06-27 00:48 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/StepsImplementation/FanconiEligibilityQuestionnaireStepsImpl.java
> +    /*****************************************************************/
Done

2024-06-27 00:48 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/StepsImplementation/FanconiEligibilityQuestionnaireStepsImpl.java
> +    /*****************************************************************/
Done

2024-06-27 00:49 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/StepsImplementation/FanconiEligibilityQuestionnaireStepsImpl.java
> +    /*****************************************************************/
Done

2024-06-27 00:49 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/StepsImplementation/FanconiEligibilityQuestionnaireStepsImpl.java
> +    /*****************************************************************/
Done. You would have asked in one comment line to remove the space between all the methods

2024-06-27 00:49 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/StepsImplementation/FanconiEligibilityQuestionnaireStepsImpl.java
> +    /*****************************************************************/
space between the methods removed

2024-06-27 00:49 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/StepsImplementation/FanconiEligibilityQuestionnaireStepsImpl.java
> +    /*****************************************************************/
space between the methods removed

2024-06-27 00:50 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/StepsImplementation/FanconiEligibilityQuestionnaireStepsImpl.java
> +    /*****************************************************************/
space between the methods removed

2024-06-27 00:50 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/StepsImplementation/FanconiEligibilityQuestionnaireStepsImpl.java
> +    /*****************************************************************/
space between the methods removed

2024-06-27 00:50 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/StepsImplementation/FanconiEligibilityQuestionnaireStepsImpl.java
> +    /*****************************************************************/
space between the methods removed

2024-06-27 00:50 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/StepsImplementation/FanconiEligibilityQuestionnaireStepsImpl.java
> +    /*****************************************************************/
space between the methods removed

2024-06-27 00:51 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/StepsImplementation/FanconiEligibilityQuestionnaireStepsImpl.java
> +    /*****************************************************************/
space between the methods removed

2024-06-27 00:51 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/StepsImplementation/FanconiEligibilityQuestionnaireStepsImpl.java
> +    /*****************************************************************/
space between the methods removed

2024-06-27 00:51 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/StepsImplementation/FanconiEligibilityQuestionnaireStepsImpl.java
> +    /*****************************************************************/
space between the methods removed

2024-06-27 00:51 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/StepsImplementation/FanconiEligibilityQuestionnaireStepsImpl.java
> +    /*****************************************************************/
space between the methods removed

2024-06-27 00:51 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/StepsImplementation/FanconiEligibilityQuestionnaireStepsImpl.java
> +    /*****************************************************************/
space between the methods removed

2024-06-27 00:51 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/StepsImplementation/FanconiEligibilityQuestionnaireStepsImpl.java
> +    /*****************************************************************/
space between the methods removed

2024-06-27 00:51 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/StepsImplementation/FanconiEligibilityQuestionnaireStepsImpl.java
> +    /*****************************************************************/
space between the methods removed

2024-06-27 00:51 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/StepsImplementation/FanconiEligibilityQuestionnaireStepsImpl.java
> +    /*****************************************************************/
space between the methods removed

2024-06-27 00:52 UTC, sonika-nih commented
Made changes as per the suggestions.

2024-06-27 15:45 UTC, hamidnesar requested changes
Hi Sonika, please review the comments. Thanks!

2024-06-27 15:45 UTC, hamidnesar commented on src/test/java/ServiceNow/CHARMS/StepsImplementation/FanconiEligibilityQuestionnaireStepsImpl.java
> +import java.util.Iterator;
> I have given the comments for each line to make it clear as to what each step is doing. The surveys are very complicated and many questions are similar. To avoid confustion during debugging, i have given the comments. It has been approved by Diego. Moreover, for anyone who is new to CHARMS will have a better workflow understanding by reading the comments. Basically, it shows how the progress of the work flow.

Sonika, I believe we need to come up with a better solution to code like a pro rather than adding a comment for each line.

2024-06-27 16:15 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/FanconiSurvey/playwright/Features/FanconiSurveyBackgroundInformation.feature
> +  @jains @BackgroundInformation @CP2-3178 @CP2-3133 @playwright
Added @Progression tag

2024-06-27 16:22 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/FanconiSurvey/playwright/Pages/FanconiSurveyLoginPage.java
> +	public static final String PLEASE_RESPOND_FROM_THE_PERSPECTIVE_OF_THE_PARTICIPANT = "If you are filling this out for someone else, please respond from the perspective of the participant";
.Diego has approved it and was decided that the comments will be added when I will have extra time

2024-06-27 16:27 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/StepsImplementation/FanconiEligibilityQuestionnaireStepsImpl.java
I will consider it going forward. This is old code and will be updated as time permits

2024-06-27 16:41 UTC, iamdez99 requested changes

2024-06-27 16:41 UTC, iamdez99 commented on src/test/java/ServiceNow/CHARMS/Constants/CHARMS_Data_File_Path_Constants.java
Agree with Hamids comment. Commented out code should not be merged to master.

2024-06-27 16:41 UTC, iamdez99 commented on src/test/java/ServiceNow/CHARMS/FanconiSurvey/playwright/Steps/FanconiSurveyBackgroundInformationSteps.java
Add space after line 6.

2024-06-27 16:41 UTC, iamdez99 commented on src/test/java/ServiceNow/CHARMS/FanconiSurvey/playwright/StepsImplementation/FanconiSurveyStepsImpl.java
Add space after line 12 please.

2024-06-27 16:41 UTC, iamdez99 commented on src/test/java/ServiceNow/CHARMS/Pages/TestAccountResetPage.java
Add space after line 10.

2024-06-27 16:41 UTC, iamdez99 commented on src/test/java/ServiceNow/CHARMS/Steps/FHQAuntUncleRecordProducerSteps.java
Delete space on line 4

2024-06-27 16:41 UTC, iamdez99 commented on src/test/java/ServiceNow/CHARMS/Steps/FanconiEligibilityQuestionnaireSteps.java
In this class you are throwing many exceptions because you are calling methods which are throwing exceptions. Next I recommend using try catch blocks so you would not have to throw these when you call them.

2024-06-27 16:41 UTC, iamdez99 commented on src/test/java/ServiceNow/CHARMS/Steps/FanconiLoginSteps.java
Cucumber step definitions should only have one line of code. You would have to store this code in a steps implementation class.

2024-06-27 16:41 UTC, iamdez99 commented on src/test/java/ServiceNow/CHARMS/StepsImplementation/FanconiEligibilityQuestionnaireStepsImpl.java
Delete line 50 and 53. No commented out code is allowed to be merged to master.

2024-06-27 17:27 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/StepsImplementation/FanconiEligibilityQuestionnaireStepsImpl.java
Done

2024-06-27 17:27 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/StepsImplementation/FanconiEligibilityQuestionnaireStepsImpl.java
Done

2024-06-27 17:28 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/Constants/CHARMS_Data_File_Path_Constants.java
Removed the commented code.

2024-06-27 17:29 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/StepsImplementation/FanconiEligibilityQuestionnaireStepsImpl.java
Removed all click comments

2024-06-27 17:29 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/StepsImplementation/FanconiEligibilityQuestionnaireStepsImpl.java
Removed

2024-06-27 17:30 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/StepsImplementation/FanconiEligibilityQuestionnaireStepsImpl.java
Removed all the commented lines

2024-06-27 17:37 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/Steps/FanconiLoginSteps.java
Diego, this is old code. I will modify it as soon as I have some time to do.

2024-06-27 17:38 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/Steps/FanconiEligibilityQuestionnaireSteps.java
Diego, this is old code. I will modify it as soon as I have some time to do.It is time consuming changes because it needs to be changed at too many places.

2024-06-27 17:40 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/Steps/FHQAuntUncleRecordProducerSteps.java
Done

2024-06-27 17:41 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/Pages/TestAccountResetPage.java
Done

2024-06-27 17:43 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/FanconiSurvey/playwright/StepsImplementation/FanconiSurveyStepsImpl.java
Done

2024-06-27 17:44 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/FanconiSurvey/playwright/Steps/FanconiSurveyBackgroundInformationSteps.java
Done

2024-06-27 17:45 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/FanconiSurvey/playwright/StepsImplementation/FanconiSurveyStepsImpl.java
> +    public static void login() {
Done

2024-06-27 17:46 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/Runners/RunCHARMSTestAccountResetForFanconi.java
>  		"junit:target/cucumber.xml", "rerun:target/failed.txt",
Done

2024-06-27 17:46 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/Runners/RunCHARMSTestAccountResetForFanconi.java
>  		"junit:target/cucumber.xml", "rerun:target/failed.txt",
Done

2024-06-27 17:47 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/Constants/CHARMS_Data_File_Path_Constants.java
> +/*
Removed

2024-06-27 17:48 UTC, sonika-nih commented on src/main/java/com/nci/automation/utils/ExcelReader.java
> +	//	return WorkbookFactory.create(new File(excelFilePath));
Done

2024-06-27 17:49 UTC, sonika-nih commented
Deleted all the comments in the stepimplementation file. Made changes as per the suggestions.

2024-06-28 14:41 UTC, iamdez99 requested changes

2024-06-28 14:41 UTC, iamdez99 commented on src/test/java/ServiceNow/CHARMS/Steps/FHQAuntUncleRecordProducerSteps.java
All this code should be in steps implementation and delete spaces between lines of code

2024-06-28 15:31 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/Runners/RunCHARMSTestAccountResetForFanconi.java
>  		"junit:target/cucumber.xml", "rerun:target/failed.txt",
added comments in the Fanconi survey login page.

2024-06-28 15:35 UTC, iamdez99 approved these changes
Reviewed and approved - juarezds

2024-06-28 15:40 UTC, matakevin approved these changes
LGTM

2024-06-28 15:43 UTC, hamidnesar approved these changes
Reviewed and approved! Excellent work.

2024-06-28 18:21 UTC, merged