SSJ + CHARMS RAS STUDY AUTOMATION
CBIIT/CBIIT-Test-Automation pull request #256
Opened 2024-08-02 18:18 UTC by iamdez99

SSJ + CHARMS RAS STUDY AUTOMATION

2024-08-02 20:06 UTC, hamidnesar requested changes
Hi, 
Please review the comments. Thank you!

2024-08-02 20:06 UTC, hamidnesar commented on src/test/java/ServiceNow/PlatformBusinessApps/SSJ/playwright/StepsImplementation/ApplicantProfileStepsImpl.java
> +//        Hooks.softAssert.assertEquals(page.locator("//div[@class='TitleAndDateContainer']/h1").innerText(), expectedVacancyTitle);
Please remove the commented code/line

2024-08-05 14:01 UTC, iamdez99 commented on src/test/java/ServiceNow/CHARMS/Features/RasopathyStudy/RAS Entire Flow.feature
> +#      | charmsras5@yahoo.com | RASTest2023$$ | screenerScenario4 | IIQScenario4 | RASSurveyScenario4 |
Yes for now they are, still need to update those scenarios.

2024-08-05 14:02 UTC, iamdez99 commented on src/test/java/ServiceNow/CHARMS/StepsImplementation/RASStudy/RAS_Screener_Submissions_StepsImpl.java
> +     * USE THIS METHOD TO CLICK ON RAS IIF FORM
Its actually IIQ, Ive made the update.

2024-08-05 14:03 UTC, iamdez99 commented on src/test/java/ServiceNow/CHARMS/StepsImplementation/RASStudy/RAS_Screener_Submissions_StepsImpl.java
> +
Done

2024-08-05 14:06 UTC, iamdez99 commented on src/test/java/ServiceNow/CHARMS/StepsImplementation/RASStudy/RAS_Screener_Submissions_StepsImpl.java
> +        MiscUtils.sleep(2000);
Thanks, I removed one.

2024-08-05 14:06 UTC, iamdez99 commented on src/test/java/ServiceNow/CHARMS/StepsImplementation/RASStudy/RAS_Screener_Submissions_StepsImpl.java
> +
Done

2024-08-05 14:06 UTC, iamdez99 commented on src/test/java/ServiceNow/CHARMS/StepsImplementation/RASStudy/RAS_Screener_Submissions_StepsImpl.java
> +         * BEGINNING: CONSENT FLOW PROCESS
Done.

2024-08-05 14:07 UTC, iamdez99 commented on src/test/java/ServiceNow/CHARMS/StepsImplementation/RASStudy/RAS_Screener_Submissions_StepsImpl.java
> +
Done

2024-08-05 14:11 UTC, iamdez99 commented on src/test/java/ServiceNow/CHARMS/StepsImplementation/RASStudy/RAS_Screener_Submissions_StepsImpl.java
> +
I was unsure about this code but I decided to remove it completely.

2024-08-05 14:12 UTC, iamdez99 commented on src/test/java/ServiceNow/CHARMS/StepsImplementation/RASStudy/RAS_Screener_Submissions_StepsImpl.java
> +    public void rasScreenerSurveyScenario1PartThree() {
actually, this will be removed soon but I dont want to delete it just yet for reference.

2024-08-05 14:12 UTC, iamdez99 commented on src/test/java/ServiceNow/CHARMS/StepsImplementation/RASStudy/RAS_Screener_Submissions_StepsImpl.java
> +    public void rasScreenerSurveyScenario1PartFour() {
Same with this method.

2024-08-05 14:12 UTC, iamdez99 commented on src/test/java/ServiceNow/CHARMS/StepsImplementation/RASStudy/RAS_Screener_Submissions_StepsImpl.java
> +    public void rasScreenerSurveyScenario1PartFive() {
and same with this method.

2024-08-05 14:12 UTC, iamdez99 commented on src/test/java/ServiceNow/CHARMS/StepsImplementation/RASStudy/RAS_Screener_Submissions_StepsImpl.java
> +    public void rasScreenerSurveyScenario1PartSix() {
Same with this one.

2024-08-05 14:13 UTC, iamdez99 commented on src/test/java/ServiceNow/CHARMS/StepsImplementation/RASStudy/RAS_Screener_Submissions_StepsImpl.java
> +    public void rasScreenerSurveyScenario1PartSeven() {
And this one as well.

2024-08-05 14:13 UTC, iamdez99 commented on src/test/java/ServiceNow/CHARMS/StepsImplementation/RASStudy/RAS_Screener_Submissions_StepsImpl.java
> +    public void rasScreenerSurveyScenario1PartEight() {
Same with this one.

2024-08-05 14:13 UTC, iamdez99 commented on src/test/java/ServiceNow/CHARMS/StepsImplementation/RASStudy/RAS_Screener_Submissions_StepsImpl.java
> +    public void rasScreenerSurveyScenario1PartTen() {
lol I didnt know we had many of this but same thing.

2024-08-05 14:14 UTC, iamdez99 commented on src/test/java/ServiceNow/CHARMS/StepsImplementation/RASStudy/RAS_Screener_Submissions_StepsImpl.java
> +    public void verifyingDropDownOption(WebElement element, String message) {
I removed it, had this method in the CommonUtils class.

2024-08-05 20:03 UTC, hamidnesar commented on src/test/java/ServiceNow/PlatformBusinessApps/SSJ/playwright/StepsImplementation/ApplicantProfileStepsImpl.java
> +//        Hooks.softAssert.assertEquals(page.locator("//div[@class='TitleAndDateContainer']/h1").innerText(), expectedVacancyTitle);
It seems line 1493 has been removed but the commented line is still there

2024-08-05 20:07 UTC, hamidnesar requested changes
Hi, 
It seems the commented line is still there on line 1494 but instead line 1493 (       Hooks.softAssert.assertEquals(page.locator("//div[@class='TitleAndDateContainer']/h1").innerText(), expectedVacancyTitle); ) has been from the below class:

PlatformBusinessApps/SSJ/playwright/StepsImplementation/ApplicantProfileStepsImpl.java
![image](https://github.com/user-attachments/assets/5581544a-de4c-49ad-83d2-55c632a01461)

2024-08-05 20:20 UTC, iamdez99 commented on src/test/java/ServiceNow/PlatformBusinessApps/SSJ/playwright/StepsImplementation/ApplicantProfileStepsImpl.java
> +//        Hooks.softAssert.assertEquals(page.locator("//div[@class='TitleAndDateContainer']/h1").innerText(), expectedVacancyTitle);
<img width="1058" alt="image" src="https://github.com/user-attachments/assets/57320e5d-abc6-44f1-8efe-04c0bb7bd89b">

2024-08-05 20:20 UTC, iamdez99 commented on src/test/java/ServiceNow/PlatformBusinessApps/SSJ/playwright/StepsImplementation/ApplicantProfileStepsImpl.java
> +//        Hooks.softAssert.assertEquals(page.locator("//div[@class='TitleAndDateContainer']/h1").innerText(), expectedVacancyTitle);
Not sure why if I removed it.... please see image

2024-08-05 20:21 UTC, sarwarahmed1 approved these changes

2024-08-05 20:22 UTC, iamdez99 commented on src/main/java/com/nci/automation/web/CommonUtils.java
Done.

2024-08-06 14:37 UTC, hamidnesar approved these changes
Reviewed & Approved!

2024-08-06 14:51 UTC, alenaminsk approved these changes

2024-08-06 18:52 UTC, matakevin approved these changes
LGTM

2024-08-06 18:52 UTC, matakevin approved these changes
LGTM

2024-08-06 19:34 UTC, lfcabrera14 commented on src/main/java/com/nci/automation/web/CommonUtils.java
its still not there for methods on line 717, 734, and 739

2024-08-07 20:25 UTC, merged