CCR Careers Smoke test: Fill In An Application As An Internal User , Verify CCR Landing Page items
CBIIT/CBIIT-Test-Automation pull request #259
Opened 2024-08-21 23:33 UTC by alenaminsk

2024-08-22 23:08 UTC, hamidnesar requested changes
Hi, 
Please review the comments

2024-08-22 23:08 UTC, hamidnesar commented on src/test/java/CustomBusiness/CCR/Pages/CCRAdminUserPage.java
> +        /**  Todays Date Actiev Datepicker Choice**/
Please replace Actiev with Active

2024-08-22 23:08 UTC, hamidnesar commented on src/test/java/CustomBusiness/CCR/Pages/CCRApplicantPage.java
> +    /** Reference Degree Degree Dropdown **/
Repeated word - Degree

2024-08-23 00:34 UTC, alenaminsk commented on src/test/java/CustomBusiness/CCR/Pages/CCRAdminUserPage.java
> +        /**  Todays Date Actiev Datepicker Choice**/
fixed

2024-08-23 00:34 UTC, alenaminsk commented on src/test/java/CustomBusiness/CCR/Pages/CCRApplicantPage.java
> +    /** Reference Degree Degree Dropdown **/
fixed

2024-08-26 14:23 UTC, hamidnesar approved these changes
Reviewed and approved

2024-08-26 14:39 UTC, sarwarahmed1 approved these changes

2024-08-26 19:19 UTC, lfcabrera14 approved these changes
reviewed and approved

2024-08-26 20:08 UTC, merged