NERD - SEER ODS Data Regression updates
CBIIT/CBIIT-Test-Automation pull request #261
Opened 2024-08-26 20:42 UTC by Mariachaudhry

2024-08-27 00:19 UTC, Mariachaudhry reviewed
Reviewed by Maria

2024-08-27 15:54 UTC, iamdez99 requested changes
Please review comments

2024-08-27 15:54 UTC, iamdez99 commented on src/test/java/ServiceNow/PlatformBusinessApps/SNOW_TRAVEL/playwright/Features/Travel_Request_Portal_Form.feature
A scenario in-progress should not be tagged regression or smoke

2024-08-27 21:51 UTC, matakevin requested changes
Please review my requested changes, thank you!

2024-08-27 21:51 UTC, matakevin commented on src/test/java/ServiceNow/PlatformBusinessApps/ETracking/StepsImplementation/EtrackAssetsRecords_NativeViewStepImplimentation.java
Does the method on line 25 need 2 JavaDocs (lines 17-24)?

2024-08-27 21:51 UTC, matakevin commented on src/test/java/ServiceNow/PlatformBusinessApps/OFFBOARD/StepsImplementation/OFFBOARD_StepsImpl.java
I could be wrong I think your method on line 38 can be in the steps class seeing as it's just 1 line of code

2024-08-27 21:51 UTC, matakevin commented on src/test/java/ServiceNow/PlatformBusinessApps/SEER/StepsImplementation/SEERUserRegistrationPageStepImpl.java
Your JavaDocs on lines 19-21 and 23-25 are stating the same thing.  Let's try getting rid of lines 23-25 to keep the JavaDocs outside the method they're describing

2024-08-27 21:51 UTC, matakevin commented on src/test/java/ServiceNow/PlatformBusinessApps/SNOW_TRAVEL/Selenium/Features/Travel_Request_Form.feature
Seeing as this is in progress, we can let the commented out lines pass but these should at least have an empty step definition for defined for them so they aren't commented out.  We're trying to keep commented code out of master

2024-08-27 21:51 UTC, matakevin commented on src/test/java/ServiceNow/PlatformBusinessApps/SNOW_TRAVEL/Selenium/Pages/Travel_Request_Form_Page.java
> +    public Travel_Request_Form_Page() {
This locator needs a descriptor to know what it is for

2024-08-27 21:51 UTC, matakevin commented on src/test/java/ServiceNow/PlatformBusinessApps/SNOW_TRAVEL/Selenium/StepImpl/Travel_Requests_Form_StepImpl.java
> +    public static void i_am_on_the_portal_form(String travelPlanningSystem) {
Method description is missing

2024-08-27 21:51 UTC, matakevin commented on src/test/java/ServiceNow/PlatformBusinessApps/SNOW_TRAVEL/playwright/Features/Travel_Request_Portal_Form.feature
> +      """
This is the same scenario listed in your "src/test/java/ServiceNow/PlatformBusinessApps/SNOW_TRAVEL/Selenium/Features/Travel_Request_Form.feature" file but the one in this current class isn't commented out.  Is there a reason its on 2 feature files with the same tags?

2024-08-27 21:51 UTC, matakevin commented on src/test/java/appsCommon/PageInitializers/PageInitializer.java
> +
Remove extra space on line 200 please.

2024-08-27 22:11 UTC, Mariachaudhry commented on src/test/java/ServiceNow/PlatformBusinessApps/ETracking/StepsImplementation/EtrackAssetsRecords_NativeViewStepImplimentation.java
good catch! :) I removed the method but forgot the javadoc- updated

2024-08-27 22:17 UTC, Mariachaudhry commented on src/test/java/ServiceNow/PlatformBusinessApps/SNOW_TRAVEL/Selenium/Features/Travel_Request_Form.feature
Added the empty step lines to avoid commented lines

2024-08-27 22:20 UTC, Mariachaudhry commented on src/test/java/ServiceNow/PlatformBusinessApps/SNOW_TRAVEL/Selenium/StepImpl/Travel_Requests_Form_StepImpl.java
> +    public static void i_am_on_the_portal_form(String travelPlanningSystem) {
this test case is still in progress. I added the doc string to it

2024-08-27 22:22 UTC, Mariachaudhry commented on src/test/java/ServiceNow/PlatformBusinessApps/OFFBOARD/StepsImplementation/OFFBOARD_StepsImpl.java
updated

2024-08-27 22:25 UTC, Mariachaudhry commented on src/test/java/ServiceNow/PlatformBusinessApps/SNOW_TRAVEL/Selenium/Pages/Travel_Request_Form_Page.java
> +    public Travel_Request_Form_Page() {
This is the page's constructor

2024-08-27 22:27 UTC, Mariachaudhry commented on src/test/java/ServiceNow/PlatformBusinessApps/SNOW_TRAVEL/playwright/Features/Travel_Request_Portal_Form.feature
> +      """
yes, started working as playwright but seems Selenium test case has better assertion solution which is why both are in progress and one will be finalized later on.

2024-08-27 22:34 UTC, hamidnesar requested changes
Hi, 
Please review the comments. Thanks

2024-08-27 22:34 UTC, hamidnesar commented on src/test/java/ServiceNow/PlatformBusinessApps/NERD/StepsImplementation/NERDCollaborationSubmissionStepImpl.java
> +        ServiceNow_Common_Methods.impersonateAnyUser("Abigail joyce");
I do not see an issue with this but for consistency, it is better to start names with capital letter. joyce vs Joyce

2024-08-27 22:34 UTC, hamidnesar commented on src/test/java/ServiceNow/PlatformBusinessApps/NERD/StepsImplementation/NERDCollaborationSubmissionStepImpl.java
> +        ServiceNow_Common_Methods.impersonateAnyUser("Abigail joyce");
joyce vs Joyce

2024-08-27 22:34 UTC, hamidnesar commented on src/test/java/ServiceNow/PlatformBusinessApps/NERD/StepsImplementation/NERD_NCI_StaffMemberStepsImplementation.java
> +        ServiceNow_Common_Methods.impersonateAnyUser("Abigail joyce");
joyce vs Joyce

2024-08-27 22:34 UTC, hamidnesar commented on src/test/java/ServiceNow/PlatformBusinessApps/NERD/StepsImplementation/NERD_NCI_StaffMemberStepsImplementation.java
> +        ServiceNow_Common_Methods.impersonateAnyUser("Abigail joyce");
joyce vs Joyce

2024-08-27 22:34 UTC, hamidnesar commented on src/test/java/ServiceNow/PlatformBusinessApps/NERD/StepsImplementation/NERD_NCI_StaffMemberStepsImplementation.java
> +        ServiceNow_Common_Methods.impersonateAnyUser("Abigail joyce");
joyce vs Joyce

2024-08-27 22:34 UTC, hamidnesar commented on src/test/java/ServiceNow/PlatformBusinessApps/NERD/StepsImplementation/NERD_NCI_StaffMemberStepsImplementation.java
> +        ServiceNow_Common_Methods.impersonateAnyUser("Abigail joyce");
joyce vs Joyce

2024-08-27 22:34 UTC, hamidnesar commented on src/test/java/ServiceNow/PlatformBusinessApps/NERD/StepsImplementation/NERD_NCI_StaffMemberStepsImplementation.java
> +        ServiceNow_Common_Methods.impersonateAnyUser("Abigail joyce");
joyce vs Joyce

2024-08-27 22:34 UTC, hamidnesar commented on src/test/java/ServiceNow/PlatformBusinessApps/OFFBOARD/StepsImplementation/OFFBOARD_StepsImpl.java
> +    public static void should_not_be_required_for_transfer_request(String hardwareReturnTicketNumbers) {
Did we stop adding JavaDocs for methods in Steps Implementation class? 
The same applies to other methods within this class on lines:
306, 311, 332, 340, 359, 381

2024-08-27 22:34 UTC, hamidnesar commented on src/test/java/ServiceNow/PlatformBusinessApps/SNOW_TRAVEL/Selenium/StepImpl/Travel_Requests_Form_StepImpl.java
> +    public static void i_am_on_the_portal_form(String travelPlanningSystem) {
Agree, JavaDoc is missing

2024-08-27 22:34 UTC, hamidnesar commented on src/test/java/ServiceNow/PlatformBusinessApps/SNOW_TRAVEL/Travel_Runners/Run_TRAVEL_PW_Progression_Test.java
> +        , features = {"src/test/java/ServiceNow/PlatformBusinessApps/SNOW_TRAVEL/playwright/Features" , "src/test/java/ServiceNow/PlatformBusinessApps/SNOW_TRAVEL/Selenium/Features" }
If this is a Playwright Runner class, is there a reason for gluing selenium features to it?

2024-08-27 22:34 UTC, hamidnesar commented on src/test/java/ServiceNow/PlatformBusinessApps/SNOW_TRAVEL/Travel_Runners/Run_TRAVEL_PW_Regression_Test.java
> +        , features = {"src/test/java/ServiceNow/PlatformBusinessApps/SNOW_TRAVEL/playwright/Features", "src/test/java/ServiceNow/PlatformBusinessApps/SNOW_TRAVEL/Selenium/Features"}
If this is a Playwright Runner class, is there a reason for gluing selenium features to it?

2024-08-27 22:34 UTC, hamidnesar commented on src/test/java/ServiceNow/PlatformBusinessApps/SNOW_TRAVEL/Travel_Runners/Run_TRAVEL_PW_Smoke_Test.java
> +        , features = {"src/test/java/ServiceNow/PlatformBusinessApps/SNOW_TRAVEL/playwright/Features" , "src/test/java/ServiceNow/PlatformBusinessApps/SNOW_TRAVEL/Selenium/Features" }
If this is a Playwright Runner class, is there a reason for gluing selenium features to it?

2024-08-27 22:34 UTC, hamidnesar commented on src/test/java/ServiceNow/ServiceNowRunners/RunETrackingRegressionTest.java
>          "junit:target/cucumber.xml", "rerun:target/failed.txt",
We no longer use Junit, it is better to remove it from line 7 (junit:target/cucumber.xml)

2024-08-27 22:34 UTC, hamidnesar commented on src/test/java/ServiceNow/PlatformBusinessApps/ETracking/StepsImplementation/EtrackAssetsRecords_NativeViewStepImplimentation.java
> +     * This metha verifies a date picker "Expiration Date" field.
metha vs method

2024-08-28 00:03 UTC, Mariachaudhry commented on src/test/java/ServiceNow/PlatformBusinessApps/OFFBOARD/StepsImplementation/OFFBOARD_StepsImpl.java
> +    public static void should_not_be_required_for_transfer_request(String hardwareReturnTicketNumbers) {
updated

2024-08-28 00:05 UTC, Mariachaudhry commented on src/test/java/ServiceNow/PlatformBusinessApps/SNOW_TRAVEL/Travel_Runners/Run_TRAVEL_PW_Progression_Test.java
> +        , features = {"src/test/java/ServiceNow/PlatformBusinessApps/SNOW_TRAVEL/playwright/Features" , "src/test/java/ServiceNow/PlatformBusinessApps/SNOW_TRAVEL/Selenium/Features" }
This runner is for both feature files

2024-08-28 11:51 UTC, hamidnesar approved these changes
Reviewed and approved

2024-08-28 13:14 UTC, alenaminsk approved these changes
Reviewed and approved

2024-08-28 14:40 UTC, georgeb79 approved these changes

2024-08-28 14:41 UTC, sarwarahmed1 approved these changes

2024-08-28 19:38 UTC, matakevin approved these changes
LGTM

2024-09-04 16:50 UTC, merged