CI - NERD Workflow Modifications
CBIIT/CBIIT-Test-Automation pull request #263
Opened 2024-09-04 17:36 UTC by iamdez99

2024-09-04 19:05 UTC, Mariachaudhry requested changes

2024-09-04 19:05 UTC, Mariachaudhry commented on src/test/java/ServiceNow/CHARMS/StepsImplementation/RASStudy/RAS_Screener_Submissions_StepsImpl.java
Line 23 needs to be removed

2024-09-04 19:05 UTC, Mariachaudhry commented on src/test/java/ServiceNow/CHARMS/StepsImplementation/TestAccountResetImpl.java
line 34 needs to be removed

2024-09-04 20:10 UTC, hamidnesar requested changes
Hi, 
Please review the comments. Thanks!

2024-09-04 20:10 UTC, hamidnesar commented on src/test/java/GrantsApps/GPMATS/Steps/GPMATS_All_Steps.java
> +package GrantsApps.GPMATS.Steps;
There are a lot of empty lines throughout this page within the code starting from line 58, 61, 64, .... Are those empty lines there on purpose to enhance readability?

2024-09-04 20:10 UTC, hamidnesar commented on src/test/java/GrantsApps/GrantsRunners/GPMATS/Run_GPMATS_Progression_Test.java
> +        "junit:target/cucumber.xml", "rerun:target/failed.txt",
Please remove "junit:target/cucumber.xml"

2024-09-04 20:10 UTC, hamidnesar commented on src/test/java/GrantsApps/GrantsRunners/GPMATS/Run_GPMATS_Regression_Test.java
> +            "junit:target/cucumber.xml", "rerun:target/failed.txt",
please remove "junit:target/cucumber.xml"

2024-09-04 20:10 UTC, hamidnesar commented on .gitattributes
> +*.html filter=lfs diff=lfs merge=lfs -text
Is this a new class introduced in the framework? Wondering if it is meant to be added to git ignore

2024-09-12 17:20 UTC, Mariachaudhry approved these changes

2024-09-12 17:38 UTC, hamidnesar approved these changes
Reviewed and approved

2024-09-12 17:48 UTC, alenaminsk approved these changes

2024-09-12 17:49 UTC, merged