eGrants - document upload workflow automated test cases
CBIIT/CBIIT-Test-Automation pull request #267
Opened 2024-09-11 16:46 UTC by hamidnesar

2024-09-11 19:33 UTC, sarwarahmed1 approved these changes
Reviewed and Approved!

2024-09-11 19:42 UTC, iamdez99 requested changes

2024-09-11 19:42 UTC, iamdez99 commented on src/test/java/CustomBusiness/Egrants/Features/EgrantsLinksVerificationAndManagementMenu.feature
It seems that these scenarios are missing the requirement IDs, can you please add them?

2024-09-11 19:42 UTC, iamdez99 commented on src/test/java/CustomBusiness/Egrants/Features/EgrantsSearchAndFileManagementScenarios.feature
Some of these scenarios are also missing requirement IDs, can you please also format line 44 and 71?

2024-09-11 19:42 UTC, iamdez99 commented on src/test/java/CustomBusiness/Egrants/Pages/EgrantsSearchAndFileManagementScenariosPage.java
The element on line 73 looks like it may be dynamic, can you confirm it works or do we need to locate it differently?

2024-09-11 19:42 UTC, iamdez99 commented on src/test/java/CustomBusiness/Egrants/Steps/EgrantsSearchAndFileManagementSteps.java
Are the hard sleeps necessary in these steps?

2024-09-11 19:42 UTC, iamdez99 commented on src/test/java/CustomBusiness/Egrants/Steps/HooksSteps.java
This hooks class should not be used, please use the universal hooks class we have. You will have to modify your runners as well.

2024-09-11 19:42 UTC, iamdez99 commented on src/test/java/CustomBusiness/Egrants/Steps/QuickLinkVerificationAndManagementMenuSteps.java
String parameter isnt being used but its not required to be used per our last conversation.

2024-09-11 19:42 UTC, iamdez99 commented on src/test/java/CustomBusiness/Egrants/StepsImplementation/EgrantsStepImplementation.java
If the hard sleeps are necessary, then I recommend taking the screenshots after the sleeps.

2024-09-11 21:54 UTC, hamidnesar commented on src/test/java/CustomBusiness/Egrants/Features/EgrantsLinksVerificationAndManagementMenu.feature
These are old requirements that do not have any documentation stored neither in Jira or elsewhere.

2024-09-11 21:54 UTC, hamidnesar commented on src/test/java/CustomBusiness/Egrants/Features/EgrantsSearchAndFileManagementScenarios.feature
These are old requirements that do not have any documentation stored neither in Jira nor elsewhere.
Addressed the formatting issue on Lines 44 and 71.

2024-09-11 21:55 UTC, hamidnesar commented on src/test/java/CustomBusiness/Egrants/Steps/EgrantsSearchAndFileManagementSteps.java
The scripts are executing so quick that it is hard to see them interacting with elements on page. I am using these Hard sleeps to slow down the execution process a bit.

2024-09-11 21:55 UTC, hamidnesar commented on src/test/java/CustomBusiness/Egrants/Pages/EgrantsSearchAndFileManagementScenariosPage.java
It was dynamic and I was grouping them by to get the one that is visible on the page. I have replaced the Xpath with CSS selector.

2024-09-11 21:55 UTC, hamidnesar commented on src/test/java/CustomBusiness/Egrants/Steps/HooksSteps.java
Deleted the Hooks class and modified the Runner classes to use the universal hooks class.

2024-09-11 21:56 UTC, hamidnesar commented on src/test/java/CustomBusiness/Egrants/Steps/QuickLinkVerificationAndManagementMenuSteps.java
Removed the unused String parameter

2024-09-11 21:56 UTC, hamidnesar commented on src/test/java/CustomBusiness/Egrants/StepsImplementation/EgrantsStepImplementation.java
Addressed, moved all screenshot taking steps after the hard sleeps.

2024-09-12 15:33 UTC, iamdez99 requested changes

2024-09-12 15:33 UTC, iamdez99 commented on src/test/java/CustomBusiness/Egrants/StepsImplementation/EgrantsStepImplementation.java
Please remove extra space on 13 or 14.

2024-09-12 15:36 UTC, hamidnesar commented on src/test/java/CustomBusiness/Egrants/StepsImplementation/EgrantsStepImplementation.java
Removed the extra space. Thanks!

2024-09-12 15:42 UTC, iamdez99 approved these changes

2024-09-12 15:45 UTC, katm007 approved these changes
Review and approved!

2024-09-12 15:49 UTC, merged