Automated CP2-3603 CHARMS RAS Adult E-Consent
CBIIT/CBIIT-Test-Automation pull request #272
Opened 2024-09-19 15:33 UTC by katm007

Automated CP2-3603 CHARMS RAS Adult E-Consent.

2024-09-19 16:33 UTC, sarwarahmed1 requested changes

2024-09-19 16:33 UTC, sarwarahmed1 commented on src/test/java/ServiceNow/CHARMS/Steps/RAS_All_Steps.java
> +     * @param sheetName
Javadocs are missing descriptions for the parameters in this file on lines 13, 23, 33-36, 46, 56-57

2024-09-19 16:33 UTC, sarwarahmed1 commented on src/test/java/ServiceNow/CHARMS/Steps/RAS_Common_Methods.java
> +public class RAS_Common_Methods {}
Is this method being used? If not is it necessary to have?

2024-09-19 16:38 UTC, katm007 commented on src/test/java/ServiceNow/CHARMS/Steps/RAS_Common_Methods.java
> +public class RAS_Common_Methods {}
This class will be used to store RAS common methods in the future

2024-09-19 17:00 UTC, hamidnesar requested changes
Hi, 
Please review the comments.

2024-09-19 17:21 UTC, katm007 commented on src/test/java/ServiceNow/CHARMS/StepsImplementation/RASConsentStepsImpl.java
> +package ServiceNow.CHARMS.StepsImplementation;
Diego asked me to put all steps in RAS_All_Steps
Should I get rid of the steps implementation and only use RAS_All_Steps?

2024-09-19 17:41 UTC, hamidnesar requested changes
Hi, please review the comments

2024-09-19 17:41 UTC, hamidnesar commented on src/test/java/ServiceNow/CHARMS/StepsImplementation/RASConsentStepsImpl.java
> +package ServiceNow.CHARMS.StepsImplementation;
I see what is happening here. It is redundant to declare the steps on two classes. I would suggest removing the steps declared steps from the Steps Implementation class. 
For instance, you do not need to declare @Given("the e-consent is submitted for {string}") in the Steps implementation class if you already have it in the Steps class. 
![image](https://github.com/user-attachments/assets/e8638181-2f87-43ef-9c7e-b7b141a084d4)

Additionally, you do not need to keep the method names the same as the step in your steps implementation. For example, "public static void the_e_consent_is_submitted_for" can be anything meaningful and then called in the Steps class.

2024-09-19 18:36 UTC, hamidnesar requested changes
Hi, please review the comment. Thanks

2024-09-19 18:36 UTC, hamidnesar commented on src/test/java/ServiceNow/CHARMS/StepsImplementation/RASStudy/RAS_Screener_Submissions_StepsImpl.java
> +        MiscUtils.sleep(2000);
You could modify line 739 to four seconds (4000) instead of adding a new line.

2024-09-19 18:52 UTC, sarwarahmed1 requested changes
Please review comments

2024-09-19 18:52 UTC, sarwarahmed1 commented on src/test/java/ServiceNow/CHARMS/StepsImplementation/TestAccountResetImpl.java
> +    @Given("test automation account {string} has been reset")
This @Given tag is not needed since it was already used in the "src/test/java/ServiceNow/CHARMS/Steps/TestAccountResetSteps.java" file.

2024-09-19 18:59 UTC, katm007 commented on src/test/java/ServiceNow/CHARMS/StepsImplementation/TestAccountResetImpl.java
> +    @Given("test automation account {string} has been reset")
I fixed it, thank you

2024-09-19 18:59 UTC, katm007 commented on src/test/java/ServiceNow/CHARMS/StepsImplementation/RASStudy/RAS_Screener_Submissions_StepsImpl.java
> +        MiscUtils.sleep(2000);
I changed to 4sec wait. Thank you

2024-09-19 19:10 UTC, hamidnesar approved these changes
Reviewed and approved!

2024-09-19 19:15 UTC, sarwarahmed1 approved these changes
Looks good!

2024-09-20 16:31 UTC, puzikovam2 approved these changes
approved by @puzikovam2

2024-09-20 16:32 UTC, lfcabrera14 approved these changes
Approved

2024-09-20 16:33 UTC, merged