Added some classes missing on master
CBIIT/CBIIT-Test-Automation pull request #279
Opened 2024-09-27 19:16 UTC by matakevin

Will create smaller PRs with each class to avoid large, time consuming PRs

2024-09-27 20:12 UTC, katm007 commented on src/test/java/AnalysisTools/ACT24/StepsImpl/ACT24ResearcherStepImpl.java
I would convert these comments to javadoc comments. Also, please remove empty line 6, thank you.

2024-09-27 20:12 UTC, katm007 commented on src/test/java/AnalysisTools/ACT24/Steps/ACT24ParticipantPortalSteps.java
Should these have comments?

2024-09-27 20:14 UTC, katm007 commented on src/test/java/AnalysisTools/CEDCD/Steps/CEDCDAdminPageSteps.java
Please remove empty line 11.

2024-09-27 21:43 UTC, Mariachaudhry requested changes

2024-09-27 21:43 UTC, Mariachaudhry commented on src/test/java/AnalysisTools/ACT24/Steps/ACT24ResearcherPortalSteps.java
emapty line 12 can be deleted within imports.

2024-09-27 21:43 UTC, Mariachaudhry commented on src/test/java/AnalysisTools/GDSTracking/Steps/UpgradeExample.java
on the bottom of class, there is commented java doc string. is it needed?

2024-09-27 21:43 UTC, Mariachaudhry commented on src/test/java/AnalysisTools/ICDGenie/playwright/Features/ICDGenie.feature
is scenario 7 needed which is in progress?

2024-09-27 21:43 UTC, Mariachaudhry commented on src/test/java/AnalysisTools/ICDGenie/playwright/Steps/Example.java
delete the empty space between imports. line 5

2024-09-27 21:43 UTC, Mariachaudhry commented on src/test/java/AnalysisTools/ICDGenie/playwright/Steps/ICDGenieSteps.java
line 12 and 14 need to be deleted between imports.

2024-09-27 21:43 UTC, Mariachaudhry commented on src/test/java/AnalysisTools/ICRP/Steps/ICRPSearchSteps.java
are the hard sleeps needed?

2024-09-27 21:43 UTC, Mariachaudhry commented on src/test/java/AnalysisTools/JPSurv/Steps/JPSurvHomePageSteps.java
extra line 343 can be deleted.

2024-09-27 21:43 UTC, Mariachaudhry commented on src/test/java/appsCommon/PageInitializers/PageInitializer.java
need extra space between 79 and 80.

2024-09-30 15:34 UTC, matakevin commented on src/test/java/appsCommon/PageInitializers/PageInitializer.java
Added, will push soon

2024-09-30 15:35 UTC, matakevin commented on src/test/java/AnalysisTools/JPSurv/Steps/JPSurvHomePageSteps.java
Added, will push soon

2024-09-30 15:38 UTC, matakevin commented on src/test/java/AnalysisTools/ICRP/Steps/ICRPSearchSteps.java
Yes, the site loads extremely slow and any wait over 30 seconds times out the run.  So if it's a 15 second wait, its actually about a 45 second wait.  It will be updated after a couple of more project are automated to make sure the waits are still relevant but will not be changed soon.

2024-09-30 15:40 UTC, matakevin commented on src/test/java/AnalysisTools/ICDGenie/playwright/Steps/ICDGenieSteps.java
Fixed and removed unused imports also

2024-09-30 15:40 UTC, matakevin commented on src/test/java/AnalysisTools/ICDGenie/playwright/Steps/Example.java
This shouldn't have been pushed, will removed and push again

2024-09-30 15:52 UTC, matakevin commented on src/test/java/AnalysisTools/GDSTracking/Steps/UpgradeExample.java
No, I created the subProject class for this but it used to be for both flows.  Technically GDS won't be automated but for the TomCat upgrade I created these classes.  Will remove both

2024-09-30 15:54 UTC, matakevin commented on src/test/java/AnalysisTools/ACT24/Steps/ACT24ResearcherPortalSteps.java
fixed and removed unused imports

2024-09-30 15:55 UTC, matakevin commented on src/test/java/AnalysisTools/CEDCD/Steps/CEDCDAdminPageSteps.java
Fixed and removed unused imports

2024-09-30 16:01 UTC, matakevin commented on src/test/java/AnalysisTools/ACT24/StepsImpl/ACT24ResearcherStepImpl.java
Fixed, will push soon

2024-09-30 16:36 UTC, Mariachaudhry approved these changes

2024-09-30 19:45 UTC, hamidnesar requested changes
Hi, 
Please review the comments

2024-09-30 19:45 UTC, hamidnesar commented on src/test/java/AnalysisTools/ICDGenie/selenium/Steps/HooksSteps.java
Are you still using this Hooks class? It can be deleted if you have started using the universal hooks. I noticed you have modified your Runner classes.

2024-09-30 19:45 UTC, hamidnesar commented on src/test/java/AnalysisTools/ICRP/Steps/ICRPSearchSteps.java
All MiscUtils.sleep can be replaced with CommonUtils.sleep.

2024-09-30 19:45 UTC, hamidnesar commented on src/test/java/AnalysisTools/JPSurv/Features/JPSurvHomePage.feature
> +    @Progression @matakevin @selenium @manualLoadTest
If this an in progress test case, it can be tagged as @In-progress instead of @progression

2024-09-30 19:45 UTC, hamidnesar commented on src/test/java/AnalysisTools/JPSurv/Steps/JPSurvHomePageSteps.java
> +			MiscUtils.sleep(2000);
MiscUtils.sleep can be replaced with CommonUtils.sleep

2024-09-30 19:45 UTC, hamidnesar commented on src/test/java/AnalysisTools/ezQTL/Features/AnalysesTab.feature
please tag all the scenarios @selenium or @playwright

2024-09-30 19:45 UTC, hamidnesar commented on src/test/java/AnalysisTools/ezQTL/Steps/AnalysesTabSteps.java
> +        MiscUtils.sleep(1000);
MiscUtils => CommonUtils.sleep

2024-09-30 19:45 UTC, hamidnesar commented on src/test/java/AnalysisTools/scAtlas/Features/Cohorts.feature
please tag all the scenarios @Selenium or @playwright

2024-09-30 19:45 UTC, hamidnesar commented on src/test/java/AnalysisTools/scAtlas/Features/Home.feature
please tag all the scenarios @Selenium or @playwright

2024-09-30 19:45 UTC, hamidnesar commented on src/test/java/AnalysisTools/scAtlas/Steps/SCAtlasCohortsSteps.java
> +        MiscUtils.sleep(5000);
MiscUtils.sleep can be replaced with CommonUtils.sleep.

2024-09-30 19:45 UTC, hamidnesar commented on src/test/java/AnalysisTools/scAtlas/Steps/SCAtlasHomeSteps.java
> +        MiscUtils.sleep(5000);
MiscUtils.sleep can be replaced with CommonUtils.sleep.

2024-09-30 19:45 UTC, hamidnesar commented on src/test/java/AnalysisTools/scAtlas/Steps/SCAtlasHomeSteps.java
> +        MiscUtils.sleep(5000);
MiscUtils.sleep can be replaced with CommonUtils.sleep.

2024-10-07 17:40 UTC, matakevin commented on src/main/resources/conf/env/dev.xml
> +		<login_url>https://analysistools-dev.cancer.gov/jpsurv/
Seeing as this file was deleted for the testProperties it shouldn't be there anymore but yes, if this endpoint isn't specified then it will redirect to the analysis tools landing page where all the applications hosted by the AT team are.

2024-10-07 17:41 UTC, matakevin commented on src/test/java/AnalysisTools/scAtlas/Steps/SCAtlasCohortsSteps.java
> +        MiscUtils.sleep(5000);
Lots of the miscUtils and selenium/playwright tags have been addressed since recent push.  Will close all conversations regarding these requested changes.

2024-10-07 17:45 UTC, matakevin commented on src/test/java/AnalysisTools/ACT24/Steps/ACT24ParticipantAPISteps.java
> +//        String expectedText = "[{\"qcOverlapApplied\":\"N\",\"qcOverlapTime\":null,\"qcOverlapDeletedEventsCount\":1,\"subjectId\":\"1\",\"studyId\":7685,\"studyLastUpdatedDate\":\"01/22/2024\",\"s
removed from commit

2024-10-07 18:54 UTC, matakevin commented on src/test/java/AnalysisTools/ACT24/Steps/ACT24ParticipantAPISteps.java
> +        String password = globalPass;
fixed

2024-10-07 18:57 UTC, matakevin commented on src/test/java/AnalysisTools/GWASExplorer/Pages/BrowsePhenotypesPage.java
> +    @FindBy(xpath = "/html/body/main/div[1]/div[1]/div/div[3]/a")
Completed valid change, it was initially changed from the relative xpath for it not working anymore.  I'll try and fix it if it breaks but for now will keep as is.

2024-10-07 18:57 UTC, matakevin commented on src/test/java/AnalysisTools/GWASExplorer/Pages/GwasExplorerHomePage.java
> +    @FindBy(xpath = "/html/body/main/div[1]/div[1]/div/div[3]/a")
Completed valid change, it was initially changed from the relative xpath for it not working anymore.  I'll try and fix it if it breaks but for now will keep as is.

2024-10-07 19:04 UTC, matakevin commented on src/test/java/AnalysisTools/ICDGenie/selenium/Steps/HooksSteps.java
No, was deleted

2024-10-08 14:04 UTC, hamidnesar requested changes
Hi, please review the comments. Thanks!

2024-10-08 14:04 UTC, hamidnesar commented on src/test/java/AnalysisTools/scAtlas/Steps/SCAtlasCohortsSteps.java
> +        MiscUtils.sleep(5000);
MiscUtils class no longer exists. It needs to be replaced with CommonUtils class

2024-10-08 14:05 UTC, hamidnesar commented on src/main/resources/conf/env/test.xml
This class no longer exists in the framework

2024-10-08 14:19 UTC, matakevin commented on src/main/resources/conf/env/test.xml
Are you saying it's gone or that I'm reintroducing it to master?  It shouldn't be on my PR anymore

2024-10-08 14:20 UTC, matakevin commented on src/test/java/AnalysisTools/ACT24/StepsImpl/ACT24ResearcherStepImpl.java
> +        String timeStamp = new SimpleDateFormat("MMdd").format(new java.util.Date());
I'll check for a new methods already created in master

2024-10-08 14:30 UTC, matakevin commented on src/test/java/AnalysisTools/ACT24/StepsImpl/ACT24ResearcherStepImpl.java
> +        String timeStamp = new SimpleDateFormat("MMdd").format(new java.util.Date());
I checked and there isn't a common method for getting the date in MMdd format.  I could create but for now it seems very particular to this one instances or application

2024-10-08 14:34 UTC, matakevin commented on src/test/java/AnalysisTools/ICDGenie/playwright/Steps/ICDGenieSteps.java
> +    }
resolved

2024-10-08 14:34 UTC, matakevin commented on src/test/java/AnalysisTools/ICDGenie/playwright/Steps/ICDGenieSteps.java
> +    }
resolved

2024-10-08 14:36 UTC, matakevin commented on src/test/java/AnalysisTools/ICDGenie/playwright/Steps/ICDGenieSteps.java
> +    }
These are empty but in progress.  ICDGenie feature file line 50 contains these steps

2024-10-11 17:13 UTC, alenaminsk reviewed
Approved

2024-10-16 17:38 UTC, hamidnesar requested changes
Hi Kevin, please review the comments and suggestions. Thanks!

2024-10-16 17:38 UTC, hamidnesar commented on src/test/java/AnalysisTools/GWASExplorer/GWASExplorerRunners/RunGWASExplorerSmokeTest.java
- You could add .html after default-report on line 6.
- You could remove Junit from line 7

2024-10-16 17:38 UTC, hamidnesar commented on src/test/java/AnalysisTools/GWASExplorer/Steps/BrowsePhenotypesSteps.java
I would suggest replacing the Assert on line 20 with the one we have in the CommonUtils (CommonUtils.assertTrue). And remove the Assert import from imports if you decided going that route.

2024-10-16 17:38 UTC, hamidnesar commented on src/test/java/AnalysisTools/ICDGenie/playwright/Steps/ICDGenieSteps.java
> +    }
These three steps are not implemented yet

2024-10-16 18:07 UTC, matakevin commented on src/test/java/AnalysisTools/ICDGenie/playwright/Steps/ICDGenieSteps.java
> +    }
Yes, they are in progress for a scenario so they do not have steps coded just yet

2024-10-16 19:23 UTC, hamidnesar approved these changes
Approved!

2024-10-16 21:53 UTC, merged