OA Intake  App. Create an OA Intake form
CBIIT/CBIIT-Test-Automation pull request #283
Opened 2024-10-01 14:18 UTC by alenaminsk

OA Intake  App. Create an OA Intake form

2024-10-01 20:25 UTC, hamidnesar requested changes
Hi, 
Please review the comments.

2024-10-01 20:25 UTC, hamidnesar commented on src/main/resources/conf/env/test.xml
Please delete this class. We no longer use it. All the URLs are declared in TestProperties.java class

2024-10-01 20:25 UTC, hamidnesar commented on src/test/java/ServiceNow/OA_Intake/Features/OAIntakeForm.feature
> +  @selenium @OAIntake-576 @OAIntake-544 @OAIntake-575 @OAIntake-499 @OAIntake-657 @OAIntake-430 @OAIntake-408 @OAIntake-623 @Regression @Alena @Smoke
You would only tag a scenario @Smoke if it is going to be part of the daily scheduled jobs, else you do not need to tag it as @Smoke

2024-10-01 20:25 UTC, hamidnesar commented on src/test/java/ServiceNow/OA_Intake/Steps/OAIntakeSteps.java
All your steps are missing Javadocs. Since you are not implementing them in the Steps Implementation class, please add them here

2024-10-01 20:25 UTC, hamidnesar commented on src/test/java/ServiceNow/ServiceNowRunners/OAIntakeRunners/OAIntakeProgressionRunner.java
> +@CucumberOptions(plugin = {"html:target/html-reports/cucumber-default-report"
Please add .html at the end of this like "html:target/html-reports/cucumber-default-report.html"

2024-10-01 20:25 UTC, hamidnesar commented on src/test/java/ServiceNow/ServiceNowRunners/OAIntakeRunners/OAIntakeProgressionRunner.java
> +        , "junit:target/cucumber.xml"
Please remove junit as we no longer use it. line 9

2024-10-01 20:25 UTC, hamidnesar commented on src/test/java/ServiceNow/ServiceNowRunners/OAIntakeRunners/OAIntakeProgressionRunner.java
> +        , "rerun:target/failed.txt", "pretty"}
Add the below:
"com.aventstack.extentreports.cucumber.adapter.ExtentCucumberAdapter:"

2024-10-01 20:25 UTC, hamidnesar commented on src/test/java/ServiceNow/ServiceNowRunners/OAIntakeRunners/OAIntakeRegressionRunner.java
> +    @CucumberOptions(plugin = {"html:target/html-reports/cucumber-default-report"
Please add .html at the end of this like "html:target/html-reports/cucumber-default-report.html"

2024-10-01 20:25 UTC, hamidnesar commented on src/test/java/ServiceNow/ServiceNowRunners/OAIntakeRunners/OAIntakeRegressionRunner.java
> +            , "junit:target/cucumber.xml"
Please remove junit as we no longer use it. line 8

2024-10-01 20:25 UTC, hamidnesar commented on src/test/java/ServiceNow/ServiceNowRunners/OAIntakeRunners/OAIntakeProgressionRunner.java
> +
please delete the empty line 5

2024-10-01 20:25 UTC, hamidnesar commented on src/test/java/ServiceNow/ServiceNowRunners/OAIntakeRunners/OAIntakeRegressionRunner.java
> +            , "rerun:target/failed.txt", "pretty"}
Add the below:
"com.aventstack.extentreports.cucumber.adapter.ExtentCucumberAdapter:"

2024-10-01 21:02 UTC, Mariachaudhry requested changes

2024-10-01 21:02 UTC, Mariachaudhry commented on src/test/java/ServiceNow/OA_Intake/StepsImplementation/OAIntakeStepsImplementation.java
Please add javadoc for the implemented method

2024-10-02 13:50 UTC, alenaminsk commented on src/test/java/ServiceNow/ServiceNowRunners/OAIntakeRunners/OAIntakeProgressionRunner.java
> +
Updated

2024-10-02 13:52 UTC, alenaminsk commented on src/test/java/ServiceNow/ServiceNowRunners/OAIntakeRunners/OAIntakeProgressionRunner.java
> +@CucumberOptions(plugin = {"html:target/html-reports/cucumber-default-report"
Updated

2024-10-02 13:53 UTC, alenaminsk commented on src/test/java/ServiceNow/ServiceNowRunners/OAIntakeRunners/OAIntakeProgressionRunner.java
> +        , "junit:target/cucumber.xml"
Updated

2024-10-02 13:54 UTC, alenaminsk commented on src/test/java/ServiceNow/ServiceNowRunners/OAIntakeRunners/OAIntakeRegressionRunner.java
> +    @CucumberOptions(plugin = {"html:target/html-reports/cucumber-default-report"
Updated

2024-10-02 13:54 UTC, alenaminsk commented on src/test/java/ServiceNow/ServiceNowRunners/OAIntakeRunners/OAIntakeRegressionRunner.java
> +            , "junit:target/cucumber.xml"
Updated

2024-10-02 13:54 UTC, alenaminsk commented on src/test/java/ServiceNow/ServiceNowRunners/OAIntakeRunners/OAIntakeRegressionRunner.java
> +            , "rerun:target/failed.txt", "pretty"}
Updated

2024-10-02 14:16 UTC, alenaminsk commented on src/main/resources/conf/env/test.xml
deleted

2024-10-02 14:18 UTC, sarwarahmed1 commented on src/main/java/com/nci/automation/web/TestProperties.java
> +    public static boolean HEADLESS = false;
Are we permanently changing headless value to false? Please confirm with Diego

2024-10-02 15:15 UTC, alenaminsk commented on src/test/java/ServiceNow/OA_Intake/Steps/OAIntakeSteps.java
updated

2024-10-02 15:15 UTC, alenaminsk commented on src/test/java/ServiceNow/OA_Intake/StepsImplementation/OAIntakeStepsImplementation.java
Added

2024-10-02 15:28 UTC, Mariachaudhry approved these changes

2024-10-02 15:38 UTC, katm007 commented on src/test/java/ServiceNow/OA_Intake/Features/OAIntakeForm.feature
You're tagging this scenario with @Alena but in other feature files you use @Nekrashevich. If you don't need two different tags, then you should choose one and stick with it for consistency

2024-10-02 15:48 UTC, alenaminsk commented on src/test/java/ServiceNow/OA_Intake/Features/OAIntakeForm.feature
updated

2024-10-02 15:49 UTC, alenaminsk commented on src/main/java/com/nci/automation/web/TestProperties.java
> +    public static boolean HEADLESS = false;
updated

2024-10-02 15:56 UTC, sarwarahmed1 approved these changes

2024-10-02 16:19 UTC, hamidnesar requested changes

2024-10-02 16:19 UTC, hamidnesar commented on src/test/java/ServiceNow/OA_Intake/Features/OAIntakeForm.feature
> +  @selenium @OAIntake-576 @OAIntake-544 @OAIntake-575 @OAIntake-499 @OAIntake-657 @OAIntake-430 @OAIntake-408 @OAIntake-623 @Alena @Smoke
This scenario is missing @Regression tag. not sure if you would need to tag it @Smoke

2024-10-02 16:19 UTC, hamidnesar commented on src/test/java/ServiceNow/OA_Intake/Steps/OAIntakeSteps.java
> +    /**
/**
     * Submitter  fills in Request Title field
     * _@param_ _title_
     */

2024-10-02 20:27 UTC, hamidnesar commented on src/test/java/ServiceNow/OA_Intake/Steps/OAIntakeSteps.java
> +     * ubmitter fills in Please enter the estimated value of IT field
Submitter is missing the letter S

2024-10-02 20:28 UTC, hamidnesar approved these changes
Looks good!

2024-10-02 20:39 UTC, hamidnesar approved these changes

2024-10-03 02:31 UTC, merged