[Platform Business Apps] Travel request and OFF-Board Automation -Chaudhryma
CBIIT/CBIIT-Test-Automation pull request #284
Opened 2024-10-01 15:25 UTC by Mariachaudhry

2024-10-01 15:27 UTC, Mariachaudhry reviewed
Reviewed by me!

2024-10-01 20:40 UTC, hamidnesar requested changes
Hi Maria, please review the comments. thanks!

2024-10-01 20:40 UTC, hamidnesar commented on src/test/java/ServiceNow/PlatformBusinessApps/OFFBOARD/Features/CBIIT OffBoarding Form.feature
Are all these scenarios part of the daily scheduled smoke jobs? I see that you have tagged them all @Smoke

2024-10-01 20:40 UTC, hamidnesar commented on src/test/java/ServiceNow/PlatformBusinessApps/OFFBOARD/Steps/CBIIT_OFFBOARD_Form_Steps.java
> +    @When("I select {string} under the {string} field")
This is missing a Javadoc

2024-10-01 20:40 UTC, hamidnesar commented on src/test/java/ServiceNow/PlatformBusinessApps/SNOW_TRAVEL/playwright/Features/Travel_Request_Portal_Form.feature
> +  @SNOWTRAVEL-121 @Chaudhryma @Smoke @Regression @playwright
Just making sure if this test case is going to part of the daily scheduled smoke jobs, if not, @Smoke can be removed

2024-10-01 20:40 UTC, hamidnesar commented on src/test/java/ServiceNow/PlatformBusinessApps/SNOW_TRAVEL/playwright/Steps/Travel_Request_Portal_Form_Steps.java
> +        CucumberLogUtils.playwrightScreenshot(page);
These two steps are missing Javadocs,

2024-10-01 20:42 UTC, Mariachaudhry commented on src/test/java/ServiceNow/PlatformBusinessApps/SNOW_TRAVEL/playwright/Features/Travel_Request_Portal_Form.feature
> +  @SNOWTRAVEL-121 @Chaudhryma @Smoke @Regression @playwright
That is the plan!

2024-10-01 20:46 UTC, Mariachaudhry commented on src/test/java/ServiceNow/PlatformBusinessApps/SNOW_TRAVEL/playwright/Steps/Travel_Request_Portal_Form_Steps.java
> +        CucumberLogUtils.playwrightScreenshot(page);
added

2024-10-01 20:49 UTC, Mariachaudhry commented on src/test/java/ServiceNow/PlatformBusinessApps/OFFBOARD/Features/CBIIT OffBoarding Form.feature
I added smoke tags, once Regression job is scheduled then smoke will be removed

2024-10-01 20:57 UTC, hamidnesar approved these changes
Reviewed, looks good!

2024-10-02 14:09 UTC, sarwarahmed1 approved these changes
Looks good!

2024-10-02 14:14 UTC, katm007 approved these changes

2024-10-02 14:32 UTC, merged