CHARMS RAS changed tags to @RAS_Regression tags
CBIIT/CBIIT-Test-Automation pull request #285
Opened 2024-10-01 16:50 UTC by katm007

Minor changes so that GitHub Actions can run.

2024-10-01 20:16 UTC, sarwarahmed1 approved these changes

2024-10-01 20:46 UTC, hamidnesar requested changes
Hi Kate, please review the comments.

2024-10-01 20:46 UTC, hamidnesar commented on src/test/java/ServiceNow/CHARMS/Features/RasopathyStudy/RAS Consent Scenarios.feature
> +  @muzipovay2 @RAS_STUDY @CP2-3603 @CP2-3637 @selenium @RAS_Regression @In-Progress
We do not have @RAS_Regression tag. You can either use Regression, Smoke or @In-Progress tags. You are not supposed to tag a scenario @Regression and @In-Progress at the same time. @Regression means it is a complete test case

2024-10-01 20:46 UTC, hamidnesar commented on src/test/java/ServiceNow/CHARMS/StepsImplementation/RASStudy/RAS_Screener_Submissions_StepsImpl.java
public static void rasScreenerSubmissions(String sheetName)  on line 85 is missing Javadoc

2024-10-01 20:46 UTC, hamidnesar commented on src/test/java/ServiceNow/CHARMS/Features/RasopathyStudy/RAS Consent Scenarios.feature
We do not have @RAS_Regression tag. For consistency across the framework, you can either use Regression, Smoke or @in-progress tags

2024-10-01 20:57 UTC, Mariachaudhry requested changes

2024-10-01 20:57 UTC, Mariachaudhry commented on src/test/java/ServiceNow/CHARMS/Constants/CHARMS_Data_File_Path_Constants.java
extra line 16 can be deleted!

2024-10-01 20:57 UTC, Mariachaudhry commented on src/test/java/ServiceNow/CHARMS/Features/RasopathyStudy/RAS Consent Scenarios.feature
Is the commented line 22 needed?

2024-10-01 20:57 UTC, Mariachaudhry commented on src/test/java/ServiceNow/CHARMS/StepsImplementation/RASStudy/RAS_Screener_Submissions_StepsImpl.java
Javadoc missing for few methods.  line 1388, 1663, 1691, 1846, 1872, 1933

2024-10-02 13:59 UTC, katm007 commented on src/test/java/ServiceNow/CHARMS/Features/RasopathyStudy/RAS Consent Scenarios.feature
Yes, I'm still working on it. It's commented out because I wanted to start running the finished scenarios in regression.

2024-10-02 14:06 UTC, katm007 commented on src/test/java/ServiceNow/CHARMS/StepsImplementation/RASStudy/RAS_Screener_Submissions_StepsImpl.java
Added javadocs.

2024-10-02 14:06 UTC, katm007 commented on src/test/java/ServiceNow/CHARMS/StepsImplementation/RASStudy/RAS_Screener_Submissions_StepsImpl.java
Added javadoc

2024-10-02 14:07 UTC, katm007 commented on src/test/java/ServiceNow/CHARMS/Constants/CHARMS_Data_File_Path_Constants.java
Deleted it

2024-10-02 14:07 UTC, katm007 commented on src/test/java/ServiceNow/CHARMS/Features/RasopathyStudy/RAS Consent Scenarios.feature
The reason we use @RAS_Regression is because we have a runners pointing the same feature file package with other studies and we don’t want to run other studies together.

2024-10-02 14:24 UTC, hamidnesar approved these changes
Looks good!

2024-10-02 14:28 UTC, Mariachaudhry requested changes

2024-10-02 14:28 UTC, Mariachaudhry commented on src/main/java/com/nci/automation/web/TestProperties.java
please update the Headless to true, we cannot push the false to master.

2024-10-02 14:39 UTC, katm007 commented on src/main/java/com/nci/automation/web/TestProperties.java
Done!

2024-10-02 14:50 UTC, Mariachaudhry approved these changes

2024-10-02 14:50 UTC, merged