ESR Short Descriptions Field Validation
CBIIT/CBIIT-Test-Automation pull request #286
Opened 2024-10-01 20:06 UTC by sarwarahmed1

Reviewed

2024-10-01 20:12 UTC, hamidnesar requested changes
Hi, please review the comment

2024-10-01 20:12 UTC, hamidnesar commented on src/test/java/ServiceNow/ESR/Playwright/Features/ESRShortDescription.feature
> +  @ESR-528 @sarwarahmed1 @Progression @playwright
Per Diego, please tag these scenarios @In-Progress if you are still working on them

2024-10-01 20:50 UTC, Mariachaudhry approved these changes

2024-10-02 14:04 UTC, sarwarahmed1 commented on src/test/java/ServiceNow/ESR/Playwright/Features/ESRShortDescription.feature
> +  @ESR-528 @sarwarahmed1 @Progression @playwright
Forgot to change them, should be regression tags

2024-10-02 14:15 UTC, hamidnesar approved these changes
Reviewed and approved!

2024-10-02 15:41 UTC, katm007 approved these changes
approved!

2024-10-02 15:50 UTC, merged