OA Intake Home Page tabs and options for Submitter and Leadership Users
CBIIT/CBIIT-Test-Automation pull request #292
Opened 2024-10-16 17:04 UTC by alenaminsk

OA Intake Home Page tabs and options for Submitter and Leadership Users

2024-10-16 17:53 UTC, hamidnesar requested changes
Hi, 
Please review the comments. Thanks!

2024-10-16 17:53 UTC, hamidnesar commented on src/test/java/ServiceNow/OA_Intake/Features/OAIntakeForm.feature
> +  @selenium @OAIntake-576 @OAIntake-544 @OAIntake-575 @OAIntake-499 @OAIntake-657 @OAIntake-430 @OAIntake-408 @OAIntake-623 @Alena
This scenario is missing @Regression and it should be tagged @Smoke if needed

2024-10-16 17:53 UTC, hamidnesar commented on src/test/java/ServiceNow/OA_Intake/Features/OAIntakeForm.feature
> +
Please remove the empty line 35

2024-10-16 17:53 UTC, hamidnesar commented on src/test/java/ServiceNow/OA_Intake/Features/OAIntakeForm.feature
> +  @selenium @Alena @Smoke @OAIntake-8 @OAIntake-417 @OAIntake-425 @OAIntake-426 @OAIntake-439 @OAIntake-260 @OAIntake-261 @OAIntake-263
This scenario is missing @Regression

2024-10-16 17:53 UTC, hamidnesar commented on src/test/java/ServiceNow/OA_Intake/Features/OAIntakeForm.feature
> +
Please delete empty lines 74-87

2024-10-16 17:53 UTC, hamidnesar commented on src/test/java/ServiceNow/OA_Intake/Steps/OAIntakeSteps.java
> +        Assert.assertTrue(oaIntakePage.pageHeaderOAIntake.isDisplayed());
You could replace Assert with the one we have in the CommonUtils class and use it across this class. CommonUtils.assertTrue(). 

If you decided replacing it, then remove the testNG import as well.

2024-10-16 17:53 UTC, hamidnesar commented on src/test/java/ServiceNow/OA_Intake/Steps/OAIntakeSteps.java
You could replace Assert with the one we have in the CommonUtils and use it across this class. CommonUtils.assertTrue().

If you decided replacing it, then remove the testNG import as well.

2024-10-16 17:53 UTC, hamidnesar commented on src/test/java/ServiceNow/OA_Intake/StepsImplementation/OAIntakeStepsImplementation.java
> +import org.testng.Assert;
You could replace Assert with the one we have in the CommonUtils class and use it across this class. CommonUtils.assertTrue().

If you decided replacing it, then remove the testNG import as well.

2024-10-16 17:57 UTC, katm007 commented on src/test/java/ServiceNow/OA_Intake/StepsImplementation/OAIntakeStepsImplementation.java
Please remove the empty line11 between imports

2024-10-17 15:32 UTC, alenaminsk commented on src/test/java/ServiceNow/OA_Intake/Features/OAIntakeForm.feature
> +  @selenium @OAIntake-576 @OAIntake-544 @OAIntake-575 @OAIntake-499 @OAIntake-657 @OAIntake-430 @OAIntake-408 @OAIntake-623 @Alena
updated

2024-10-17 15:32 UTC, alenaminsk commented on src/test/java/ServiceNow/OA_Intake/Features/OAIntakeForm.feature
> +
updated

2024-10-17 15:33 UTC, alenaminsk commented on src/test/java/ServiceNow/OA_Intake/Features/OAIntakeForm.feature
> +  @selenium @Alena @Smoke @OAIntake-8 @OAIntake-417 @OAIntake-425 @OAIntake-426 @OAIntake-439 @OAIntake-260 @OAIntake-261 @OAIntake-263
added

2024-10-17 15:34 UTC, alenaminsk commented on src/test/java/ServiceNow/OA_Intake/Features/OAIntakeForm.feature
> +
deleted

2024-10-17 15:35 UTC, alenaminsk commented on src/test/java/ServiceNow/OA_Intake/Steps/OAIntakeSteps.java
kept Test ng for assertions

2024-10-17 15:35 UTC, alenaminsk commented on src/test/java/ServiceNow/OA_Intake/Steps/OAIntakeSteps.java
> +        Assert.assertTrue(oaIntakePage.pageHeaderOAIntake.isDisplayed());
Kept testNG  for assertions

2024-10-17 15:36 UTC, alenaminsk commented on src/test/java/ServiceNow/OA_Intake/StepsImplementation/OAIntakeStepsImplementation.java
updated

2024-10-17 15:49 UTC, hamidnesar requested changes

2024-10-17 15:49 UTC, hamidnesar commented on src/test/java/ServiceNow/OA_Intake/Features/OAIntakeForm.feature
> +
Please remove the empty lines 73-83

2024-10-17 15:55 UTC, hamidnesar approved these changes
Reviewed and approved!

2024-10-17 15:59 UTC, sarwarahmed1 approved these changes

2024-10-17 19:58 UTC, matakevin approved these changes
LGTM -- Thank you!

2024-10-17 19:59 UTC, Mariachaudhry approved these changes

2024-10-17 19:59 UTC, merged