APPTRACK-127 Verify the edit application functionality from review application page
CBIIT/CBIIT-Test-Automation pull request #293
Opened 2024-10-16 20:00 UTC by lfcabrera14

APPTRACK-127 Verify the edit application functionality from review application page

2024-10-17 14:29 UTC, sarwarahmed1 requested changes

2024-10-17 14:29 UTC, sarwarahmed1 commented on src/test/java/ServiceNow/PlatformBusinessApps/SSJ/playwright/Utils/SSJ_Common_Utils.java
Please remove space on line 10

2024-10-17 14:47 UTC, lfcabrera14 commented on src/test/java/ServiceNow/PlatformBusinessApps/SSJ/playwright/Utils/SSJ_Common_Utils.java
done

2024-10-17 14:57 UTC, sarwarahmed1 approved these changes

2024-10-17 15:41 UTC, hamidnesar requested changes
Hi, 
Please review the comments. Thanks!

2024-10-17 15:41 UTC, hamidnesar commented on src/test/java/ServiceNow/PlatformBusinessApps/SSJ/playwright/Steps/ApplicantProfileSteps.java
also remove empty line 748

2024-10-17 15:45 UTC, lfcabrera14 commented on src/test/java/ServiceNow/PlatformBusinessApps/SSJ/playwright/Steps/ApplicantProfileSteps.java
done

2024-10-17 15:46 UTC, hamidnesar approved these changes
Looks good!

2024-10-18 16:54 UTC, Mariachaudhry approved these changes

2024-10-18 16:59 UTC, merged