Added the Reproductive History section to the Fanconi Survey
CBIIT/CBIIT-Test-Automation pull request #297
Opened 2024-10-18 17:20 UTC by sonika-nih

Added the Reproductive History section to the Fanconi Survey in Playwright

2024-10-18 20:29 UTC, Mariachaudhry requested changes

2024-10-18 20:29 UTC, Mariachaudhry commented on src/test/java/ServiceNow/CHARMS/Steps/FHQChildRecordProducerSteps.java
There are some extra lines in Imports and within methods to remove.

2024-10-21 13:45 UTC, hamidnesar requested changes
Hi, 
Please review the comments. Thank you!

2024-10-21 13:45 UTC, hamidnesar commented on src/test/java/ServiceNow/CHARMS/Features/FHQ/FHQSubmission.feature
> +  @jains @FHQSubmissionInPortal @CP2-562 @CP2-930 @CP2-559 @Regression1 @selenium
Please modify the tag to @Regression

2024-10-21 13:45 UTC, hamidnesar commented on src/test/java/ServiceNow/CHARMS/Features/FHQ/FHQSubmission.feature
> +  @jains @FHQSubmissionInPortal @CP2-603 @CP2-1020 @Regression1 @selenium
Modify the tag to @Regression.
Regression vs Regression1

2024-10-21 13:45 UTC, hamidnesar commented on src/test/java/ServiceNow/CHARMS/Runners/RunCHARMSFHQRegressionTest.java
> +tags = "@Regression1",
Regression vs Regression1

2024-10-21 13:45 UTC, hamidnesar commented on src/test/java/ServiceNow/CHARMS/Steps/FHQChildRecordProducerSteps.java
1. Please remove empty lines: 
4, 26, 28, 31, 34, 36, 41, 43, 46, 48, 193, 229, 232, 235, 241, 244, 247, 250, 253, 256, 259, 262, 268, 271, 285, 294, 297, 300, 304, 307, 312, 314, and _MANY MORE_ throughout the class. 

2. Methods on line 51, 95, 118, 160, 174, 184, 203, 213, 227, 289 and _MANY MORE_ throughout the class are missing Javadoc comments.

2024-10-21 13:57 UTC, Mariachaudhry approved these changes

2024-10-21 14:13 UTC, hamidnesar requested changes
Hi, 
Please review the comments. thanks

2024-10-21 14:13 UTC, hamidnesar commented on src/test/java/ServiceNow/CHARMS/Steps/FHQChildRecordProducerSteps.java
Methods on line 32, 40, 84, 107, 149, 163, 173, 191, 201, and _MANY MORE_ throughout the class are missing Javadoc comments.

2024-10-21 14:22 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/Steps/FHQChildRecordProducerSteps.java
Done

2024-10-21 15:10 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/Steps/FHQChildRecordProducerSteps.java
old code. WIll do the cleaning as time permits

2024-10-21 15:10 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/Features/FHQ/FHQSubmission.feature
> +  @jains @FHQSubmissionInPortal @CP2-562 @CP2-930 @CP2-559 @Regression1 @selenium
done

2024-10-21 15:11 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/Features/FHQ/FHQSubmission.feature
> +  @jains @FHQSubmissionInPortal @CP2-603 @CP2-1020 @Regression1 @selenium
Done

2024-10-21 15:35 UTC, iamdez99 requested changes
Please see comments.

2024-10-21 15:35 UTC, iamdez99 commented on src/test/java/ServiceNow/CHARMS/Runners/Run_CHARMS_Fanconi_Regression_Test.java
Can you please change this tag to @Fanconi_Regression? And update all fanconi regression scenarios with this tag.

2024-10-21 15:35 UTC, iamdez99 commented on src/test/java/ServiceNow/CHARMS/Features/FHQ/FHQSubmission.feature
I think charmsras1@yahoo.com is the account I use for my tests. Will there be any issues if you use it here?

2024-10-21 15:35 UTC, iamdez99 commented on src/test/java/ServiceNow/CHARMS/Pages/FHQSurveyPortalPage.java
For the xpath, you are pasting a String within a String, thats why it looks like "//span[normalize-space()=\"Are any of the following individuals a biological parent of this child?\"]", instead it should be "//span[normalize-space()='Are any of the following individuals a biological parent of this child?']"

2024-10-21 15:35 UTC, iamdez99 commented on src/test/java/ServiceNow/CHARMS/Runners/RunCHARMSFHQRegressionTest.java
Can you please change this tag @FHQ_Regression and update all FHQ regression scenarios with this tag.

2024-10-21 17:06 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/Runners/RunCHARMSFHQRegressionTest.java
Done

2024-10-21 17:08 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/Features/FHQ/FHQSubmission.feature
Changed to another test account

2024-10-21 17:12 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/Runners/Run_CHARMS_Fanconi_Regression_Test.java
Done

2024-10-21 17:26 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/Pages/FHQSurveyPortalPage.java
This is another way of writing the xpath. both works. For eg given below are both correct
 (//*[contains(text(),"sub-title")])
(//*[contains(text(),'sub-title')])

2024-10-21 17:56 UTC, hamidnesar approved these changes
Reviewed and approved!

2024-10-22 18:39 UTC, iamdez99 approved these changes

2024-10-22 18:41 UTC, merged