eGrants - Add and remove flag maintenance for a grant year
CBIIT/CBIIT-Test-Automation pull request #298
Opened 2024-10-18 20:20 UTC by hamidnesar

2024-10-18 20:21 UTC, hamidnesar commented
Reviewed

2024-10-18 20:25 UTC, Mariachaudhry approved these changes

2024-10-18 20:25 UTC, Mariachaudhry approved these changes

2024-10-21 15:27 UTC, iamdez99 requested changes
Please see comments.

2024-10-21 15:27 UTC, iamdez99 commented on src/test/java/CustomBusiness/Egrants/Steps/QuickLinkVerificationAndManagementMenuSteps.java
You have a 3 second hard sleep before handling an alert. This is okay for now but we should create a common method later to wait for an alert to be present.

2024-10-21 15:27 UTC, iamdez99 commented on src/test/java/CustomBusiness/Egrants/StepsImplementation/EgrantsStepImplementation.java
Can you please use the SoftAssert from the Hooks class?

2024-10-21 16:49 UTC, hamidnesar commented on src/test/java/CustomBusiness/Egrants/Steps/QuickLinkVerificationAndManagementMenuSteps.java
I will make sure to create a common method in my next PR

2024-10-21 16:50 UTC, hamidnesar commented on src/test/java/CustomBusiness/Egrants/StepsImplementation/EgrantsStepImplementation.java
Replaced the hard asserts with SoftAssert

2024-10-22 19:01 UTC, iamdez99 requested changes

2024-10-22 19:01 UTC, iamdez99 commented on src/test/java/CustomBusiness/Egrants/StepsImplementation/EgrantsStepImplementation.java
Please remove line 12

2024-10-22 19:01 UTC, iamdez99 requested changes
Please view comments

2024-10-22 20:45 UTC, iamdez99 approved these changes

2024-10-22 20:45 UTC, merged