CHARMS Verifying FSID in Native View after creating new participant through Add New Participant page.
CBIIT/CBIIT-Test-Automation pull request #300
Opened 2024-10-21 21:28 UTC by katm007

FSID verifications in Native View.

2024-10-22 14:00 UTC, hamidnesar requested changes
Hi, 
please review the comments. Thanks!

2024-10-22 14:19 UTC, katm007 commented on src/test/java/ServiceNow/CHARMS/Steps/RAS_Common_Methods.java
> +
Done!

2024-10-22 14:19 UTC, katm007 commented on src/test/java/ServiceNow/CHARMS/Steps/RAS_All_Steps.java
> +     * @param sheetName the name of the sheet for which the consent is being processed
Added the second parameter

2024-10-22 20:54 UTC, iamdez99 requested changes
Please review comments.

2024-10-22 20:54 UTC, iamdez99 commented on src/test/java/ServiceNow/CHARMS/StepsImplementation/RASStudy/RAS_Screener_Submissions_StepsImpl.java
Please use soft assert from the Hooks class instead of CommonUtils

2024-10-22 20:54 UTC, iamdez99 commented on src/test/java/ServiceNow/CHARMS/Steps/RAS_Common_Methods.java
Please update your assertions to use the soft assert from the Hooks class not CommonUtils.

2024-10-22 20:54 UTC, iamdez99 commented on src/test/java/ServiceNow/CHARMS/Features/RasopathyStudy/RAS Consent Scenarios.feature
A scenario should not be tagged Regression if it is in progress.

2024-10-22 21:32 UTC, katm007 commented on src/test/java/ServiceNow/CHARMS/StepsImplementation/RASStudy/RAS_Screener_Submissions_StepsImpl.java
What do I do about the message logging? The hooks class doesn't have anything like CommonUtils.assertEqualsWithMessage()

2024-10-23 17:54 UTC, hamidnesar requested changes
Hi, 
please review the comment.

2024-10-23 17:54 UTC, hamidnesar commented on src/test/java/ServiceNow/CHARMS/Steps/RAS_All_Steps.java
> +
Please remove empty line 19

2024-10-23 18:37 UTC, katm007 commented on src/test/java/ServiceNow/CHARMS/Steps/RAS_All_Steps.java
> +
Removed

2024-10-23 19:15 UTC, matakevin requested changes
Please review requested changes

2024-10-23 19:21 UTC, katm007 commented on src/test/java/ServiceNow/CHARMS/Features/RasopathyStudy/RAS Consent Scenarios.feature
> +  @muzipovay2 @RAS_STUDY @selenium @In-Progress
There is no ticket number, this is just so I can test the new consent script. I will remove it after everything is complete.

2024-10-23 19:22 UTC, katm007 commented on src/test/java/ServiceNow/CHARMS/Features/RasopathyStudy/RAS Entire Flow.feature
Yes, they're needed. This is Diego's in-progress code

2024-10-23 19:22 UTC, katm007 commented on src/test/java/ServiceNow/CHARMS/Features/RasopathyStudy/RAS Consent Scenarios.feature
> +  Scenario: Consent Call
Same as above this is just so I can test the new consent script. I will remove it after everything is complete.

2024-10-23 19:26 UTC, katm007 commented on src/test/java/ServiceNow/CHARMS/Pages/NativeViewCHARMSAddNewParticipantPage.java
> +    public WebElement warningFSIDWillNotGenerateForOtherOrUnknownRelationshipText;
I will try, but it's not possible in this case. The alternative is calling these question 1, question 2.. and so on but then it's hard to tell which question is which.

2024-10-23 19:29 UTC, katm007 commented on src/test/java/ServiceNow/CHARMS/Pages/NativeViewCHARMSParticipantDetailsPage.java
Most of these pages weren't written by me. These are javadocs, they're just formatted differently

2024-10-23 19:35 UTC, matakevin approved these changes
LGTM

2024-10-23 20:59 UTC, hamidnesar approved these changes

2024-10-24 14:30 UTC, Mariachaudhry approved these changes

2024-10-24 14:30 UTC, merged