Analysis Tools - Implemented test cases for multiple applications(NIFESubmit, FORGEdb and BCRAT)
CBIIT/CBIIT-Test-Automation pull request #303
Opened 2024-10-24 19:45 UTC by sgugulothu

Analysis Tools - Implemented test cases for multiple applications(NIFESubmit, FORGEdb and BCRAT)

2024-10-24 21:44 UTC, hamidnesar requested changes
Hi, 
Please review the comments

2024-10-24 21:44 UTC, hamidnesar commented on src/test/java/AnalysisTools/BCRAT/BCRAT_Runner/RunBCRATProgressionTest.java
> +		, glue = "AnalysisTools.BCRAT.playwright.Steps"
You need to use the universal Hooks: , glue = {"AnalysisTools.BCRAT.playwright.Steps","Hooks"}

2024-10-24 21:44 UTC, hamidnesar commented on src/test/java/AnalysisTools/BCRAT/BCRAT_Runner/RunBCRATRegressionTest.java
> +		, glue = "AnalysisTools.BBCRAT.playwright.Steps"
You need to use the universal Hooks: , glue = {"AnalysisTools.BCRAT.playwright.Steps","Hooks"}

2024-10-24 21:44 UTC, hamidnesar commented on src/test/java/AnalysisTools/CometsAnalytics/StepsImplementation/CometsAnalyticsStepImp.java
Please delete empty line 4

2024-10-24 21:44 UTC, hamidnesar commented on src/test/java/AnalysisTools/FORGEdb/FORGEdb_Runner/RunFORGEdbProgressionTest.java
> +		, glue = "AnalysisTools.FORGEdb.playwright.Steps"
You need to use the universal Hooks: , glue = {"AnalysisTools.FORGEdb.playwright.Steps","Hooks"}

2024-10-24 21:44 UTC, hamidnesar commented on src/test/java/AnalysisTools/FORGEdb/FORGEdb_Runner/RunFORGEdbRegressionTest.java
> +		, glue = "AnalysisTools.FORGEdb.playwright.Steps"
You need to use the universal Hooks: , glue = {"AnalysisTools.FORGEdb.playwright.Steps","Hooks"}

2024-10-24 21:44 UTC, hamidnesar commented on src/test/java/AnalysisTools/FORGEdb/playwright/Pages/FORGEdbPage.java
> +    public static String here = "here";
Is "here" a valid locator?

2024-10-24 21:44 UTC, hamidnesar commented on src/test/java/AnalysisTools/FORGEdb/playwright/StepsImplementation/FORGEdbStepsImpl.java
> +            soft.assertEquals(str, FORGEdbPage.doneText);
Please use the Soft Assert from the Hooks class

2024-10-24 21:44 UTC, hamidnesar commented on src/test/java/AnalysisTools/FORGEdb/playwright/StepsImplementation/FORGEdbStepsImpl.java
Please use the Soft Assert from the Hooks class. You could use Hard Assertion if needed, otherwise use Soft Assert if you want your test case to continue execution. There are pre-implemented try and catch blocks in the @after method within Hooks class that will print the assertions details.

2024-10-24 21:44 UTC, hamidnesar commented on src/test/java/AnalysisTools/NIFESubmit/playwright/Features/NIFESubmit.feature
> +  @satya @Smoke @Regression @playwright
Please add the Jira storyId if available

2024-10-24 21:44 UTC, hamidnesar commented on src/test/java/AnalysisTools/NIFESubmit/playwright/Features/NIFESubmit.feature
> +  @satya @Smoke @Regression @playwright
Please add the Jira storyId if available

2024-10-24 21:44 UTC, hamidnesar commented on src/test/java/AnalysisTools/NIFESubmit/playwright/StepsImplementation/NIFESubmitStepsImpl.java
> +        CommonUtils.sleep(2000);
There too many static waits. I would recommend using dynamic waits

2024-10-24 21:44 UTC, hamidnesar commented on src/test/java/AnalysisTools/Soccer/playwright/Steps/Soccer_Steps.java
> +        System.out.println(getSoccerUrl());
This print statement is not necessary for the functionality of navigating to the soccer home page. it's only beneficial for debugging and logging purposes.

2024-10-24 21:44 UTC, hamidnesar commented on src/test/java/AnalysisTools/Soccer/playwright/Steps/Soccer_Steps.java
> +
Please delete the empty line

2024-10-25 15:43 UTC, sgugulothu commented on src/test/java/AnalysisTools/FORGEdb/playwright/Pages/FORGEdbPage.java
> +    public static String here = "here";
Yes it is valid locater

2024-10-28 16:29 UTC, sgugulothu commented on src/test/java/AnalysisTools/NIFESubmit/playwright/StepsImplementation/NIFESubmitStepsImpl.java
> +        CommonUtils.sleep(2000);
I have removed the extra one which i used while execution

2024-10-28 16:46 UTC, sgugulothu commented on src/test/java/AnalysisTools/FORGEdb/playwright/StepsImplementation/FORGEdbStepsImpl.java
> +            soft.assertEquals(str, FORGEdbPage.doneText);
Instead of soft assert, I replaced it with hard assert.

2024-10-29 14:21 UTC, hamidnesar requested changes
Hi, 
Please review the comments. Thanks!

2024-10-29 14:21 UTC, hamidnesar commented on src/main/java/com/nci/automation/web/TestProperties.java
> +    public static final String NIFE_TEST_URL = "https://nife-dev.cancer.gov/";
The String is name as TEST URL but the provided URL points to Dev. Please either rename the String or provide the Test URL.

2024-10-29 14:21 UTC, hamidnesar commented on src/test/java/AnalysisTools/CometsAnalytics/CometsAnalyticsRunners/RunCometsAnalyticsProgressionTest.java
> +        , glue = {"AnalysisTools.CometsAnalystics.Steps", "c"}
Please replace C with Hooks

2024-10-29 14:21 UTC, hamidnesar commented on src/test/java/AnalysisTools/CometsAnalytics/StepsImplementation/CometsAnalyticsStepImp.java
Please delete the empty line 4 among the imports

2024-10-29 14:21 UTC, hamidnesar commented on src/test/java/AnalysisTools/FORGEdb/playwright/StepsImplementation/FORGEdbStepsImpl.java
> +import org.testng.asserts.SoftAssert;
Please remove the unused import line 15 (SoftAssert)

2024-10-29 15:22 UTC, hamidnesar requested changes
Hi, please see the comments. thanks!

2024-10-29 15:22 UTC, hamidnesar commented on src/main/java/com/nci/automation/web/TestProperties.java
> +     * NIFE URLSSSS
Please remove the extra letter S

2024-10-29 15:22 UTC, hamidnesar commented on src/main/java/com/nci/automation/web/TestProperties.java
> +    public static final String NIFE_TEST_URL = "https://nife-Test.cancer.gov/";
For consistency, it is better to write Test with lowercase t in the URL

2024-10-29 18:24 UTC, hamidnesar approved these changes
Approved

2024-10-29 21:39 UTC, alenaminsk approved these changes

2024-10-30 00:39 UTC, sonika-nih approved these changes
Approved

2024-10-30 11:45 UTC, merged