CHARMS: Added new code to FHQ Child Record Producer to address the enhancements in FHQ
CBIIT/CBIIT-Test-Automation pull request #307
Opened 2024-10-29 17:03 UTC by sonika-nih

CHARMS: Added new code to FHQ Child Record Producer to address the Biological child Parents enhancements in FHQ.

2024-10-29 17:08 UTC, katm007 commented on src/test/java/ServiceNow/CHARMS/Features/FHQ/FHQPatientPersonalRecordProducer.feature
Can these scenarios be added to regression?

2024-10-29 17:10 UTC, katm007 commented on src/test/java/ServiceNow/CHARMS/ScenariosData/FHQ_TestDataManager.java
> +	//public String pleaseIdentifyTheNumberOfEachOfTheFollowingPregnancyResultsForThisPerson;
Can line 228 be removed, or is it needed?

2024-10-29 17:11 UTC, katm007 commented on src/test/java/ServiceNow/CHARMS/ScenariosData/FHQ_TestDataManager.java
> +//	public String addAdditionalInformationForAuntUncle;
Same for line 266, can it be removed or is it needed?

2024-10-29 17:14 UTC, katm007 commented on src/test/java/ServiceNow/CHARMS/StepsImplementation/FHQSubmissionStepsImpl.java
> +		};
On line 1416, there shouldn't be a ; following the curly bracket.

2024-10-30 17:28 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/Features/FHQ/FHQPatientPersonalRecordProducer.feature
I need to update them as per enhancements. Will add them after updating the scripts

2024-10-30 17:33 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/ScenariosData/FHQ_TestDataManager.java
> +//	public String addAdditionalInformationForAuntUncle;
Removed

2024-10-30 17:35 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/StepsImplementation/FHQSubmissionStepsImpl.java
> +		};
Removed

2024-10-31 19:35 UTC, matakevin requested changes
Please review my comments and make necessary changes

2024-10-31 19:35 UTC, matakevin commented on src/test/java/ServiceNow/CHARMS/Features/FanconiStudy/FanconiEligibilityQuestionnaire.feature
> +  @jains @FanconiSubmission @CP2-1949 @Fanconi_Regression @selenium @Smoke1
The Smoke1 tag shouldn't be pushed to master

2024-10-31 19:35 UTC, matakevin commented on src/test/java/ServiceNow/CHARMS/Pages/FHQSubmissionPage.java
> +//	@FindBy(xpath = "(//div[@id='select2-result-label-206'])[1]")
Are these commented out lines needed?  Normal we don't want these on master but I know charms has some exceptions

2024-10-31 19:35 UTC, matakevin commented on src/test/java/ServiceNow/CHARMS/Runners/Run_CHARMS_Fanconi_Smoke_Test.java
> +        tags = "@Smoke1",
We don't change these runners tags.  Its a Smoke runner not a Smoke1 runner.  If you want to test something or something's in progress, we have the progression runner

2024-10-31 19:35 UTC, matakevin commented on src/test/java/ServiceNow/CHARMS/ScenariosData/FHQ_TestDataManager.java
> +	//public String pleaseIdentifyTheNumberOfEachOfTheFollowingPregnancyResultsForThisPerson;
seconded

2024-10-31 19:35 UTC, matakevin commented on src/test/java/ServiceNow/CHARMS/StepsImplementation/FHQSubmissionStepsImpl.java
It'd be nice to space out the methods and leave an empty line to differentiate when one starts and when one ends.

2024-10-31 19:35 UTC, matakevin commented on src/test/java/ServiceNow/CHARMS/Utils/CharmsUtil.java
> +
remove these empty lines

2024-10-31 19:35 UTC, matakevin commented on src/test/java/ServiceNow/CHARMS/Utils/CharmsUtil.java
> +	public static void clickAutoPopulatedReference (WebElement webElement, List<String> referenceElements, String dropDownValue){
Same with these, they should have an empty line to separate from the previous method.  Otherwise it looks a little congested and sometimes hard to read

2024-11-01 20:14 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/Features/FHQ/FHQPatientPersonalRecordProducer.feature
I added the  @InProgress tag

2024-11-01 20:15 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/ScenariosData/FHQ_TestDataManager.java
> +	//public String pleaseIdentifyTheNumberOfEachOfTheFollowingPregnancyResultsForThisPerson;
removed

2024-11-01 20:16 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/Features/FanconiStudy/FanconiEligibilityQuestionnaire.feature
> +  @jains @FanconiSubmission @CP2-1949 @Fanconi_Regression @selenium @Smoke1
Removed

2024-11-01 20:16 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/Pages/FHQSubmissionPage.java
> +//	@FindBy(xpath = "(//div[@id='select2-result-label-206'])[1]")
Removed the commented lines where not needed

2024-11-01 20:17 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/Runners/Run_CHARMS_Fanconi_Smoke_Test.java
> +        tags = "@Smoke1",
removed

2024-11-01 20:28 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/StepsImplementation/FHQSubmissionStepsImpl.java
Done

2024-11-01 20:28 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/Utils/CharmsUtil.java
> +
Removed

2024-11-01 20:30 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/Utils/CharmsUtil.java
> +	public static void clickAutoPopulatedReference (WebElement webElement, List<String> referenceElements, String dropDownValue){
Done

2024-11-04 15:06 UTC, matakevin requested changes
Please review requested changes.  Thank you!

2024-11-04 17:59 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/Playwright/StepsImplementation/SMS/SMSStepsImpl.java
> +
Removed Empty lines.

2024-11-04 17:59 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/ScenariosData/FHQ_TestDataManager.java
> +	//public String pleaseIdentifyTheNumberOfEachOfTheFollowingPregnancyResultsForThisPerson;
Removed commented lines

2024-11-04 18:01 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/ScenariosData/FHQ_TestDataManager.java
> +//	public String addAdditionalInformationForAuntUncle;
266 line removed

2024-11-04 18:16 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/StepsImplementation/FanconiEligibilityQuestionnaireStepsImpl.java
> +//        }
Yes, it is needed but put on hold so that It can be updated based on new enhancement.

2024-11-04 18:29 UTC, katm007 commented on src/test/java/ServiceNow/CHARMS/StepsImplementation/FanconiEligibilityQuestionnaireStepsImpl.java
> +        for (int i = 0; i <= 0; i++) {
this loop will only run once? If that's the case, isn't it better to remove it and just leave the statements inside the body?

2024-11-04 19:00 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/StepsImplementation/FanconiEligibilityQuestionnaireStepsImpl.java
> +        for (int i = 0; i <= 0; i++) {
i was testing this part of code but forgot to add the loop number. added back now

2024-11-04 20:09 UTC, katm007 approved these changes
Approved

2024-11-05 16:24 UTC, matakevin approved these changes
LGTM

2024-11-05 17:38 UTC, sarwarahmed1 requested changes

2024-11-05 17:38 UTC, sarwarahmed1 commented on src/main/java/com/nci/automation/web/TestProperties.java
> -    public static boolean HEADLESS = true;
Headless value should always remain true, please change it back

2024-11-05 17:38 UTC, sarwarahmed1 commented on src/test/java/ServiceNow/CHARMS/Pages/FHQSubmissionPage.java
> +	/* Which of the following individuals is a biological parent of this child? Selected Dropdown*/
Are these commented lines needed?

2024-11-05 17:38 UTC, sarwarahmed1 commented on src/test/java/ServiceNow/CHARMS/Pages/FHQSubmissionPage.java
> +	//@FindBy(xpath = "(//span[@id='select2-chosen-24'])[1]")
Same over here, there are commented lines

2024-11-05 17:38 UTC, sarwarahmed1 commented on src/test/java/ServiceNow/CHARMS/Playwright/StepsImplementation/SMS/SMSStepsImpl.java
> +    /* This method allows the login to the RAS Study screener page */
Please use the correct Java Doc format for this method

2024-11-05 18:37 UTC, sonika-nih commented on src/main/java/com/nci/automation/web/TestProperties.java
> -    public static boolean HEADLESS = true;
Done

2024-11-05 18:39 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/Pages/FHQSubmissionPage.java
> +	/* Which of the following individuals is a biological parent of this child? Selected Dropdown*/
Done

2024-11-05 18:40 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/Pages/FHQSubmissionPage.java
> +	//@FindBy(xpath = "(//span[@id='select2-chosen-24'])[1]")
Done

2024-11-06 15:48 UTC, sarwarahmed1 requested changes
Please review comment

2024-11-06 15:48 UTC, sarwarahmed1 commented on src/test/java/ServiceNow/CHARMS/Pages/FHQSubmissionPage.java
> +	//@FindBy(xpath = "//a[@aria-label='Review Family History Questionnaire']//span[contains(text(),'Family History Questionnaire')]")
Is line 192 needed? It's a commented line

2024-11-06 16:03 UTC, merged