CHARMS RAS -  Verifying fields in NV Participant Consent Record and Subject Flags.
CBIIT/CBIIT-Test-Automation pull request #308
Opened 2024-10-30 16:23 UTC by katm007

Verifying fields in NV Participant Consent Record and Subject Flags.

2024-10-31 17:17 UTC, sarwarahmed1 requested changes
Please review comments

2024-10-31 17:17 UTC, sarwarahmed1 commented on src/test/java/ServiceNow/CHARMS/Steps/RAS_All_Steps.java
There are a lot of if statements here that have no code in them, do they serve any purpose?

2024-10-31 17:17 UTC, sarwarahmed1 commented on src/test/java/ServiceNow/CHARMS/Steps/RAS_All_Steps.java
> +        }
Please fix the spacing between each if statement

2024-10-31 17:21 UTC, katm007 commented on src/test/java/ServiceNow/CHARMS/Steps/RAS_All_Steps.java
Yes, they're going to be filled eventually. This is for a method that will complete the consent call in NV for different participants.

2024-10-31 17:23 UTC, katm007 commented on src/test/java/ServiceNow/CHARMS/Steps/RAS_All_Steps.java
> +        }
Do you mean that I should remove the spaces between the {} ?

2024-10-31 17:24 UTC, sarwarahmed1 commented on src/test/java/ServiceNow/CHARMS/Steps/RAS_All_Steps.java
Got it, just wanted to make sure

2024-10-31 17:25 UTC, sarwarahmed1 commented on src/test/java/ServiceNow/CHARMS/Steps/RAS_All_Steps.java
> +        }
Yes

2024-10-31 17:30 UTC, katm007 commented on src/test/java/ServiceNow/CHARMS/Pages/NativeViewCHARMSSubjectFlagsPage.java
> +
Line removed

2024-10-31 17:32 UTC, sarwarahmed1 approved these changes

2024-11-04 17:48 UTC, andreyeve approved these changes

2024-11-04 17:50 UTC, merged