Account activation and deactivation test cases
CBIIT/CBIIT-Test-Automation pull request #310
Opened 2024-10-30 22:47 UTC by hamidnesar

Most of these scenarios are old requirements therefore, there is no StoryId attached to them

2024-10-30 23:41 UTC, matakevin requested changes
Requested some changes/feedback.  Please take a look when you have the chance

2024-10-30 23:41 UTC, matakevin commented on src/test/java/CustomBusiness/Egrants/Features/EgrantsLinksVerificationAndManagementMenu.feature
> +    @ActivateAnAccount @nesarh2 @selenium @Regression
Is there a ticket number you can link to this scenario?

2024-10-30 23:41 UTC, matakevin commented on src/test/java/CustomBusiness/Egrants/Features/EgrantsLinksVerificationAndManagementMenu.feature
> +    @DeactivateAnAccount @nesarh2 @selenium @Regression
Is there a ticket number you can link to this scenario?

2024-10-30 23:41 UTC, matakevin commented on src/test/java/CustomBusiness/Egrants/Steps/EgrantsSearchAndFileManagementSteps.java
Some of the steps in this class have javadoc statements and some don't, is that expected?

2024-10-30 23:41 UTC, matakevin commented on src/test/java/CustomBusiness/Egrants/Steps/QuickLinkVerificationAndManagementMenuSteps.java
> +	public void user_selects_as_qc_person(String qcPerson) {
Is this parameter being used somewhere?

2024-10-31 18:10 UTC, hamidnesar commented on src/test/java/CustomBusiness/Egrants/Features/EgrantsLinksVerificationAndManagementMenu.feature
> +    @DeactivateAnAccount @nesarh2 @selenium @Regression
This is an old requirement, we do not have it in Jira.

2024-10-31 18:14 UTC, hamidnesar commented on src/test/java/CustomBusiness/Egrants/Steps/EgrantsSearchAndFileManagementSteps.java
The steps implemented in the Steps Implementation class would not have Javadoc here. Since Diego's encouraged us to consolidate the declaration and implementation in the same class, new steps have Javadoc because they are implemented here. However, the older steps, which are implemented in a separate class, retain their Javadoc there

2024-10-31 18:31 UTC, hamidnesar commented on src/test/java/CustomBusiness/Egrants/Steps/QuickLinkVerificationAndManagementMenuSteps.java
> +	public void user_selects_as_qc_person(String qcPerson) {
Thanks for pointing it out! The step was not well written, I made the necessary changes.

2024-10-31 18:43 UTC, sarwarahmed1 approved these changes

2024-10-31 19:23 UTC, matakevin approved these changes
LGTM

2024-11-01 11:23 UTC, Mariachaudhry approved these changes

2024-11-01 11:23 UTC, merged