CHARMS Native View Subject Flags verification
CBIIT/CBIIT-Test-Automation pull request #317
Opened 2024-11-07 15:39 UTC by katm007

CHARMS Native View Subject Flags verification

2024-11-07 16:22 UTC, sarwarahmed1 requested changes

2024-11-07 16:22 UTC, sarwarahmed1 commented on src/test/java/ServiceNow/CHARMS/Steps/RAS_Common_Methods.java
> +
Remove extra line on 17

2024-11-07 16:22 UTC, sarwarahmed1 commented on src/test/java/ServiceNow/CHARMS/Steps/RAS_Common_Methods.java
> +
Remove extra line 21

2024-11-07 16:22 UTC, sarwarahmed1 commented on src/test/java/ServiceNow/CHARMS/Steps/RAS_All_Steps.java
> +
Remove extra line 20

2024-11-07 16:22 UTC, sarwarahmed1 commented on src/test/java/ServiceNow/CHARMS/Steps/RAS_All_Steps.java
> +
Remove extra line 26

2024-11-07 17:10 UTC, katm007 commented on src/test/java/ServiceNow/CHARMS/Steps/RAS_Common_Methods.java
> +
Removed all the extra lines!

2024-11-12 20:47 UTC, puzikovam2 approved these changes
approved by @puzikovam2

2024-11-12 21:15 UTC, hamidnesar requested changes
Hi, 
please review the comment.

2024-11-12 21:15 UTC, hamidnesar commented on src/test/java/ServiceNow/CHARMS/Steps/RAS_Common_Methods.java
> +        softAssert.assertEquals(nativeViewCHARMSParticipantDetailsPage.nativeViewPatientDetailsSubjectID.getText().split("-")[0], nativeViewCHARMSParticipantDetailsPage.nativeViewPatientDetailsFamily
Could you use the softAssert from the Hooks class across this Class? Lines 108, 114, 115, 276, 277, 287, 288, 289, 404.

2024-11-12 21:20 UTC, katm007 commented on src/test/java/ServiceNow/CHARMS/Steps/RAS_Common_Methods.java
> +        softAssert.assertEquals(nativeViewCHARMSParticipantDetailsPage.nativeViewPatientDetailsSubjectID.getText().split("-")[0], nativeViewCHARMSParticipantDetailsPage.nativeViewPatientDetailsFamily
This is the softAssert from the Hooks class

2024-11-13 15:26 UTC, sarwarahmed1 approved these changes

2024-11-13 15:28 UTC, merged