Fanconi Screener submission code to run end to end workflow for the Fanconi survey
CBIIT/CBIIT-Test-Automation pull request #318
Opened 2024-11-07 18:39 UTC by sonika-nih

Added code for the Fanconi Screener submission from the portal to run the end to end workflow for the Fanconi survey

2024-11-08 21:06 UTC, katm007 commented on src/test/java/ServiceNow/CHARMS/Playwright/StepsImplementation/FanconiStudy/FanconiSurveyStepsImpl.java
> +      //  page.getByRole(AriaRole.BUTTON, new Page.GetByRoleOptions().setName(FanconiSurveyLoginPage.SUBMIT)).click();
Can this commented out line be removed?

2024-11-08 21:11 UTC, katm007 commented on src/test/java/ServiceNow/CHARMS/Playwright/StepsImplementation/FanconiStudy/FanconiSurveyStepsImpl.java
You're using a containsText() method here, it does not check for the exact match. Is that okay for assertions? It will return True if it finds any substring.

2024-11-13 01:35 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/Playwright/StepsImplementation/FanconiStudy/FanconiSurveyStepsImpl.java
> +      //  page.getByRole(AriaRole.BUTTON, new Page.GetByRoleOptions().setName(FanconiSurveyLoginPage.SUBMIT)).click();
removed

2024-11-15 15:46 UTC, iamdez99 requested changes
Please make requested changes.

2024-11-15 15:46 UTC, iamdez99 commented on src/test/java/ServiceNow/CHARMS/Playwright/Features/FanconiStudy/FanconiSurveyBackgroundInformation.feature
The Regression tag should be @Fanconi_Regression

2024-11-15 15:46 UTC, iamdez99 commented on src/test/java/ServiceNow/CHARMS/Playwright/Features/FanconiStudy/FanconiSurveySexualHistory.feature
The regression tag should be @Fanconi_Regression

2024-11-15 15:46 UTC, iamdez99 commented on src/test/java/ServiceNow/CHARMS/Playwright/Features/FanconiStudy/FanconiSurveySurgicalAndOtherMedicalHistory.feature
The regression tag should be @Fanconi_Regression

2024-11-15 15:46 UTC, iamdez99 commented on src/test/java/ServiceNow/CHARMS/Playwright/Pages/FanconiStudy/FanconiSurveyLoginPage.java
The environment URLs and login credentials for the sidedoor test account are in the TestProperties class. Please use those and remove from here.

2024-11-15 15:46 UTC, iamdez99 commented on src/test/java/ServiceNow/CHARMS/StepsImplementation/FHQSubmissionStepsImpl.java
You are using your own Soft Assert class here. Please use the Soft Assert from the Hooks class which throws the assertAll() in the afterhook and no need to write this statement so many times.

2024-11-18 18:04 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/Playwright/StepsImplementation/FanconiStudy/FanconiSurveyStepsImpl.java
Replaced with the hastext()

2024-11-18 18:05 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/Playwright/Pages/FanconiStudy/FanconiSurveyLoginPage.java
Done

2024-11-18 18:08 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/Playwright/Features/FanconiStudy/FanconiSurveyBackgroundInformation.feature
Added

2024-11-18 18:08 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/StepsImplementation/FHQSubmissionStepsImpl.java
I will make these changes when I will do the cleanup for the FHQ.

2024-11-18 18:31 UTC, katm007 commented on src/test/java/ServiceNow/CHARMS/Playwright/Runners/FanconiStudy/Run_CHARMS_FanconiSurvey_Regression_Test.java
> +        tags = "@Regression1",
Please change this back to Fanconi_Regression

2024-11-18 18:43 UTC, matakevin requested changes
Please review changes requested.  There are a few extra spaces on some feature files but there's a regression runner that is tagged "Regression1".  These should either remain "Regression" or in your case I believe you're using "Fanconi_Regression".

2024-11-18 18:43 UTC, matakevin commented on src/test/java/ServiceNow/CHARMS/Playwright/Features/FanconiStudy/FanconiSurveyBackgroundInformation.feature
> +  @jains @BackgroundInformation @CP2-3178 @CP2-3133 @playwright  @Fanconi_Regression
We could probably get rid of the extra space before the Faconi_Regression tag but a non-issue

2024-11-18 18:43 UTC, matakevin commented on src/test/java/ServiceNow/CHARMS/Playwright/Features/FanconiStudy/FanconiSurveyDemographic.feature
> +  @jains @Demographic @CP2-3178 @CP2-3133 @playwright  @Fanconi_Regression
Same space issue from previous class

2024-11-18 18:43 UTC, matakevin commented on src/test/java/ServiceNow/CHARMS/Playwright/Features/FanconiStudy/FanconiSurveyMedicalHistory.feature
> +  @jains @MedicalHistory @CP2-3178 @CP2-3133 @playwright  @Fanconi_Regression
Same extra space issue

2024-11-18 18:43 UTC, matakevin commented on src/test/java/ServiceNow/CHARMS/Playwright/Features/FanconiStudy/FanconiSurveySexualHistory.feature
> +  @jains @SexualHistory @CP2-3178 @CP2-3133 @playwright  @Fanconi_Regression
Same extra space issue

2024-11-18 18:43 UTC, matakevin commented on src/test/java/ServiceNow/CHARMS/Playwright/Features/FanconiStudy/FanconiSurveySurgicalAndOtherMedicalHistory.feature
> +  @jains @SurgicalMedicationHistory @CP2-3178 @CP2-3133 @playwright  @Fanconi_Regression
Same extra space issue

2024-11-18 18:43 UTC, matakevin commented on src/test/java/ServiceNow/CHARMS/Playwright/Runners/FanconiStudy/Run_CHARMS_FanconiSurvey_Regression_Test.java
> +        tags = "@Regression1",
"Regression1" shouldn't be a tag for a regression runner.

2024-11-18 19:32 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/Playwright/Features/FanconiStudy/FanconiSurveySurgicalAndOtherMedicalHistory.feature
> +  @jains @SurgicalMedicationHistory @CP2-3178 @CP2-3133 @playwright  @Fanconi_Regression
done

2024-11-18 19:32 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/Playwright/Features/FanconiStudy/FanconiSurveySexualHistory.feature
> +  @jains @SexualHistory @CP2-3178 @CP2-3133 @playwright  @Fanconi_Regression
done

2024-11-18 19:32 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/Playwright/Features/FanconiStudy/FanconiSurveyMedicalHistory.feature
> +  @jains @MedicalHistory @CP2-3178 @CP2-3133 @playwright  @Fanconi_Regression
done

2024-11-18 19:33 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/Playwright/Features/FanconiStudy/FanconiSurveyDemographic.feature
> +  @jains @Demographic @CP2-3178 @CP2-3133 @playwright  @Fanconi_Regression
done

2024-11-18 19:33 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/Playwright/Features/FanconiStudy/FanconiSurveyBackgroundInformation.feature
> +  @jains @BackgroundInformation @CP2-3178 @CP2-3133 @playwright  @Fanconi_Regression
done

2024-11-18 19:36 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/Playwright/Runners/FanconiStudy/Run_CHARMS_FanconiSurvey_Regression_Test.java
> +        tags = "@Regression1",
Done

2024-11-18 19:43 UTC, matakevin approved these changes
LGTM

2024-11-19 15:13 UTC, katm007 approved these changes
Approved!

2024-11-19 17:09 UTC, iamdez99 requested changes

2024-11-19 17:09 UTC, iamdez99 commented on src/test/java/ServiceNow/CHARMS/Playwright/Pages/FanconiStudy/FanconiSurveyPage.java
Remove side door test account credentials from this class please.

2024-11-19 19:01 UTC, sonika-nih commented on src/test/java/ServiceNow/CHARMS/Playwright/Pages/FanconiStudy/FanconiSurveyPage.java
Done

2024-11-19 20:04 UTC, iamdez99 requested changes

2024-11-19 20:04 UTC, iamdez99 commented on src/test/java/ServiceNow/CHARMS/Playwright/Pages/FanconiStudy/FanconiSurveyPage.java
I still see variables for Side door login and URLs should be in the TestProperties class.

2024-11-21 14:23 UTC, hamidnesar approved these changes
Approved

2024-11-21 15:02 UTC, merged