GitHub Actions - ADDING WORKFLOWS
CBIIT/CBIIT-Test-Automation pull request #319
Opened 2024-11-07 21:40 UTC by iamdez99

2024-11-08 14:06 UTC, katm007 commented on src/main/java/com/nci/automation/web/TestProperties.java
> +    public static boolean HEADLESS = false;
Should headless be false now?

2024-11-08 19:16 UTC, georgeb79 approved these changes

2024-11-08 19:47 UTC, katm007 commented on src/test/java/GrantsApps/EM/playwright/Steps/EMFlowSteps.java
> +    String name;
Unused variable on line 263?

2024-11-08 19:48 UTC, katm007 commented on src/test/java/GrantsApps/GrantsRunners/EnterpriseMaintenance/RunEMProgressionTest.java
> +
Please remove empty line 13

2024-11-12 19:51 UTC, Mariachaudhry approved these changes

2024-11-12 20:13 UTC, Mariachaudhry requested changes

2024-11-12 20:13 UTC, Mariachaudhry commented on src/main/java/com/nci/automation/web/TestProperties.java
> +    public static boolean HEADLESS = false;
Please update it back to true!

2024-11-13 17:08 UTC, hamidnesar requested changes
Hi, 
Please review the comments. Thanks!

2024-11-13 17:08 UTC, hamidnesar commented on src/test/java/GrantsApps/EM/selenium/Features/Managing User Accounts.feature
> +    #REVIEW CREATE BUTTON, INACTIVE CANCER ACTIVITIES?
Commented line 36 can be removed if no longer in use

2024-11-13 17:08 UTC, hamidnesar commented on src/test/java/GrantsApps/EM/selenium/Utils/EM_Common_Methods.java
> +        WebDriverWait wait = new WebDriverWait(webDriver, Duration.ofSeconds(10));
We could use Wait from the CommonUtils class:

![image](https://github.com/user-attachments/assets/eb9ccb9e-5ba1-48a6-a3e5-e1151363dd20)

2024-11-13 17:08 UTC, hamidnesar commented on src/test/java/ServiceNow/CHARMS/Runners/Run_CHARMS_RAS_Regression_Test.java
> +		tags = "@TestingActions",
Please use @RAS_Regression on line 11

2024-11-13 17:08 UTC, hamidnesar commented on src/test/java/ServiceNow/CHARMS/Features/RasopathyStudy/RAS Entire Flow.feature
>  #      | charmsras5@yahoo.com | RASTest2023$$ | screenerScenario4 | IIQScenario4 | RASSurveyScenario4 |
This scenario should not be tagged @Regression, instead it should be @In-Progress since there are several commented lines.

2024-11-14 21:31 UTC, merged