Regression tests fixes
CBIIT/CBIIT-Test-Automation pull request #326
Opened 2024-11-15 21:42 UTC by lfcabrera14

Regression tests fixes

2024-11-19 18:13 UTC, katm007 commented on src/test/java/ServiceNow/PlatformBusinessApps/SSJ/playwright/Steps/OWM_Vacancy_Manager_Steps.java
> +
Please remove the extra spaces on lines 309, 310

2024-11-19 18:13 UTC, katm007 commented on src/test/java/ServiceNow/PlatformBusinessApps/SSJ/playwright/StepsImplementation/OWM_Vacancy_Manager_StepsImpl.java
> +
Please remove empty line 19

2024-11-19 18:14 UTC, katm007 commented on src/test/java/ServiceNow/PlatformBusinessApps/SSJ/playwright/StepsImplementation/Reset_Account_StepsImpl.java
> +        Playwright_ServiceNow_Common_Methods.side_Door_Test_Account_Login_Impersonate("Maria Chaudhry");
It might be better to store this user name in a constants file, but it's up to you

2024-11-21 14:39 UTC, hamidnesar requested changes
Hi, 
Please review the comments. Thanks!

2024-11-21 14:39 UTC, hamidnesar commented on src/test/java/ServiceNow/PlatformBusinessApps/SSJ/playwright/Steps/OWM_Vacancy_Manager_Steps.java
> +
Agree with Kate

2024-11-21 14:39 UTC, hamidnesar commented on src/test/java/ServiceNow/PlatformBusinessApps/SSJ/playwright/StepsImplementation/OWM_Vacancy_Manager_StepsImpl.java
> +
Agree

2024-11-21 14:39 UTC, hamidnesar commented on src/test/java/ServiceNow/PlatformBusinessApps/SSJ/playwright/StepsImplementation/OWM_Vacancy_Manager_StepsImpl.java
> +import java.io.PrintWriter;
Please remove these three unused imports

2024-11-21 20:03 UTC, Mariachaudhry requested changes

2024-11-21 20:03 UTC, Mariachaudhry commented on src/test/java/ServiceNow/PlatformBusinessApps/SSJ/playwright/StepsImplementation/OWM_Vacancy_Manager_StepsImpl.java
Please remove line 19 and line 637

2024-11-21 20:03 UTC, Mariachaudhry commented on src/test/java/appsCommon/Pages/Playwright_Common_Locators.java
please add doc string comments for last method

2024-11-21 23:27 UTC, lfcabrera14 commented on src/test/java/ServiceNow/PlatformBusinessApps/SSJ/playwright/Steps/OWM_Vacancy_Manager_Steps.java
> +
done

2024-11-21 23:28 UTC, lfcabrera14 commented on src/test/java/ServiceNow/PlatformBusinessApps/SSJ/playwright/StepsImplementation/OWM_Vacancy_Manager_StepsImpl.java
> +
done

2024-11-21 23:28 UTC, lfcabrera14 commented on src/test/java/ServiceNow/PlatformBusinessApps/SSJ/playwright/StepsImplementation/Reset_Account_StepsImpl.java
> +        Playwright_ServiceNow_Common_Methods.side_Door_Test_Account_Login_Impersonate("Maria Chaudhry");
done

2024-11-21 23:28 UTC, lfcabrera14 commented on src/test/java/ServiceNow/PlatformBusinessApps/SSJ/playwright/StepsImplementation/OWM_Vacancy_Manager_StepsImpl.java
> +import java.io.PrintWriter;
done

2024-11-21 23:28 UTC, lfcabrera14 commented on src/test/java/ServiceNow/PlatformBusinessApps/SSJ/playwright/Steps/OWM_Vacancy_Manager_Steps.java
done

2024-11-21 23:28 UTC, lfcabrera14 commented on src/test/java/ServiceNow/PlatformBusinessApps/SSJ/playwright/StepsImplementation/OWM_Vacancy_Manager_StepsImpl.java
done

2024-11-21 23:28 UTC, lfcabrera14 commented on src/test/java/appsCommon/Pages/Playwright_Common_Locators.java
done

2024-11-22 14:41 UTC, hamidnesar approved these changes
Looks good!

2024-11-22 14:41 UTC, hamidnesar commented on src/test/java/ServiceNow/PlatformBusinessApps/SSJ/playwright/Steps/OWM_Vacancy_Manager_Steps.java
> +    @Then("User can verify that vacancies with subfilter All are by default sorted by number of applicants in ascending order")
please add a space between 291 and 292

2024-11-22 18:05 UTC, lfcabrera14 commented on src/test/java/ServiceNow/PlatformBusinessApps/SSJ/playwright/Steps/OWM_Vacancy_Manager_Steps.java
> +    }
yes I have it tagged in progress

2024-11-22 18:12 UTC, lfcabrera14 commented on src/test/java/ServiceNow/PlatformBusinessApps/SSJ/playwright/Steps/OWM_Vacancy_Manager_Steps.java
> +    @Then("User can verify that vacancies with subfilter All are by default sorted by number of applicants in ascending order")
done

2024-11-22 19:06 UTC, Mariachaudhry approved these changes

2024-11-22 19:08 UTC, katm007 approved these changes
Approved!

2024-11-22 19:10 UTC, katm007 commented on src/test/java/appsCommon/Pages/Playwright_Common_Locators.java
Missing method description in this doc string

2024-11-22 19:15 UTC, lfcabrera14 commented on src/test/java/appsCommon/Pages/Playwright_Common_Locators.java
done

2024-11-22 19:17 UTC, katm007 approved these changes

2024-11-22 19:40 UTC, alenaminsk approved these changes

2024-11-22 19:42 UTC, merged