CHARMS - Verifying fields in Native View Subject Flags
CBIIT/CBIIT-Test-Automation pull request #332
Opened 2024-11-27 17:18 UTC by katm007

2024-11-27 18:48 UTC, hamidnesar requested changes
Hi Kate, 
Please review the comments. Thanks!

2024-11-27 18:48 UTC, hamidnesar commented on src/test/java/ServiceNow/CHARMS/Features/RasopathyStudy/RAS Entire Flow.feature
>  #    Then screener data from "<ScreenerScenario>" is verified
Can this commented line be removed or uncommented since the scenario is tagged as Regression?

2024-11-27 18:48 UTC, hamidnesar commented on src/test/java/ServiceNow/CHARMS/Features/RasopathyStudy/RAS Entire Flow.feature
> +  @JUAREZDS @RAS_STUDY @2CP2-2332 @Smoke @RAS_Regression @selenium @RAS_Regression
Please remove the the duplicate @RAS_Regression tag

2024-11-27 18:48 UTC, hamidnesar commented on src/test/java/ServiceNow/CHARMS/Steps/RAS_Consent_Call_Steps.java
> +    @Then("selects {string} for Age-appropriate assent obtained")
This step is missing the Javadoc

2024-11-27 21:23 UTC, katm007 commented on src/test/java/ServiceNow/CHARMS/Features/RasopathyStudy/RAS Entire Flow.feature
>  #    Then screener data from "<ScreenerScenario>" is verified
No, that's something that will be added in the future

2024-11-27 21:23 UTC, katm007 commented on src/test/java/ServiceNow/CHARMS/Features/RasopathyStudy/RAS Entire Flow.feature
> +  @JUAREZDS @RAS_STUDY @2CP2-2332 @Smoke @RAS_Regression @selenium @RAS_Regression
Removed!

2024-11-27 21:23 UTC, katm007 commented on src/test/java/ServiceNow/CHARMS/Steps/RAS_Consent_Call_Steps.java
> +    @Then("selects {string} for Age-appropriate assent obtained")
Added a javadoc

2024-11-27 21:56 UTC, hamidnesar approved these changes
Reviewed and approved

2024-11-28 02:12 UTC, Mariachaudhry approved these changes

2024-11-29 17:10 UTC, alenaminsk approved these changes

2024-11-29 20:11 UTC, merged