Analysis Tools - Implemented test cases for JPSurv with Playwright
CBIIT/CBIIT-Test-Automation pull request #339
Opened 2024-12-06 19:06 UTC by sgugulothu

Analysis Tools - Implemented test cases for JPSurv with Playwright

2024-12-09 19:39 UTC, hamidnesar requested changes
Hi, 
Please review the comments. Thanks!

2024-12-09 19:39 UTC, hamidnesar commented on src/test/java/AnalysisTools/JPSurv/Features/JPSurvHomePagePlaywright.feature
> +    Then Verify user is able to hide the configuration panel
Are all of them just Smoke tests? I did not see any of them tagged as @Regression

2024-12-09 19:39 UTC, hamidnesar commented on src/test/java/AnalysisTools/JPSurv/Steps/JPSurvHomePagePlaywrightSteps.java
> +
Please remove the empty line 16

2024-12-09 19:39 UTC, hamidnesar commented on src/test/java/AnalysisTools/JPSurv/Utils/JPSurvConstants.java
> +    public static String JOB_SUBMITTED_TEXT = "Your job has been submitted";
I would suggest declaring these constants as Final

2024-12-09 19:39 UTC, hamidnesar commented on src/main/java/com/nci/automation/web/TestProperties.java
> +    public static String JP_SURV_TEST_URL = "https://analysistools-dev.cancer.gov/jpsurv/";
The string says TEST URL but the URL is for Dev tier.

2024-12-09 21:14 UTC, hamidnesar approved these changes
Looks good! 
Make sure you pull the latest from master

2024-12-10 16:16 UTC, katm007 commented on src/main/java/com/nci/automation/web/TestProperties.java
> +    public static boolean HEADLESS = false;
please change headless back to true

2024-12-10 16:43 UTC, alenaminsk approved these changes

2024-12-10 22:09 UTC, matakevin approved these changes
LGTM

2024-12-11 17:54 UTC, sarwarahmed1 approved these changes

2024-12-11 18:46 UTC, merged