Analysis Tools - Implemented 2 test cases JPSURV Application
CBIIT/CBIIT-Test-Automation pull request #350
Opened 2024-12-13 21:03 UTC by sgugulothu

Analysis Tools - Implemented 2 test cases JPSURV Application

2024-12-16 22:54 UTC, sonika-nih approved these changes
Approved

2024-12-17 23:39 UTC, matakevin requested changes
Please review the requested changes.

2024-12-17 23:39 UTC, matakevin commented on src/test/java/ANALYSIS_TOOLS/JPSurv/stepsImplementations/JPSurvHomePagePlaywrightStepImp.java
> +     * @param string
Can you name your parameter what it is?

2024-12-17 23:39 UTC, matakevin commented on src/test/java/ANALYSIS_TOOLS/JPSurv/stepsImplementations/JPSurvHomePagePlaywrightStepImp.java
> +    public static void checkRelaxProportionalityAndCutPoint(String string) {
Same here.  You string param should be labeled what its for

2024-12-18 18:31 UTC, merged