updated Award Nomination scenarios. NCCR scenario
CBIIT/CBIIT-Test-Automation pull request #352
Opened 2024-12-19 19:28 UTC by alenaminsk

2024-12-20 19:03 UTC, matakevin requested changes
Please review the commented line in your feature file!

2024-12-20 19:03 UTC, matakevin commented on src/test/java/ITSM/ITPG/features/Nativeview.feature
>    #  Then Click on Elevate Permision
Is this line not needed anymore?

2024-12-20 19:42 UTC, katm007 commented on src/test/java/ServiceNow/AwardNomination/StepsImplementation/AwardNominationStepsImplementation.java
> +        awardNominationPage.chooseFileButton.sendKeys("C:\\Users\\nekrashevicha2\\Desktop\\projectIDEA\\src\\test\\java\\ServiceNow\\AwardNomination\\Attachments\\AWARD_NOMINATION.docx");
This won't work during our regression tests because this path only exists on your system. You need to make this path relative to wherever the project folder is located

2024-12-23 14:28 UTC, alenaminsk commented on src/test/java/ITSM/ITPG/features/Nativeview.feature
updated

2024-12-27 16:20 UTC, katm007 approved these changes
Approved!

2024-12-27 19:59 UTC, lfcabrera14 commented on src/test/java/PLATFORM_BUSINESS/OA_Intake/steps/OAIntakeSteps.java
empty line on line 11

2024-12-27 21:19 UTC, alenaminsk commented on src/test/java/PLATFORM_BUSINESS/OA_Intake/steps/OAIntakeSteps.java
updated

2024-12-30 18:29 UTC, lfcabrera14 approved these changes
approved

2024-12-31 16:37 UTC, Mariachaudhry approved these changes

2024-12-31 16:37 UTC, merged