CHARMS - Framework updates + automation script for submitting the RAS Physical Activities survey
CBIIT/CBIIT-Test-Automation pull request #355
Opened 2024-12-20 19:24 UTC by katm007

This PR is a bit long, but most of the changes are updates to package file names.

2024-12-26 17:36 UTC, sarwarahmed1 requested changes

2024-12-26 17:36 UTC, sarwarahmed1 commented on src/test/java/CHARMS/features/rasopathyStudy/RAS Consent Scenarios.feature
> +  @muzipovay2 @RAS_STUDY @CP2-4088 @selenium @RAS_Regression @Progression
Is this test case still in progress? If not please change to Regression tag

2024-12-26 19:05 UTC, katm007 commented on src/test/java/CHARMS/features/rasopathyStudy/RAS Consent Scenarios.feature
> +  @muzipovay2 @RAS_STUDY @CP2-4088 @selenium @RAS_Regression @Progression
Done!

2024-12-26 19:06 UTC, sarwarahmed1 approved these changes

2024-12-26 19:07 UTC, alenaminsk approved these changes

2024-12-27 17:49 UTC, lfcabrera14 approved these changes
approved

2024-12-30 18:54 UTC, merged